### ISSUE TITLE
[Bug] reloadClientData() does not reload site data

### ISSUE THREAD

**Issue by Blobson** [react-static/react-static#1093]
**Short description**
I am using **site.yaml** file to store site data and in development mode I want to hot-reload site data on every change in **site.yaml**.

**Steps to reproduce the issue**
1. Create new project using **react-static v7.0.5** using blank template.
2. Add **data/site.yaml** with following contents to the project:
```yaml
title: My Site!
```
3. You will need to install **node-watch** and **js-yaml** for the next step:
```
$ yarn add node-watch js-yaml
```
4. Add **getSiteData** and a watcher for **data/site.yaml** inside **static.config.js** like this:
```javascript
import fs from 'fs'
import path from 'path'
import yaml from 'js-yaml'
import watch from 'node-watch'
import { reloadClientData } from 'react-static/node'

const dataDir = path.join(__dirname, 'data')

watch(dataDir, { recursive: true, filter: /\.(?:yaml|yml)$/ }, (evt, name) => {
  console.log(`Detected changes in '${name}',  reloading client data...`)
  reloadClientData()
})

export default {
  maxThreads: 1, // Remove this when you start doing any static generation
  getSiteData: () => {
    try {
      const rawSiteData = fs.readFileSync(path.join(dataDir, 'site.yaml'))
      const yamlSiteData = yaml.safeLoad(rawSiteData)
      console.log('SiteData: ', yamlSiteData)
      return yamlSiteData
    } catch(e) {
      console.error(e)
      return {}
    }
  }
}
```
5. Add use of `const { title } = useSiteData()` to the **src/App.js** component like this:
```javascript
import React, { Suspense } from 'react'
import { useSiteData } from 'react-static'

import './app.css'
import logo from './logo.png'

const Title = () => {
  const { title } = useSiteData()
  return (
    <h1>{title}</h1>
  )
}

const App = () => (
  <Suspense fallback="Loading...">
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <Title />
      </header>
    </div>
  </Suspense>
)

export default App
```
6. Start development server
7. Try editing **title** in **data/site.yaml** and you'll see that changes does not hot-reload.
Also in the stdout of dev server you'll see that `reloadClientData()` is called but it does not trigger call for `getSiteData()`.

**Solution that worked for me**
For now the only solution that worked for me is to add: 
```javascript
latestState = await fetchSiteData(latestState)
``` 
inside `reloadClientData()` inside **runDevServer.js** [here](https://github.com/nozzle/react-static/blob/b8e2e1ab14fee70a1a8a40d9eda3d97d90c4ee01/packages/react-static/src/static/webpack/runDevServer.js#L222).

The only downside is that now `getSiteData()` is called twice at the start of development server.

**Comment by tannerlinsley** [comment]
The double call will be fixed in the patch version I'll release later today. Huzzah!

**Comment by theWebalyst** [comment]
Doesn't this fix also require the above mod to `runDevServer.js`:

```latestState = await fetchSiteData(latestState)```

**Comment by Blobson** [comment]
It doesn't fully work and I think the reason is the  `fetchSiteData()` call missing in runDevServer.js

**Comment by theWebalyst** [comment]
I tried putting that in without success. It's it just a matter of editing or would I need to do anything else? I have RS installed globally with yarn.

On 11 August 2019 18:09:10 BST, Vladimir Klimov <notifications@github.com> wrote:
>It doesn't fully work and I think the reason is the  `fetchSiteData()`
>call missing in runDevServer.js
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/react-static/react-static/issues/1093#issuecomment-520244403

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Blobson** [comment]
Try editing version inside node_modules/react-static/... 
Unfortunately, I can't check it myself because I am away from my PC.

**Comment by theWebalyst** [comment]
Still no joy with this in my node_modules RS:
```
  reloadClientData.current = async () => {
    latestState = await fetchSiteData(latestState)
    socket.emit('message', { type: 'reloadClientData' })
  }
```

**Comment by Blobson** [comment]
As I remember Tenner had reworked the code a bit. I can take a closer look at it after I return from vacation on 18th of august.

**Comment by SleeplessByte** [comment]
@theWebalyst certainly, although your issue might _relate_ but not _equate_. After the maintenance update I'll actively work on React-Static including these issues.

**Comment by krishan711** [comment]
Hey i'm running into the same problem now. I'd love to contribute and will start based on the above. If anyone has more insights im sure it would be helpful

**Comment by krishan711** [comment]
Hey I made a PR to try and fix this by adding `await buildDevRoutes` into the reloadClientData call instead of just `fetchSiteData`. It seems to work locally, im trying to build a package to deploy now to test fully.

**Comment by krishan711** [comment]
@SleeplessByte i believe this can be closed now? it works with my locally built version `"@kibalabs/react-static": "7.2.3-kiba.2"` if anyone else has the same problem before 7.3.0 is release 👍

**Comment by SleeplessByte** [comment]
@krishan711 :)
