### ISSUE TITLE
[Docs] Animated Routes guide outdated

### ISSUE THREAD

**Issue by Ontopic** [react-static/react-static#1103]
In the example code the import from react-spring should be changed to the code below.

`import { Transition, animated } from 'react-spring/renderprops'`

On top of that the example code is not working, but I'll have to dig deeper to see why.

**Comment by Cinamonas** [comment]
The example could be broken because of #1118.

**Comment by sw-yx** [comment]
:( but an updated example can be found here https://github.com/nozzle/react-static/issues/1118#issuecomment-492195423

**Comment by SleeplessByte** [comment]
`reach-router` example using #1181 was listed here: https://github.com/nozzle/react-static/issues/1162#issuecomment-492302334

**Comment by SleeplessByte** [comment]
Closing this issue as a PR was just merged for this.
