### ISSUE TITLE
[Bug] 7.0.10 in development causes SourceMapConsumer.initialize errors

### ISSUE THREAD

**Issue by hellojere** [react-static/react-static#1155]
### Reporting a bug?

After upgrading from `7.0.9` to `7.0.10` my development environment fails to build giving the following error: 

```console
  Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer

  - read-wasm.js:8 readWasm
    [react-static-prismic-v7]/[react-hot-loader]/[source-map]/lib/read-wasm.js:8:13

  - wasm.js:25 wasm
    [react-static-prismic-v7]/[react-hot-loader]/[source-map]/lib/wasm.js:25:16

  - source-map-consumer.js:264 BasicSourceMapConsumer.then.that
    [react-static-prismic-v7]/[react-hot-loader]/[source-map]/lib/source-map-consumer.js:264:14
```

This seems to happen when I'm importing the following package: 

```
import Prismic from "prismic-javascript";
```

When `prismic-javascript` is commented out, the local server starts as expected. 

Directly including this package in the `static.config.js` does not produce this error on a clean React Static install, but when calling functions from other files that have this imported, the build does not work on `7.0.10` for some reason.

Everything works fine on production.

**Comment by tannerlinsley** [comment]
Interesting. I'll check into this and figure out what is going on. Clearly it has something to do with the new hot-loader changes.

**Comment by emtesenair** [comment]
I'm facing the issue in 7.0.9.

I was not able to work around the issue as @hellojere described by directing including the `prismic-javascript` package in `static.config.js`.

**Comment by hellojere** [comment]
@emtesenair what versions of the RS plugins do you have? 

Mine are: 
```json
    "react-static": "7.0.9",
    "react-static-plugin-reach-router": "7.0.8",
    "react-static-plugin-sitemap": "7.0.8",
    "react-static-plugin-source-filesystem": "7.0.8",
    "react-static-plugin-styled-components": "7.0.8"
```

Couldn't work around the issue either, but wasn't able to reproduce it on a fresh install by just including the `prismic-javascript` package in `static.config.js`, so thought to mention it here.

**Comment by tannerlinsley** [comment]
I suggest starting a fresh project and migrating your code until you don't the culprit.

Tanner Linsley

**Comment by emtesenair** [comment]
I using the below from a fresh project:

```
    "react-router-dom": "^5.0.0",
    "react-static": "^7.0.9",
    "react-static-plugin-react-router": "^7.0.10",
    "react-static-plugin-sitemap": "^7.0.0",
    "react-static-plugin-source-filesystem": "^7.0.0"
```

The only working solution is to start the app without using `prismic-javascript` then add after spin up.

@hellojere What version of `prismic-javascript` are you running?

**Comment by hellojere** [comment]
@emtesenair Can't, unfortunately, add it after spin up myself, as I'm using it during the build process as well. 

Using the following: 

```json
"prismic-dom": "^2.1.0",
"prismic-javascript": "^2.0.3",
```

**Comment by arlair** [comment]
My issue was a [apollo-fetch](https://github.com/apollographql/apollo-fetch) call.

I tried changing to [graphql-request](https://github.com/prisma/graphql-request), but have the same problem.

It might be related to [this source-map issue about fetch](https://github.com/mozilla/source-map/issues/349) as these libraries and `prismic-javascript` all use fetch.

This [react-hot-loader issue also references the source-map issue](https://github.com/gaearon/react-hot-loader/issues/1088#issuecomment-448103940).

**Comment by fresh5447** [comment]
Same issue here. Anyone still working on this?

**Comment by fresh5447** [comment]
I did find a workaround to at least get us developing.. Just set the node env to production at the top of `static.config.js`

```
process.env.NODE_ENV = 'production'
import Prismic from 'prismic-javascript'
```

**Comment by hellojere** [comment]
This indeed seems to be a working workaround. Thanks, happy to be able to upgrade at least.

**Comment by guill3m** [comment]
I was having the same issue and eventually, we found the following workaround as all seemed to point to source map generation being the culprit.

Create a `node.api.js` file in your root folder and add the following:

```
export default () => ({
  webpack: config => {
    config.devtool = process.env.NODE_ENV === 'production' ? false : 'eval'
    return config
  },
})
```

Eval source maps seem to be working fine, you could also just set it to `false` if you prefer, any other value seemed to fail in our case.

**Comment by fresh5447** [comment]
@guill3m  - wow this works! Thank you so much! Can you point me to any resources on how you knew to use `node.api.js` for this?

**Comment by SleeplessByte** [comment]
As per https://github.com/react-static/react-static/issues/1155#issuecomment-496150754, this actually confirms that it's an upstream issue (see links at https://github.com/react-static/react-static/issues/1155#issuecomment-489444484). 

Will close for now! Please open a new issue if there is an upstream fix.

**Comment by simianarmy** [comment]
Turning off sourcemaps doesn't feel like a solution to me

**Comment by SleeplessByte** [comment]
It's a very valid workaround! Thanks for sharing :)

**Comment by solyasa** [comment]
Failed to compile.

You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mapping
s.wasm': ... }) before using SourceMapConsumer


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
