### ISSUE TITLE
[Feature] Disable url-loader's generation of DataUrls

### ISSUE THREAD

**Issue by benedfit** [react-static/react-static#1157]
I have a big old site, and DataUrls for files loaded via `url-loader` actually bloats my overall HTML payload when I upload to Netlify. Would it be possible to provide a means to disable them?

I'm currently doing this by hacking together my own plugin that sets `query.limit` of `url-loader` to 1 (https://github.com/newhighsco/destiny-clan-warfare/blob/master/plugins/plugin-webpack/node.api.js#L9-L12). It's not the greatest solution because I'm manually replicating `query.name` from https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/webpack/rules/fileLoader.js#L14.

~~On a side-note, it would be great to expose all of the file name patterns used in the internals of react-static for use in plugins so that they remain consistent~~ Ignored me, I forgot about `defaultLoaders` exposed by https://github.com/nozzle/react-static/blob/master/docs/plugins/node-api.md#webpack

Additionally, I think that files may actually be inlined during the "node" stage at https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/webpack/rules/fileLoader.js#L2-L8, because I believe `url-loader` defaults to DataUrls for everything if no limit is set

**Comment by Pixelatex** [comment]
Related to #1221

**Comment by Pixelatex** [comment]
We should fix the limit to prevent everything from being inlined but it might also be useful to create a plugin that allows you to customise the image/file rule part.
