### ISSUE TITLE
[Discussion] add Head (react-helmet) to all template examples?

### ISSUE THREAD

**Issue by sw-yx** [react-static/react-static#1161]
**Is your feature request related to a problem? Please describe.**
most people forget to set up helmet, but this is important to have

**Describe the solution you'd like**
enourage it by adding it to all template examples

what do you think?

**Comment by tannerlinsley** [comment]
Great idea

Tanner Linsley

**Comment by sw-yx** [comment]
lol i guess its my job to do this? not stale

**Comment by baebb** [comment]
Yes pls!

Noobs like myself would be interested in how to set up head tags:
- for all routes
- for specific routes
