### ISSUE TITLE
[Bug] Location props missing in static routes and 404s on dynamic routes

### ISSUE THREAD

**Issue by dgavara** [react-static/react-static#1162]
I was just trying basic template (V7). When using @reach/router, I can access location props for dynamic routes but not for static routes.

***Dynamic Route***

![image](https://user-images.githubusercontent.com/40208273/56968781-c689cd00-6b31-11e9-9856-ce035743fb71.png)

***Static Route***

![image](https://user-images.githubusercontent.com/40208273/56968854-e91be600-6b31-11e9-8476-2f69c6ac801e.png)

Also `addPrefetchExcludes(['dynamic'])` seems not working. I still see 404's on dynamic routes eventhous it was included.

![image](https://user-images.githubusercontent.com/40208273/56968972-297b6400-6b32-11e9-852e-874c4de998c2.png)

**Comment by SleeplessByte** [comment]
You can use `useLocation` or `Location` to capture the location in these routes.

**Comment by simonunlikely** [comment]
Any news on that ? It's kind of a problem not being able to transfer props from top level app to inner routes

**Comment by SleeplessByte** [comment]
> Any news on that ? It's kind of a problem not being able to transfer props from top level app to inner routes

> You can use `useLocation` or `Location` to capture the location in these routes.

**Comment by simonunlikely** [comment]
Hey, thanks for your answer ! useLocation works for reading location but what if we want to transfer other props ? In the case of building animated routes transitions we need to pass through some custom props to our routes components but <Routes /> only passes is404

**Comment by SleeplessByte** [comment]
Which prop do you need? For animated route you probably really only need `location.pathname`. Alternatively, use https://github.com/nozzle/react-static/pull/1181 or wait for it to be merged, so you can use:
```jsx
<Routes default render={
  ({ routePath, getComponentForPath }): React.ReactNode => {
    const Comp = getComponentForPath(routePath)
    return React.cloneElement(Comp, { ..whateverpropsyoulike...})})
} />
```

Or better yet:
```jsx
<Routes default render={({ routePath, getComponentForPath }) => {
  // Using the routePath as the key, both routes will render at the same time for the transition
  return (
    <Transition
       native
       items={routePath}
       from={{ transform: 'translateY(100px)', opacity: 0 }}
       enter={{ transform: 'translateY(0px)', opacity: 1 }}
       leave={{ transform: 'translateY(100px)', opacity: 0 }}
   >
   {item => props => {
     const Comp = getComponentForPath(item)
     return (
       <animated.div style={props}>
         {Comp}
       </animated.div>
      )
   }}
   </Transition>
 )
}}} />
```
