### ISSUE TITLE
[Bug] CSS Module + ReactRouter: ClassNames aren't added to the generated HTML

### ISSUE THREAD

**Issue by rickyrombo** [react-static/react-static#1166]
The inital load of any of my pages lacks the proper classes, thus the stylling is all wrong on initial load.

### Environment

```
  System:
    OS: Windows 10
    CPU: (8) x64 AMD FX(tm)-8350 Eight-Core Processor
    Memory: 16.56 GB / 31.98 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.3.0 - C:\Users\me\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
    Internet Explorer: 11.0.17763.1
  npmPackages:
    react: ^16.8.2 => 16.8.6
    react-dom: ^16.8.2 => 16.8.6
    react-router-dom: ^5.0.0 => 5.0.0
    react-static: ^7.0.0 => 7.0.10
    react-static-plugin-css-modules: ^7.0.8 => 7.0.8
    react-static-plugin-react-router: ^7.0.8 => 7.0.8
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0
    react-transition-group: ^4.0.0 => 4.0.0
```

### Expected Behavior

`yarn start` and `yarn build` yield same result.
Initial load has classNames/styles as appropriate.

Note that navigation using `<Link />` components causes rerendering of that particular element, thus causing the classNames to get applied.

### Reproducible Demo

https://github.com/rickyrombo/react-static-css-modules-bug

**Comment by Shipleaves** [comment]
This affects me too, would be great to see this fixed.

**Comment by silvenon** [comment]
It looks fine, but it's a bit hard to figure out what you were trying to achieve because it's just random demo styles. Could you explain your demo?

**Comment by benedfit** [comment]
@rickyrombo I'm assuming that when you run `yarn start` you get the correct styles, but not when you run `yarn build`?

**Comment by rickyrombo** [comment]
@benedfit  correct. the outputted static HTML does not contain the class names on the elements.

> @rickyrombo I'm assuming that when you run `yarn start` you get the correct styles, but not when you run `yarn build`?

Correct. Note that the index page has no styling on initial load. Then click the link to go to foo, and click the link to go back, and the styles get mounted.

**Comment by benedfit** [comment]
This is the same behaviour I experience with my custom Stylus/CSS modules plugin. I’ve been able to get around it by also having everything export during the ‘node’ stage too, but this adds overhead to the build process

**Comment by mnosuk** [comment]
same as me!

I used emotion to styled my react-static app and i also have this problem.

I try to

`yarn add react-static-plugin-emotion` and also get the error like this

![Screen Shot 2019-05-28 at 12 50 29 PM](https://user-images.githubusercontent.com/12839963/58453987-3ac28b00-8147-11e9-8041-7bf68dd689b2.png)

**Comment by benedfit** [comment]
After updating to v7.1.0 this issue was resolved for me, and I was able to remove the additional code I mentioned in https://github.com/react-static/react-static/issues/1166#issuecomment-491948441 and classes rendered as expected https://github.com/newhighsco/destiny-clan-warfare/commit/fb803e7b7ff5cdcbdd421b1049be476d7ea5c8e5

**Comment by DominikGuzei** [comment]
I just ran into this issue with the latest `react-static@7.2.3` version. The stylesheet gets generated correctly but the built DOM does not have the classes assigned - this only happens after the react app was mounted. @benedfit can you tell me how you solved the issue?

**Comment by SleeplessByte** [comment]
Seems to be solved / have a good workaround.
