### ISSUE TITLE
[Docs] Update Material UI Guide for v4

### ISSUE THREAD

**Issue by jared1000** [react-static/react-static#1179]
### Reporting a bug?

The guide in the repository doesn't work for the latest Material UI. API for SSR has changed. MUI v4 is still in Beta, but an update needs to be made. Any suggestions of how it can be patched temporarily before the official release is welcome too @tannerlinsley @sw-yx 

Latest API: https://next.material-ui.com/guides/server-rendering/
Oudated Guide: https://github.com/nozzle/react-static/blob/master/docs/guides/material-ui.md

**Comment by jared1000** [comment]
https://github.com/nozzle/react-static/issues/1082 < same issue

**Comment by jared1000** [comment]
@sw-yx @tannerlinsley how to fix this? https://next.material-ui.com/guides/migration-v3/#styles pretty much says the plugin is broken now and as much as i tried, i couldnt fix it. Are you not going to look into it until MUI v4 releases? (It's going to be released soon)

**Comment by sw-yx** [comment]
i cant speak for tanner but i dont use MUI right now. this is an early stage oss project, we all have to chip in to maintain and update things we care about. i encourage you to dive in yourself to fix the plugin, if not we will have to wait til someone else does.

**Comment by jared1000** [comment]
Of course, I don't expect anything from anyone and I take nothing for granted. I tried to solve it myself, but was unable to. Seems to me 
```js
import React from 'react'
import { ServerStyleSheet, StyleSheetManager } from 'styled-components'
import { ServerStyleSheets } from '@material-ui/styles'

export default () => ({
  beforeRenderToHtml: (element, { meta }) => {
    meta.styledComponentsSheet = new ServerStyleSheet()
    meta.muiSheet = new ServerStyleSheets()
    meta.muiSheet.collect(element)
    return <StyleSheetManager sheet={meta.styledComponentsSheet.sheet}>{element}</StyleSheetManager>
  },
  headElements: (elements, { meta }) => {
    elements = [
      ...elements,
      meta.styledComponentsSheet.getStyleElement(),
      <style
        id="jss-server-side"
        // @ts-ignore
        dangerouslySetInnerHTML={{ __html: meta.muiSheet.toString() }}
      />
    ]
    return elements
  }
})
```
should work, but it doesn't

**Comment by jared1000** [comment]
Im placing $75 bounty if someone gets this done in the next 3 days. If not, the bounty's cancelled as Ill be moving on

**Comment by Herohtar** [comment]
What's up with the imports from `styled-components`? That's not part of MUI.

**Comment by jared1000** [comment]
@Herohtar if you noticed im using `meta.styledComponentsSheet.sheet`, because latest SC alpha release changed `.instance` to `.sheet`, so that is a hotfix to SC, not related to MUI.

**Comment by Herohtar** [comment]
This is how it seems it should work from looking at their documentation:
## node.api.js
```
import React from 'react'
import { ServerStyleSheets, ThemeProvider } from '@material-ui/styles'

import theme from './src/theme'

export default () => ({
  beforeRenderToElement: (App, { meta }) => props => {
    meta.muiSheets = new ServerStyleSheets()

    return meta.muiSheets.collect(
      <ThemeProvider theme={theme}>
        <App {...props} />
      </ThemeProvider>
    )
  },
  headElements: (elements, { meta }) => [
    ...elements,
    meta.muiSheets.getStyleElement(),
  ],
})
```

Specifically:
- [`ServerStyleSheets.collect()`](https://next.material-ui.com/css-in-js/api/#sheets-collect-node-react-element) returns a React element that should be included in the rendering, so you need to return that and not just ignore it.
- You can simply use [`ServerStyleSheets.getStyleElement()`](https://next.material-ui.com/css-in-js/api/#sheets-getstyleelement-css-react-element) to add the style element instead of creating your own from `toString()`.
- You should include `ThemeProvider` if you want to be able to access the theme at all, but if you don't need that then I guess you can leave it out

This seems to mostly work on my site, but I noticed that the generated class names aren't being shortened -- they're still the full `.MuiGrid-align-content-xs-flex-start`, etc. Also, there are some components that aren't being styled correctly. I'm not sure if I'm doing something wrong somewhere or if there's an issue with MUI.

You can see the full code for my test repo here: https://github.com/Herohtar/thalion-herohtar/tree/mui-v4

**Comment by jared1000** [comment]
@Herohtar Yes! You are right, muiSheets.collect needs to be returned. Your other concerns are also legitimate that not everything gets styled and class names arent being shortened, but you've still saved me a lot of potentially wasted time, so link me your twitter and we can talk about your bounty!

**Comment by jared1000** [comment]
By the way Styled Components v5 also suggests to use `collect` instead of wrapping in the Provider. Let's discuss implementing the plugins for the new versions here. People are going to open issues for them when they release anyway, so better if we prepare for it https://www.styled-components.com/docs/advanced#example

**Comment by Herohtar** [comment]
I've updated the example in my post with `beforeRenderToHtml` since that was what you were using. It seems to behave the same either way.

I figured out the issues with styling on my site were because of the MUI v4 changes to `Typography` -- it now doesn't have a default color and just inherits its color if you don't give it one yourself.

Still not sure what the problem is with MUI not generating the production class names.

I never active on my Twitter account, but it's [@Herohtar](https://twitter.com/Herohtar).

**Comment by sw-yx** [comment]
wow, glad this is working out!

**Comment by Herohtar** [comment]
Confirmed bounty received, glad I could be of help!

The plugins and guides will definitely need updating for the new releases of those components.

**Comment by jared1000** [comment]
My problem is solved but Ill leave the issue opened as we still need to figure out a good way to integrate the new apis. As far as I know `collect` is much more preferred than wrapping with providers (which is what current plugins do)

**Comment by Herohtar** [comment]
The guides probably still need updating, so not stale.

**Comment by 6pm** [comment]
@Herohtar thank you for solution, everything works again.
But I think 'ThemeProvider' is redundant. Everything works without it. My final version:

```
import { ServerStyleSheets } from '@material-ui/styles';

export default () => ({
  beforeRenderToHtml: (App, { meta }) => {
    meta.muiSheets = new ServerStyleSheets();

    return meta.muiSheets.collect(App);
  },
  headElements: (elements, { meta }) => [
    ...elements,
    meta.muiSheets.getStyleElement(),
  ],
});
```

Any objections?

**Comment by Herohtar** [comment]
@6pm That *might* work -- I'm not sure if it will cause any issues, but I believe it is okay as long as you are only making a very basic site that just uses the default theme. You also won't be able to access the theme values to use in custom components. However, if you want to do either of those things you will definitely need the `ThemeProvider`. I would recommend leaving it there for completeness.

**Comment by captainkovalsky** [comment]
I tried to use this `node.api.js` config 

```
import React from 'react'
import { ServerStyleSheets, ThemeProvider } from '@material-ui/styles'
const theme = require('./src/theme-build');

export default _ => {
  return {
    beforeRenderToHtml: (App, { meta }) => {
      meta.muiSheets = new ServerStyleSheets()

      return meta.muiSheets.collect(
        <ThemeProvider theme={theme}>
          {App}
        </ThemeProvider>
      )
    },
    headElements: (elements, { meta }) => [
      ...elements,
      meta.muiSheets.getStyleElement()
    ]
  }
}
``` and got this errors

```
 Error: Material-UI: the `styles` argument provided is invalid.
  You are providing a function without a theme in the context.
  One of the parent elements needs to use a ThemeProvider.

  Error: Material-UI: the `styles` argument provided is invalid.
  You are providing a function without a theme in the context.
  One of the parent elements needs to use a ThemeProvider.

  Error: Material-UI: the `styles` argument provided is invalid.
  You are providing a function without a theme in the context.
  One of the parent elements needs to use a ThemeProvider.
```

**Comment by SleeplessByte** [comment]
I don't know why that happens, unfortunately.

**Comment by captainkovalsky** [comment]
I suppose that injecting styles in this manner should prevent flickering view during first load, but it doesn't.
I even flip the order
```
    headElements: (elements, { meta }) => {
        return [
            meta.muiSheets.getStyleElement(),
            ...elements,
        ];
    },
})
```

**Comment by SleeplessByte** [comment]
We currently don't have the bandwidth to support MUI. Happy to take PRs.

**Comment by bluprince13** [comment]
@captainkovalsky did you ever figure out the answer to this?

> I noticed that processing stylesheets inside beforeRenderToHtml method just returns the MUI theme css, not custom styles used with makeStyles. Does any one know how to get all css not only for basic material UI ?

**Comment by cooperka** [comment]
Hi from late 2020 -- a few links have broken above, namely here's the PR for @Herohtar's working JSS plugin [node.api.js](https://github.com/Herohtar/thalion-herohtar/pull/5/files#diff-51ff3d87338f5547eaac6f5019bbdbbef84262f006d1eb19163bf2c5124d0f09) (original comment is https://github.com/react-static/react-static/issues/1179#issuecomment-491552921)

I'll officially submit a PR to fix the React Static documentation once I can get it fully working together; that PR helped a lot but I'm still encountering little issues with serving in production. Cheers.

**Comment by SleeplessByte** [comment]
Thanks Kevin! Shout if you need anything in particular.
