### ISSUE TITLE
[Bug] Local browser.api.js is not transformed by Babel

### ISSUE THREAD

**Issue by nddery** [react-static/react-static#1187]
Local `browser.api.js` is not correctly (?) transformed by Babel, specifically, JSX is not transpiled and running `yarn stage` (or `build` I'd assume) fails.

The error received is a `SyntaxError`:

```
ERROR in /my-static-site/browser.api.js
Module build failed (from/my-static-site/node_modules/babel-loader/lib/index.js):
SyntaxError: /my-static-site/browser.api.js: Unexpected token (5:11)

  3 | export default () => ({
  4 |   Root: PreviousRoot => ({ children, ...rest }) => {
> 5 |     return <div {...rest}>{children}</div>
    |            ^
  6 |   }
  7 | })
```

Running `browser.api.js` through Babel first solves the issue. Ideally this would be handled by React Static, as is done so for `node.api.js`.

### Environment
```
❯ npx envinfo --system --npmPackages 'react*' --binaries --npmGlobalPackages 'react*' --browsers
npx: installed 1 in 1.942s

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 906.13 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.14.0 - ~/n/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 64.0
    Safari: 12.1
  npmPackages:
    react: ^16.8.2 => 16.8.6
    react-dom: ^16.8.2 => 16.8.6
    react-static: ^7.0.0 => 7.0.5
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.
```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  `$ react-static create # choose the "basic" template` 
2.  `$ cd my-static-site`
3.  Add a `browser.api.js` file to your project root with the following content:
```js
import React from 'react'

export default () => ({
  Root: PreviousRoot => ({ children, ...rest }) => {
    return <div {...rest}>{children}</div>
  }
})
```
4. `$ yarn stage`

### Expected Behavior
I'd expect local `browser.api.js` to be correctly transformed, much like a local `node.api.js` is.

The [documentation](https://github.com/nozzle/react-static/tree/master/docs/plugins#plugins-must-be-compiled-if-installed-via-node_modules) says only the local plugins directory will be transformed, but I'd expect consistent behavior for both `node.api.js` and `browser.api.js`.

**Comment by david476** [comment]
This affected me too, its not stale.
