### ISSUE TITLE
Need help in Incremental Build

### ISSUE THREAD

**Issue by vivekspraxa** [react-static/react-static#1214]
I need a help. How can I detect which route i have to rebuild when Incremental flag is true. As in My app i have more then 10 routes.

**Comment by vivekspraxa** [comment]
Hi @tannerlinsley can you please help

**Comment by sw-yx** [comment]
he's been pretty busy. does this article help you in any way? https://www.netlify.com/blog/2019/01/17/how-to-scale-massive-react-static-sites-with-incremental-builds/#finally-the-goods sorry i'm not an incremental builds expert

**Comment by SleeplessByte** [comment]
Please use the blog post, docs and https://spectrum.chat/react-static
