### ISSUE TITLE
IE11 - Suspense broken

### ISSUE THREAD

**Issue by simonunlikely** [react-static/react-static#1217]
Hi,

I'm having trouble making my app work correctly on IE11.

On initial load the page displays correctly but on route change, it seems that Suspense never resolves and keeps my page with a `display: none` style, even though the page is correctly loaded (it exists in the DOM).

I have `babel-polyfill` as my entry point in my webpack config. Tried a bunch of other polyfills (via `core-js`) and still no luck...

No errors are logged in the console in IE so I'm kinda clueless here...

Anybody experiencing the same issue?

Thanks!

**Comment by SleeplessByte** [comment]
Given https://github.com/facebook/react/issues/14583 and https://github.com/facebook/react/issues/14570, I think this is an upstream issue. They have been closed and solved using _specific_ polyfills there.
