### ISSUE TITLE
Additional "/" added before url path

### ISSUE THREAD

**Issue by Tonkoy** [react-static/react-static#1225]
OS: Win 32: 
I installed react static and changed location to: './src/pages/'.
Also added cross-env in"build": "cross-env react-static build" row. 
No matter when I try to build I have this error for every Page.
I sow that in artifacts/static-app I have this kind of root id: "../src/pages/blog.js", so it seems like somewhere "/" has been added.
Please advice!

Error: Failed exporting HTML for URL blog (../src/pages/blog.js): Cannot convert undefined or null to object for every startup page.

**Comment by SleeplessByte** [comment]
Please provide a reproducible example with clear steps.
