### ISSUE TITLE
Preact with V7 ?

### ISSUE THREAD

**Issue by simonunlikely** [react-static/react-static#1234]
Hey guys, 

What's the status on using preact with react-static v7 ?
From my understanding preact doesn't support Suspense yet which basically makes it unusable with the latest version of react-static. Am I wrong ?

Thanks !

**Comment by SleeplessByte** [comment]
https://github.com/preactjs/preact/issues/1756

Suspense is in Preact X (just not SSR suspense) which matches the necessary capability of react-static V7. Let me know if you run into any bugs.
