### ISSUE TITLE
Outdated dependencies?

### ISSUE THREAD

**Issue by zehawki** [react-static/react-static#1237]
Warnings about critical bugs fixed in dependencies as follows:

```
yarn global add react-static
yarn global v1.7.0
[1/4] Resolving packages...
warning react-static > @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning react-static > chokidar > braces > snapdragon > base > mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
warning react-static > chokidar > braces > snapdragon > base > cache-base > set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning react-static > chokidar > braces > snapdragon > base > cache-base > union-value > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

```

**Comment by SleeplessByte** [comment]
> warning react-static > @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

Upstream issue: https://github.com/reach/router/issues/272

> warning react-static > chokidar > braces > snapdragon > base > mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
> warning react-static > chokidar > braces > snapdragon > base > cache-base > set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
> warning react-static > chokidar > braces > snapdragon > base > cache-base > union-value > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

These have been fixed upstream, which now lives at `3.0.x`. Dependency _should_ be updated.
