### ISSUE TITLE
[Bug] RUC not resolved when SSR

### ISSUE THREAD

**Issue by digitalkaoz** [react-static/react-static#1238]
### BUG Description

Lazy-Loading-Components seem to fail when dumping the site as static files.
The code-splitting and stuff works, but the components are not resolved during `react-static build` and no HTML is included in the static dumped file.

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 128.24 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome Canary: 77.0.3832.0
    Firefox: 65.0.1
    Safari: 12.1.1
  npmPackages:
    react: ^16.8.6 => 16.8.6
    react-dom: ^16.8.6 => 16.8.6
    react-static: ^7.1 => 7.1.0
    react-static-plugin-sass: ^7.1 => 7.1.0
    react-static-plugin-typescript: ^7.0 => 7.0.10
    react-universal-component: ^4 => 4.0.0
```

### Steps to Reproduce the problem

1. checkout https://github.com/digitalkaoz/react-static-ruc-ssr
2.  `react-static build`

### Expected Behavior

In https://github.com/digitalkaoz/react-static-ruc-ssr/blob/master/src/pages/blog.js we introduced 2 lazy loaded components with https://github.com/faceyspacey/react-universal-component. Those should be resolved during SSR.
After building the static dump investigate the compiled HTML:

In the file `dist/blog/index.html` there should be the resolved lazy loaded components, but its not:

search for `<span>Loading Bottomlink</span>` or `<span>Loading Toplink</span>` those should not be present, instead i expect the resolved components (like in `react-static@6`)

### Reproducible Demo

https://github.com/digitalkaoz/react-static-ruc-ssr

@tannerlinsley what changed here? In v6 it worked like a charm, in v7 its broken! So SSR with dynamic imports is broken now. Im relying on the v6 behavior todo some further optimizations like `purgecss` or `critical`

Since Suspense is broken too (for SSR) whats the correct way todo it now? Code-Splitting works fine, but rendering not!

**Comment by digitalkaoz** [comment]
@tannerlinsley @ScriptedAlchemy anyone have an idea?

**Comment by sw-yx** [comment]
hi everyone! thanks for your issue! there is now a call for maintainers of React Static, please weigh in here: https://github.com/nozzle/react-static/issues/1259

**Comment by ScriptedAlchemy** [comment]
I'll check this out, see if i can spot anything.
