### ISSUE TITLE
[Feature] Override siteRoot in sitemap plugin

### ISSUE THREAD

**Issue by ghost** [react-static/react-static#1245]
Hey guys,

So I have this use case : my website is hosted on a url which is : https://production-site.com
but the real public domain is https://site.com. So basically my `siteRoot` must be set to `/` if I want the site to be working from both urls.

But with this configuration, I cannot generate a sitemap automatically as `siteRoot` must be declared in order to work.

Is there a way to manually set the host for sitemap generation? Which may be different from the siteRoot config instead of automatically read from `static.config`?

**Comment by Pixelatex** [comment]
your siteroot should be https://site.com.

Because your domain https://site.com should map to https://production-site.com anyway.

**Comment by simonunlikely** [comment]
Yes you're right, but I still want the site to be accessible from https://production-site.com (for troubleshooting purposes mostly). If I set siteRoot to be https://site.com, then when loading https://production-site.com assets will be fetched from the other url. Does that make sense?

**Comment by sw-yx** [comment]
hi everyone! thanks for your issue! there is now a call for maintainers of React Static, please weigh in here: https://github.com/nozzle/react-static/issues/1259

**Comment by SleeplessByte** [comment]
Is this not solvable by `build`ing twice? Once with the `site.com` domain and once with the `production-site.com` domain?

**Comment by simonunlikely** [comment]
No, because `site.com` is an alias pointing to `production-site.com`, the only server is behind `production-site.com` so only one build is used here

**Comment by SleeplessByte** [comment]
Got it.

Since react-static has quite a few hooks that prevent this from working (absolute path redirects, canonical urls, sitemap plugin), and given that unless you have a canonical url specified pointing to one of the two domains, google would penalise you, the best way at THIS moment would be to add something like a Serverless Function that rewrites the request. 

- If coming from `production-site.com`, leave everything be
- If coming from `site.com`, rewrite `production-site.com` to `site.com`

**Comment by krzysztof-pyrzyk-ah** [comment]
@simonunlikely I think we have the same setup in our project.
For now we've set `siteRoot` to `https://site.com`. It works well.

The only downside is that when browsing the page from `https://production-site.com` it looks for routeInfo and other JS files on `https://site.com`. This request are being blocked by CORS policies.

I was thinking about separating the `siteRoot` config from sitemap plugin 🤔
Maybe something like `sitemapRoot` which could be equal to `siteRoot` to ensure backward compatibility.

**Comment by SleeplessByte** [comment]
Having disparate configuration and adding a new xxxRoot for each plugin is not my preferred way forward, but if you can come up with something that works well, PR it :heart:
