### ISSUE TITLE
Feature: AMP plugin

### ISSUE THREAD

**Issue by itchingpixels** [react-static/react-static#1247]
We'd love to have an AMP output plugin that works out-of-the-box.

Is our usecase unique? Or would other also find this useful?

**Comment by sw-yx** [comment]
hi everyone! thanks for your issue! there is now a call for maintainers of React Static, please weigh in here: https://github.com/nozzle/react-static/issues/1259

**Comment by simonunlikely** [comment]
I'm seconding this, would be nice to have! I'm working on a project that will need AMP pages in the future so use case exists, at least for me :)

**Comment by PolMrt** [comment]
Would be so nice ! Any news about this ?

**Comment by SleeplessByte** [comment]
We take PRs! None of our clients require or want AMP, so there is no incentive to build this right now.
