### ISSUE TITLE
TypeError: Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by rolexta** [react-static/react-static#1260]
when run react-static ...

**Comment by M1chaelTran** [comment]
yup got the same error when i ran `react-static --help`
![image](https://user-images.githubusercontent.com/30276/61126651-624f9600-a4f0-11e9-94de-657de1571bcc.png)

**Comment by julientaq** [comment]
got the same issue today. Is that a blocker to start working with react-static?

**Comment by bvillagran** [comment]
I got this issue as well, Fedora 30 and Node 10.16.0 installed from package manager. Other than the error message I haven't noticed any other issues with React Static, it's still usable.

**Comment by Manc** [comment]
Same with Node version 10.16.3.

**Comment by RJ-1998** [comment]
I found the same problem. I've temporarily done this to avoid this useless error.
**Comment the following lines in the react-static file**
```js
init().catch(e => {
  console.trace(e)
  process.exit(1)
})
```
**and do this instead**
`init();`
