### ISSUE TITLE
IE11 Object.entries error (react-hot-loader)

### ISSUE THREAD

**Issue by emuraton** [react-static/react-static#1267]
Hello,

`react-hot-loader` fixed an IE11 error in v`4.12.8` (https://github.com/gaearon/react-hot-loader/issues/1303#issuecomment-512666939)
It seems we are currently using the different version (depending of the package), but all of them are older than 4.12.8.

Do you mind if I open a PR to bump the version?

**Comment by SleeplessByte** [comment]
You can always open that PR :)

**Comment by emuraton** [comment]
Pushed a PR, let me know your thoughts
