### ISSUE TITLE
[BUG] HMR not working with latest react-static version

### ISSUE THREAD

**Issue by ghost** [react-static/react-static#1268]
Hey guys,

Since I upgraded to `^7.0.0` hmr has stopped working in my app (js and most importantly css).

At first I thought it was coming from my custom webpack config (I started my project on v6, and had to create a custom config to have sass + css modules working nicely together), but I just installed globally the latest react-static version and created a blank starter, hmr does not work out of the box, even for .css files.

So I guess I'm not the only one in this situation? All issues related to hmr not working seem to be resolved for everybody so I wonder if I'm missing something here?

Thanks!

**Comment by david476** [comment]
It does work for me for some changes, but I do frequently have to refresh.

**Comment by SleeplessByte** [comment]
It's really the integration of whichever css package you use _with_ HMR and not react-static. #1267' PR should bring some fixes here to, because the hot loader currently packaged is slightly outdated!

**Comment by simonunlikely** [comment]
Thanks for chiming in guys!

I wonder why my blank starters also had hmr failing out of the box with no additional config ? Or maybe it is just on my end ?
