### ISSUE TITLE
[Bug] project can run but failed to build

### ISSUE THREAD

**Issue by naivefun** [react-static/react-static#1270]
The attached project runs fine with `yarn start` but failed with `yarn build`.

The error shows
```
Failed exporting HTML for URL ProductDocPostPage (../src/pages/ProductDocPostPage.tsx): Cannot read property 'title' of undefined
```

But the object is not undefined and the console.log clearly shows that.

[pdc-docs copy.zip](https://github.com/react-static/react-static/files/3429847/pdc-docs.copy.zip)
Try url with http://localhost:3000/products/pdc/get-started/introduction

**Comment by simonunlikely** [comment]
Hey,

It's not the object that is undefined here but the property you're trying to access.
If it works in local try adding some checks for undefined in your code so that it doesn't break if  it is undefined and try building again.

**Comment by vicodinvic1** [comment]
Same issue. Please somebody help with this problem.
