### ISSUE TITLE
How do you localize a menu?

### ISSUE THREAD

**Issue by ghost** [react-static/react-static#1277]
Hey guys,

I'm having a little trouble translating my site, especially the menu part (which is the same on every route).

For a while I had only one locale, so I put my menu data in the siteData object and it was spread across all my pages. All good.

But now that I need to have multiple locales, I can't use siteData anymore because it is only build once per site. Or it means I should have all my menus inside of it which seems wrong (I'll have about 10 locales, and the menu structure is heavy).

So new approach, I moved everything into sharedData so it is only loaded once per session. I create a shared object for each locale that I share across pages of that locale. It works well, but problem is that this data is only available in routes. And my header is outside of routes because I only want to include it once (useRouteData returns null when used outside of a react-static Routes component right?)

I don't want to move my header in every page because it blinks on page change while the next page is loading (due to how Suspense works, removing everything and displaying the fallback instead).

So for now I update a global store on page change with the necessary data, and read it from the header which is some levels above in the hierarchy but it leads to bugs : when static rendering occurs, sometimes my store did not have the time to update and data in the exported html is wrong.

Do you have any ideas what could be the best approach for my needs? Or maybe how I could delay the static rendering until my header has rendered with the necessary data?

Thanks!

**Comment by francoisgeorgy** [comment]
Hi,
I have exactly the same problem.
Did you find an elegant solution?
Best Regards
