### ISSUE TITLE
Localized 404

### ISSUE THREAD

**Issue by ghost** [react-static/react-static#1289]
Hi ! 

I have multiple locales on my website, and they each have a different menu. Problem is the 404 component cannot be localized as we can only have one in a config. So only solution I see would be to build a big object containing all translations for the 404 page and feed it to the template, instead of feeding only the proper localized data, and then read the locale in the url and decide what to display. But it is non optimized and cumbersome...

Is there a way to have multiple 404s ?

Cheers,

Simon

**Comment by nddery** [comment]
I think it's possible to nest 404's in the routes (and maybe in the directory tree too ?). I would need to verify but I think something like the following would work:

```js
// static.config.js
export default {
  routes: () => {
    return ['fr-CA', 'en-US'].map(locale => ({
      path: `/${locale === 'fr-CA' ? '' : locale}`,
      template: 'Homepage'
      children: [
        {
          path: '404',
          template: 'NotFound'
        }
      ]
    })
  }
}
```

Which would give you the following routes:

- /
- /en-US
- /404
- /en-US/404
