### ISSUE TITLE
Build never stops

### ISSUE THREAD

**Issue by KarishmaBothara** [react-static/react-static#1291]
Hi,

My project uses react-static. I am able to build the project, dist is created succesfully. However the build is never completed. 
These are the last things printed

> Your app is now exported! Here's what we suggest doing next:
> 
> - Upload your 'dist' directory to your favorite static host! We recommend using Netlify:
>   - [32mnpx netlify-cli deploy[39m
> - Analyze your app's webpack bundles
>   - [32mreact-static bundle --analyze[39m
> 

Please help.

Thanks and regards,
Karishma

**Comment by nikneroz** [comment]
@KarishmaBothara How did you fixed it?
