### ISSUE TITLE
[Bug] env: node\r: No such file or directory on MacOS

### ISSUE THREAD

**Issue by chowanij** [react-static/react-static#1294]
### Reporting a bug?
React static version 7.1.0 and 7.2.0
When react-static start command has been launched error:
```
env: node\r: No such file or directory
error Command failed with exit code 127.
```
occured.

### Environment

```
 System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 855.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.8.0/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 66.0.3
    Safari: 12.0

```

of course include any other package versions here if relevant. 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  update react-static to version 7.1.0 or 7.2.0
2. run command react-static start 

### Expected Behavior
react-static command should successfully run project on MacOs

**Comment by krzysztof-pyrzyk-ah** [comment]
A quick workaround for local development is to manually change line endings in `/node_modules/.bin/react-static` from `CRLF` to `LF`

**Comment by nddery** [comment]
When checking the line ending from an npm installed `react-static` bin file, I get CRLF:

```
$ yarn add react-static
$ file ./node_modules/.bin/react-static
[...] node script text executable, ASCII text, with CRLF line terminators
```

However, when checking the executable from the repo, there is no mention of CRLF:

```
$ cd /path/to/my/locale/react-static
$ file packages/react-static/bin/react-static
[...] node script text executable, ASCII text
```

Would a simple republish (under new version) fix this ? Unsure what @SleeplessByte steps were to publish this ?

**Comment by SleeplessByte** [comment]
Publishing for me is just running `lerna publish`, but I did it from a windows machine, so that might be the issue. 

This, however, sounds to me like a badly configured _git_ client.

**Comment by SleeplessByte** [comment]
Copying https://github.com/lerna/lerna/commit/02f70f45a5f54c8782f5ca95370ea4a8b9a1e09f could work. I'm not a fan of this but whatever makes this work...

**Comment by SleeplessByte** [comment]
I have applied the commit to the repository. I'll try to publish tomorrow (7.2.1)

**Comment by chowanij** [comment]
@SleeplessByte Thanks for addressing that so quickly 👏

**Comment by SleeplessByte** [comment]
Can you try 7.2.2 and see if that solves it? If not I will do a single release from a MacOS machine.

**Comment by krzysztof-pyrzyk-ah** [comment]
I've just tried 7.2.2.
All works fine 🎉 

Thanks!
