### ISSUE TITLE
[Bug] Unable to run react-static v7.2.0 after upgrading from v7.1.0

### ISSUE THREAD

**Issue by benedfit** [react-static/react-static#1295]
### Reporting a bug?

  Provide as much information as you can to reproduce the issue.
  **If the issue is not reproducible, it can't be fixed!**

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.39 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    Yarn: 1.12.3 - ~/.nvm/versions/node/v10.14.1/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-dom: ^16.9.0 => 16.9.0 
    react-hot-loader: ^4.12.11 => 4.12.12
    react-static: ^7.2.0 => 7.2.0 
    react-static-plugin-reach-router: ^7.2.0 => 7.2.0 
    react-static-plugin-sitemap: ^7.2.0 => 7.2.0 
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.0 

```

### Steps to Reproduce the problem

**Experienced when upgrading from v7.1.0 to v7.2.0**

1.  with v7.1.0 `react-static start` ran successfully
2.  `yarn upgrade` to v7.2.0
3.  run `react-static start` now results in 
```
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
4. Open `/node_modules/react-static/bin/react-static` and re-save file, thus changing line endings from Windows (CRLF) to Unix (LF)
5. Re-run `react-static start`, runs successfully

### Expected Behavior

v7.2.0 should work as expected irrespective of OS being used.

### Reproducible Demo

Repo: https://github.com/newhighsco/destiny-clan-warfare/tree/beta
Results: https://app.netlify.com/sites/destiny-clan-warfare/deploys/5d6e45b5bcba1d000852f2d3

**Comment by krzysztof-pyrzyk-ah** [comment]
Same issue described here: https://github.com/react-static/react-static/issues/1294

**Comment by benedfit** [comment]
Sorry, I must have just missed that one being logged. Closing duplicate
