### ISSUE TITLE
basePath is not used to load templates js and css

### ISSUE THREAD

**Issue by pmogollons** [react-static/react-static#1297]
When using basePath to load the site not on the root of your domain you get the following error on the body of the page.

**An error occurred loading this page's template. More information is available in the console.**

And on the console you get this error.

```
Error: Loading chunk 4 failed.
(error: https://www.indesigncolombia.com/templates/src/pages/index.ada690a6.js)
    at HTMLScriptElement.a (main.5bd064cb.js:1)
```

The issue is because the basePath is not used to load the templates and the css files, is trying to load them from the root of the domain /.

### Environment
```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 687.49 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    react: ^16.8.2 => 16.8.6 
    react-dom: ^16.8.2 => 16.8.6 
    react-static: ^7.0.0 => 7.0.5 
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0 
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0 
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-static: 7.0.10
```

### Steps to Reproduce the problem
1.  Add siteRoot
2.  Add basePath
3.  deploy
4. Check the console and the body of the site. [Example](https://www.indesigncolombia.com/demo/base/)

### Expected Behavior
When setting basePath value the page should load js, css and other assets from the basePath not from the root.

### Reproducible Demo
https://github.com/pmogollons/basepath-issue
https://www.indesigncolombia.com/demo/base/

**Comment by nddery** [comment]
Seems like you're on `react-static@7.0.5`. Version `7.2.0` includes fixes for `basePath` - mind trying that ? I see you're on OSX, so you might run into https://github.com/react-static/react-static/issues/1294.

Your example repo is using the `staging` configurations, so I imagine you are deploying with the `--staging` flag (these configuration will otherwise not take effect).

Seems like you removed the `routes` property from `static.config.js` - because of this you'll run into an issue trying to export `pages/blog.js`:

> Failed exporting HTML for URL blog (/basepath-issue/src/pages/blog.js): Cannot read property 'map' of undefined

**Comment by pmogollons** [comment]
@nddery Thanks for your reply. I tried that on 7.1.0 and 7.2.0 but 7.2.0 is not working for me currently having the #1294 issue.

You are right, the repro uses staging but, it also happens on siteRoot + basePath. I just updated the repo and the deployment of the reproduction.

Actually, the basePath is used for almost everything, but not for the paths of the templates and for the css. A workaround to this was deploying templates and css to the root folder.

I didn't got that issue with the blog route. I'll check it out. Thanks.

**Comment by nddery** [comment]
From my experience, only `7.2.0` will work - as `7.1.0` is also broken (suffering the symptoms you've outlined here). There are [many ways to convert line ending](https://superuser.com/questions/52044/convert-crlfs-to-line-feeds-on-linux) - until a fix is released on npm (hopefully soon) manually fixing the file is the only way to use `7.2.0` afaik.

**Comment by pmogollons** [comment]
I tried it but it didn't work. It stops failing but it running yarn start or react-static start it doesn't do anything. Maybe I did it wrong. I'll try tomorrow again.

Thanks.

**Comment by pmogollons** [comment]
@nddery I got v7.2.0 working and it does fix the issue. I'm closing it as it is already solved. Thanks again.
