### ISSUE TITLE
[Docs] How to import local images from JSON

### ISSUE THREAD

**Issue by Kadrian** [react-static/react-static#1301]
Hey, I'm trying to use a simple `items.js` file:
```
import url from './img.png';

export default {
  title: "Hello"
  imgUrl: url
}
```

Then I'm importing that in `static.config.js`
```
import data from './src/items.js';
  ...
  ...
    return [
      {
        path: "/",
        getData: () => ({
          items
        })
     }}
...
```

`imgUrl` happens to be `{}`. What's the issue here? Am I missing a DOCS guide on how to use local images?

**Comment by Pixelatex** [comment]
Just import your img.png file straight into the file you want to use it? Why are you trying to pass it via routedata?

**Comment by Kadrian** [comment]
Because it's not about a single image, but about a lot of `Item` entities that each contain a bunch of images. All of that data is currently on my local file system. 

I'm just trying to keep the data (images, texts, other media) separate from the containers / components that render that type of entity.

Shouldn't it be possible to supply a route with any kind of media / text / json?
