### ISSUE TITLE
Make dev-server a link so you can click to open in terminal.

### ISSUE THREAD

**Issue by mattwaler** [react-static/react-static#1302]
**Is your feature request related to a problem? Please describe.**

When starting up the server, you have to manually open a browser and type localhost:3000 to get to the server. If the terminal printed `http://localhost:3000` people could command/control + click on it to immediately open it in their preferred browser.

**Describe the solution you'd like**

Change the `App serving at localhost:3000` to `App serving at http://localhost:3000`

**Describe alternatives you've considered**

Really anything to make it clickable.

**Additional context**

![not-clickable](https://user-images.githubusercontent.com/32300026/64430752-ed7b8100-d086-11e9-864f-6934c7a7e2fd.png)

**Comment by SleeplessByte** [comment]
Yes, this fix is already applied for RS 8, but I will accept a PR to have this now!

**Comment by krzysztof-pyrzyk-ah** [comment]
This got fixed in PR mentioned above ☝️
