### ISSUE TITLE
[Bug] Absolute paths leaking in the bundle

### ISSUE THREAD

**Issue by nddery** [react-static/react-static#1303]
### Reporting a bug?

Absolute paths are found in the exported bundles. This is surprising, can leak information about your build system, and will cause [webpack longterm caching](https://webpack.js.org/guides/caching/) to not work if you build your site in different directories over time (or on multiple servers).

I believe the caching is two fold, part of it would be to use [`contenthash`](https://github.com/react-static/react-static/pull/1232) and second would be to use relative path for referencing modules.

I know there's been a lot of work put into using absolute paths over relative paths lately, and I wonder if we could achieve the same result with relative paths instead (unclear what the issue was) ?

### Environment

<details>
<summary>envinfo result</summary>

```
❯ npx envinfo --system --npmPackages 'react*' --binaries --npmGlobalPackages 'react*' --browsers
npx: installed 1 in 1.434s

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 6.09 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.14.0 - ~/n/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
    Safari: 12.1.1
  npmPackages:
    react: ^16.9.0 => 16.9.0
    react-dom: ^16.9.0 => 16.9.0
    react-static: ^7.2.0 => 7.2.2
    react-static-plugin-reach-router: ^7.2.0 => 7.2.2
    react-static-plugin-sitemap: ^7.2.0 => 7.2.2
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.2
```
</details>

### Steps to Reproduce the problem

1. Install a "basic" react-static site
```
❯ react-static create

? What should we name this project? my-static-site
? Select a template below... basic
Creating new react-static project...
```

2. `cd my-static-site`
3. `yarn build`
4. Look in the `dist/main.*.js` file and find absolute paths. If you're on Mac, this mean you'd find `/Users/[your-user]/...` paths in there.

Another way to see these absolute path is to run `yarn serve` and look at the `sources` tab in the devtools. You should see absolute path there: 
![Screen Shot 2019-09-06 at 9 25 55 AM](https://user-images.githubusercontent.com/610207/64431461-7c3ccd80-d088-11e9-9f52-8138ccda84f7.png)
 
### Expected Behavior

I would expect not to find absolute paths in the bundles.

**Comment by felipearosemena** [comment]
+1 on this. I'm seeing the exact same issue

**Comment by 6pm** [comment]
I think it's good for first time issue.

**Comment by felipearosemena** [comment]
ah! figured it out:

```
export default {
  siteRoot: "/",
  plugins: [
    ...
  ],
}
```

**Comment by SleeplessByte** [comment]
> I believe the caching is two fold, part of it would be to use contenthash and second would be to use relative path for referencing modules.

If we use `contenthash` (this is something I saw mentioned before) the other part also becomes much easier.

I definitely want that, as currently the hashes are not stable :heart:

**Comment by nddery** [comment]
@SleeplessByte do you know if there's a way (or if it would be wanted) to keep paths absolute inside react-static but have them become relative inside the generated bundles ? Or what do you think we should do there - absolute paths are part of the non-deterministic hashes for us as our build directory changes over time.

**Comment by SleeplessByte** [comment]
I don't know what the _right_ solution is. The problem is that we're having many active consumers with different set-ups, and we want to try to support all of them for as long as possible.

Let's find out what Gatsby does and see if we can use that behaviour!

A "quick workaround" would _literally_ be grep/replace/s the absolute prefixes after the bundles are generated.

**Comment by smartboyathome** [comment]
I ran into this issue yesterday. As @SleeplessByte said, a solution for me may not work for someone else (process.cwd() may not, in fact, be the correct directory, hence the absolute paths). For my build system, though, it is, and the directory was what was varying between builds. Until a solution can be found, adding the following workaround to my node.api.js file fixes this enough that I only track the files that actually changed:

```
import path from 'path';
import replace from 'replace-in-file';
import jsStringEscape from 'js-string-escape';
import regexStringEscape from 'lodash.escaperegexp';

export default pluginOptions => ({
    afterBundle: async state => {
        await replace({
            files: path.resolve("./dist/templates/vendors~main.js"),
            from: new RegExp(regexStringEscape(jsStringEscape(path.resolve(process.cwd()))), "g"),
            to: "."
        });
        return state;
    },
});
```

**Comment by nddery** [comment]
My understanding is that react-static uses absolute path to support pointing the `tmpt`, `artifacts` and `dist` directory to a location that is outside of the repository (for example, support building on Lambda, outputting to the `/tmp` directory)). Seems like Gatsby does not support [changing the output directory](https://github.com/gatsbyjs/gatsby/issues/1878). [They've tried adding the option](https://github.com/gatsbyjs/gatsby/pull/4756) but [ended up reverting it](https://github.com/gatsbyjs/gatsby/commit/d521c19d04f8ba029f3998d104288eb92846d4ed) as it introduced some issues. Unclear to me exactly what the issue(s) were.

I'm going to test out using [module paths](https://webpack.js.org/concepts/module-resolution/#module-paths) (along with updating the "resolve.modules" Webpack setting) for import paths within generated bundles, while keeping absolute paths anywhere within react-static.

Once that is confirmed to work (if it does), I can revisit https://github.com/react-static/react-static/pull/1232 to see if it actually helps or not.

Hopefully this makes sense!

**Comment by SleeplessByte** [comment]
Yes, thanks for figuring that all out. Since we DO support pointing those directories outside of the root, we sorta _require_ absolute paths.

Let me know if any of it works out. @smartboyathome has a temporary workaround https://github.com/react-static/react-static/issues/1303#issuecomment-531270998 that may or may not work for those reading this.

**Comment by nddery** [comment]
👋 it's been difficult to find time to work on this issue lately but wanted to give a quick update. I've got a working [branch](https://github.com/react-static/react-static/compare/master...nddery:fix/no-absolute-paths) that allows me to change both `paths.dist` and `paths.temp` to point outside of the working directory. This works fine and no absolute paths end up in the generated files, ensuring consistent hashing even when the build directory changes.

However, I can't get `yarn build` to successfully run when also changing `paths.buildArtifacts` to a directory that's outside the working directory. I've got the same issue when using the upstream `react-static@7.2.2`.

```
Exporting HTML...
  Error: Trace: { Error: Cannot find module '@reach/router'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
      at Function.Module._load (internal/modules/cjs/loader.js:562:25)
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at Module.call [as require] (/react-static/packages/react-static/s  rc/utils/binHelper.js:62:26)
      at require (internal/modules/cjs/helpers.js:25:18)
      [...]
```

Unclear to me if this is a local setup issue with `yarn link` or if this would also manifest in a "real-world setup".

**Comment by SleeplessByte** [comment]
You're awesome.

Why don't I check out your branch next week and see if I can fix that.

**Comment by robertveloso** [comment]
I'm seeing this issue in react-static@7.2.3

**Comment by nddery** [comment]
@robertveloso the fix has not yet been released.

**Comment by robertveloso** [comment]
I downgrade to react-static@7.1.0 as suggested #1355, but my build still messy, the js and css files are not loaded.
they are like this: href="/templates/src/pages/index.tsx.7baaf7a6.js"/
instead of this: href="./templates/src/pages/index.tsx.7baaf7a6.js"/
Do you know why, @nddery?

**Comment by nddery** [comment]
I think these links are meant to be absolute to your site root.

Might I suggest you ask the question in the [Spectrum community chat](https://spectrum.chat/react-static?tab=posts), along with your config and maybe a small reproducible example ? This would reach a larger audience.

**Comment by warloque** [comment]
I've played around with node to remove the root paths from the `js`, `json` and `html` in `dist/` directory and it finally works. 

Beware hardcoded paths in my snippet – it works for my setup (Unix, MacOS and default /dist & /src paths). So, here is my plugin which runs after bundling and exporting during `build`: 

`import path from 'path';
import replace from 'replace-in-file';
import jsStringEscape from 'js-string-escape';
import regexStringEscape from 'lodash.escaperegexp';
import fsx from 'fs-extra';

const strCWD = regexStringEscape(jsStringEscape(path.resolve(process.cwd())));
const srcPathParent = './dist/templates';
const srcPath = `${srcPathParent}${strCWD}/src/pages`;
const dstPath = `${srcPathParent}/pages`;

export default pluginOptions => ({
    afterBundle: async state => {
        await replace({
            files: path.resolve(`${srcPathParent}/vendors~main*.js`),
            from: new RegExp(strCWD, 'g'),
            to: '.'
        });
        await replace({
            files: path.resolve('./dist/main*.js'),
            from: new RegExp(`${strCWD.slice(1)}/src/`, 'g'),
            to: ''
        });
        return state;
    },
    afterExport: async state => {
        await replace({
            files: path.resolve('./dist/**/*.html'),
            from: new RegExp(`${strCWD}/src/`, 'g'),
            to: '/'
        });
        await replace({
            files: path.resolve('./dist/**/routeInfo.json'),
            from: new RegExp(`${strCWD}/src/`, 'g'),
            to: '/'
        });
        try {
            await fsx.move(srcPath, dstPath);
        } catch (err) {
            console.error(err);
        }
        try {
            await fsx.remove(`${srcPathParent}/Users`);
        } catch (err) {
            console.error(err);
        }
        return state;
    },
});
`

**Comment by antoninlanglade** [comment]
@warloque It's perfect !! 👌🏻

**Comment by warloque** [comment]
> @warloque It's perfect !! 👌🏻

Thanks, but nothing is perfect, you know ;-) 
Check my code update, hope that will help better)

**Comment by antoninlanglade** [comment]
Thanks a lot for the update 👍🏻

@warloque If you want to be fully compatible you need to integrate the basePath value into all dist path in order to build into subfolers 🙂

`./dist/${basePath}/...`

**Comment by AubreyHewes** [comment]
I am on the side on this.. using CI/CD the abs path will be anonymous anyway (i.e. `/pipeline/src/...`)... It's only when pushing your _locally built_ version to a production server that your local home directory could be exposed..

Though I do think that if the [`paths`](https://github.com/react-static/react-static/blob/611aa824e15f19466911623705dc0676dbe9c388/docs/config.md#paths) have not been changed that the previous behaviour should be supported.. i.e. only if you change the default `paths` abs [`paths`](https://github.com/react-static/react-static/blob/611aa824e15f19466911623705dc0676dbe9c388/docs/config.md#paths) should be used.

Also I do not understand why this issue has been closed as it is still relevant in the current (at writing) npm version `7.2.3` ? (@SleeplessByte if you have any input, thanks!)

**Comment by SleeplessByte** [comment]
Hi there @AubreyHewes 

The issues reflect the state on `master`, not on `npm`.
