### ISSUE TITLE
[Docs] The flow chart image link is broken

### ISSUE THREAD

**Issue by geverghe** [react-static/react-static#1304]
Whats up with the docs?
The flow chart image on the readme is broken
![image](https://user-images.githubusercontent.com/16950956/64520485-e7e69b00-d313-11e9-9d62-6c7d5ed3c795.png)
![image](https://user-images.githubusercontent.com/16950956/64520509-f46af380-d313-11e9-858a-d7f37ee66467.png)

The branding logo is broken as well
![image](https://user-images.githubusercontent.com/16950956/64520545-05b40000-d314-11e9-9e52-2339317a04c8.png)

**Comment by SleeplessByte** [comment]
The images were corrupted in the [latest commit](https://github.com/react-static/react-static/commit/311cd1da08cfd7cab4ee2aa90136276d0d7a43c7) (as shown [here](https://github.com/react-static/react-static/blob/master/media/flow.png)).

Luckily we still have them in history. We are currently out of office so we'll accept a PR or this will need to wait a week.

**Comment by krzysztof-pyrzyk-ah** [comment]
@SleeplessByte I think this one can be closed :)

**Comment by SleeplessByte** [comment]
You're right! Thanks Krzysztof
