### ISSUE TITLE
Memory issue while building

### ISSUE THREAD

**Issue by m4yankp** [react-static/react-static#1308]
Hi,

I am facing the memory allocation issue while building my application on the server, I saw a few tickets regarding the same, tried to run with --max-old-space as well the problem is still there. The website has 5 different categories and approximately 350+ articles for now, and when I build the same I get following error:

[✓] App Bundled (27.9s)
Fetching Site Data...
[✓] Site Data Downloaded (0.3s)
Fetching Route Data...
[=========================================================================================================================] 327/327 100% 15571/s 0.0s
[✓] Route Data Downloaded (0.3s)
Exporting HTML across 2 threads...

<--- Last few GCs --->

[23905:0x3d57100]    72064 ms: Mark-sweep 1387.7 (1422.3) -> 1387.5 (1422.8) MB, 1179.0 / 0.0 ms  (average mu = 0.106, current mu = 0.004) allocation failure scavenge might not succeed
[23905:0x3d57100]    73208 ms: Mark-sweep 1388.3 (1422.8) -> 1388.2 (1423.3) MB, 1138.4 / 0.0 ms  (average mu = 0.058, current mu = 0.005) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x4e4fb85be1d]
    1: StubFrame [pc: 0x4e4fb85d1df]
Security context: 0x25648d49e6e9 <JSObject>
    2: scriptDataState [0x83450a67d71] [/frontend/node_modules/parse5/lib/tokenizer/index.js:~720] [pc=0x4e4fbcf7765](this=0x007558fa48b9 <JSObject>,cp=116)
    3: /* anonymous */ [0x1984086741e1] [/frontend/node_modules/parse5/lib/parser/index.js:~389] [pc=0x4e4fbcfcf77](thi...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8f9d10 node::Abort() [/usr/local/bin/node]
 2: 0x8f9d5c  [/usr/local/bin/node]
 3: 0xaffd0e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xafff44 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xef4152  [/usr/local/bin/node]
 6: 0xef4258 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 7: 0xf00332 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0xf00c64 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0xf038d1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0xeccd54 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
11: 0x116cede v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x4e4fb85be1d 

I appreciate your help in understanding the issue and how this can be fixed? 

### Environment
System:
    OS: Linux 4.4 Ubuntu 16.04.4 LTS (Xenial Xerus)
    CPU: (2) x64 Intel Core Processor (Haswell, no TSX, IBRS)
    Memory: 1.03 GB / 3.86 GB
    Container: Yes
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-dom: ^16.8.6 => 16.9.0 
    react-emotion: ^9.2.4 => 9.2.12 
    react-google-publisher-tag: ^2.0.6 => 2.0.6 
    react-google-tag-manager: ^2.2.1 => 2.2.1 
    react-gpt: ^2.0.1 => 2.0.1 
    react-hot-loader: ^4.3.12 => 4.12.11 
    react-loader-spinner: ^2.3.0 => 2.3.0 
    react-loading: ^2.0.3 => 2.0.3 
    react-oembed-container: ^0.3.0 => 0.3.0 
    react-redux: ^7.0.3 => 7.1.1 
    react-router-dom: ^5.0.0 => 5.0.1 
    react-slick: ^0.24.0 => 0.24.0 
    react-static: ^7.1.0 => 7.1.0 
    react-static-plugin-emotion: ^6.0.8 => 6.3.0 
    react-static-plugin-google-tag-manager: ^1.0.3 => 1.0.3 
    react-static-plugin-reach-router: ^7.0.0 => 7.0.10 
    react-static-plugin-sitemap: ^7.0.10 => 7.0.10 
    react-static-plugin-source-filesystem: ^7.0.0 => 7.1.0 
    react-static-plugin-styled-components: ^6.0.8 => 6.3.0 
    reactstrap: ^8.0.0 => 8.0.1 
  npmGlobalPackages:
    react-static: 7.1.0

Thanks
- Mayank

**Comment by m4yankp** [comment]
Any update from anyone?

**Comment by nddery** [comment]
Does lowering [`outputFileRate`](https://github.com/react-static/react-static/blob/master/docs/config.md#outputfilerate) fix this issue for you ? I've been facing this issue and setting it to 50 might be part of our "fix". I've also got `maxThreads` set to 1 but I think it is unrelated.

**Comment by m4yankp** [comment]
@nddery It worked! Thanks a lot!

**Comment by SleeplessByte** [comment]
Thanks @nddery!

**Comment by AJTJ** [comment]
This is still relevant. Thanks @nddery
