### ISSUE TITLE
Google Mobile Friendly Test Failed

### ISSUE THREAD

**Issue by m4yankp** [react-static/react-static#1309]
Hi,

I am facing issues with the new project I created using React-Static, the mobile-friendly test of the same is what I am failing, but when I try to open the website directly on phone or through simulators, it seems pretty responsive.

It would be great if you can help me figure out what I am doing wrong?

Thanks
- Mayank

**Comment by m4yankp** [comment]
Hi @Pixelatex,

Thanks for the response.

1) Yes testing it on production build.
2) 
As per google:
<img width="1423" alt="Screenshot 2019-09-11 at 2 48 07 PM" src="https://user-images.githubusercontent.com/45486463/64674335-324a5200-d4a3-11e9-806b-17fa5d760f92.png">

Actual website on mobile view:
<img width="498" alt="Screenshot 2019-09-11 at 2 48 51 PM" src="https://user-images.githubusercontent.com/45486463/64674377-4d1cc680-d4a3-11e9-85f7-282f69e6cef8.png">

The whole css is already in one file when I check through view source: <link rel="stylesheet" href="/styles.9203ac18.css">

I hope this helps you?

**Comment by Pixelatex** [comment]
... This is not related to RS at all. The test clearly state: 

"text too small to read" and "clickable elements too close together"

These are your specific code elements, not ours.

**Comment by m4yankp** [comment]
@Pixelatex If you look at the screenshot on right that google shares, the website looks broken, whereas the same website on mobile phones, etc seems to work fine, so wanted to know what's wrong there? If I put the same code in HTML and run it via google mobile-friendly test, it works fine.

**Comment by Pixelatex** [comment]
Googling it gives a lot of issues where people complain that the google mobile friendly site can't correctly handle external files like css/js... and won't load them, resulting in what you are seeing.

I'd recommend testing with lighthouse or someting else. That will give you just as much insights .+ if the site actually works on mobile devices on such it's clearly an issue with the gmf site.

**Comment by m4yankp** [comment]
@Pixelatex thanks a ton! This helps a lot :-)

**Comment by krzysztof-pyrzyk-ah** [comment]
@m4yankp You can also look a the "Page Loading issues".
When you click on "view details" there you'll see all the problems googlebot had while fetching your page.
Probably you've added a robots.txt file where you prevent googlebot from accessing some assets like css/js.
