### ISSUE TITLE
GPT Tags with React-GPT do not change on other pages and use parent page GPT

### ISSUE THREAD

**Issue by m4yankp** [react-static/react-static#1310]
Hi,

I Added GPT tags with react-gpt and when I use <Link> tag to call other pages, the GPT tags do not change and stay at the same position at it was on the previous page.

Can you help me identify what I am doing wrong here?

**Comment by Pixelatex** [comment]
This issue seems to be related to react-gpt, not react-static.

Also, without code we can't even begin to help you.

**Comment by SleeplessByte** [comment]
Yes this is an issue with react-gpt. Let us know if there is anything else we can help you with on the react-static side.
