### ISSUE TITLE
[Bug] Incremental Build Fails when using sitemap plugin

### ISSUE THREAD

**Issue by lilbumblebear** [react-static/react-static#1312]
If I run `build`, everything works as expected, but when I run `increment` with the react-static-sitemap-plugin I get the following error:

    [✓] HTML Exported (10.4s)
    Generating sitemap.xml...
    Error: Trace: Error: The sitemap url prefix cannot be empty or undefined!

### Environment

```

System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 3.46 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Firefox: 67.0.1
    Safari: 12.1.1
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-cookie: ^4.0.1 => 4.0.1 
    react-credit-card-input: ^1.1.5 => 1.1.5 
    react-div-100vh: ^0.3.4 => 0.3.4 
    react-dom: ^16.9.0 => 16.9.0 
    react-gtm-module: ^2.0.7 => 2.0.8 
    react-payment-inputs: ^1.0.6 => 1.0.6 
    react-router-dom: ^5.0.1 => 5.0.1 
    react-static: ^7.1.0 => 7.2.2 
    react-static-plugin-less: ^1.0.2 => 1.0.2 
    react-static-plugin-reach-router: ^7.0.10 => 7.2.2 
    react-static-plugin-react-router: ^7.0.10 => 7.2.2 
    react-static-plugin-sitemap: ^7.0.10 => 7.2.2 
    react-static-plugin-source-filesystem: ^7.1.0 => 7.2.2 
    react-static-plugin-typescript: ^7.0.10 => 7.2.2 
    react-structured-data: ^0.0.14 => 0.0.14 
    react-virtualized: ^9.21.1 => 9.21.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

of course include any other package versions here if relevant. 

### Steps to Reproduce the problem

1.  Try to run `yarn increment` with the react-static-sitemap-plugin 

### Expected Behavior

This should run the same as build, with no errors during output.

### Reproducible Demo

I do not have one at this time but will work on one. 

### Additional Note
The error mentions that **url prefix** cannot be empty, but I have siteRoot defined in static.config.js

[link to spectrum chat regarding this issue](https://spectrum.chat/react-static/general/export-fails-but-build-is-fine~b71ebdda-8a50-4e40-bdc8-7bd18a7bac92)

**Comment by SleeplessByte** [comment]
What does `yarn increment` do?

**Comment by lilbumblebear** [comment]
Sorry for the delayed response, got pulled onto some other work. 

This is the response from `yarn increment` 

` Error: Trace: Error: The sitemap url prefix cannot be empty or undefined! `

**Comment by benedfit** [comment]
The following environmental variables are set when `build` and `bundle` run - https://github.com/newhighsco/destiny-clan-warfare/blob/master/plugins/plugin-netlify-cache/node.api.js#L84-L98

But aren't set when `export` is run on its own. The sitemap relies on `process.env.REACT_STATIC_SITE_ROOT` being set, and this is the issue @lilbumblebear is experiencing

**Comment by benedfit** [comment]
This duplicates https://github.com/react-static/react-static/issues/1233

**Comment by SleeplessByte** [comment]
Should be an easy fix then! PRs welcome ❤️
