### ISSUE TITLE
Misleading usage information

### ISSUE THREAD

**Issue by jamesgeorge007** [react-static/react-static#1314]
![Screenshot from 2019-09-21 16-40-44](https://user-images.githubusercontent.com/25279263/65372490-aac4c600-dc8e-11e9-9494-7bfb887cca28.png)

Instead the usage information should be `react-static <command> [options]`

**Comment by jamesgeorge007** [comment]
I would happily submit a PR :+1:

**Comment by SleeplessByte** [comment]
I will gladly accept a PR for this :heart:
