### ISSUE TITLE
[Bug] Basic Template react-static build hangs at "Bundling App"

### ISSUE THREAD

**Issue by Robp773** [react-static/react-static#1315]
### Bug

I have two React Static sites which have both run into the same problem where images on the home page are coming up as 404 errors in the console.  Neither of these codebases have been updated in the past couple months and have only been rebuilt with webhooks periodically.  When I went to investigate why this was happening, I realized that  `react-static build` was hanging at "Bundling App" and these missing images were getting placed into the artifacts folder. 

I started a fresh basic template but `react-static build` is still hanging at "Bundling App".

I've tried installing/uninstalling different versions of npm/yarn and React Static but have had no luck. I've also tried --debug and --dev flags with react-static build. 

This issue is similar to [a previous issue](https://github.com/react-static/react-static/issues/1307) although the basic template doesn't seem to run into "TypeError: Property value expected type of string but got null" (I get that error intermittently with other my other React Static projects).

Any help with this would be greatly appreciated.

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 6.61 GB / 15.84 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.329.0
    Internet Explorer: 11.0.18362.1

**Node**: 10.16.0
**React Static**: 7.2.2

### Steps to Reproduce the problem

1. npm install -g react-static
2. react-static create test
3. select basic template
4. react-static build

### Expected Behavior

Successful build

**Comment by Herohtar** [comment]
This sounds like the known issue that is mentioned in the release notes and [this comment] (https://github.com/react-static/react-static/issues/1298#issuecomment-527886915)

**Comment by Robp773** [comment]
> This sounds like the known issue that is mentioned in the release notes and [this comment](https://github.com/react-static/react-static/issues/1298#issuecomment-527886915).

Yea it looks about the same - I can close this if it's basically a duplicate.  Do you know of any other workarounds besides using the ones mentioned in the 7.2.0 maintenance release? I'm running into another error when navigating away from my home page and it's impossible to debug without a finished build.

**Comment by SleeplessByte** [comment]
It's basically a duplicate, but that's fine. You can _always_ run with those flags, without issue. Perhaps that will help in the short-time.

> I've tried installing/uninstalling different versions of npm/yarn and React Static but have had no luck. I've also tried --debug and --dev flags with react-static build.

And your build still hangs?

**Comment by Robp773** [comment]
> And your build still hangs?
Actually I think it had some messed up dependencies from all of the different things I was trying- both the basic template and my project finish building with yarn build --debug. Sorry about that.

> Assuming it doesn't happen on a dev build? (yarn start)
Unfortunately it does happen with yarn start and is happening on my deployed site - even with a completed build.  Whenever I navigate off of the home page I get `TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`
After I refresh the broken page navigating anywhere else is fine - I just can't leave the home page without a crash.

**Comment by SleeplessByte** [comment]
Interesting! That is a completely new thing. 

Alright. At least you can now have something workable with an initial crash. This is on my top priority list.

**Comment by Robp773** [comment]
> Interesting! That is a completely new thing.
> 
> Alright. At least you can now have something workable with an initial crash. This is on my top priority list.

Sounds good, I'm going to close this issue since the --debug flag does work and that was handled in earlier issues. I'll continue to dig into the internal error issue next week. Thanks.

**Comment by SleeplessByte** [comment]
With 7.2.3 you should no longer need the flag -- but warnings will show. Don't be _warned_ tho, they were already there...
