### ISSUE TITLE
Hydrate store with data before static render

### ISSUE THREAD

**Issue by ghost** [react-static/react-static#1317]
Hey guys,

My website relies on data from a redux store that needs to be set according to what I get from route data. To prevent useless rerenders and weird side effects (sometimes store isn't updated before export occurs) it would be great if i could directly set as initial state the data from route data.

Is there any way I can hydrate my stores with route / site data before static rendering occurs ?

Thanks !

**Comment by nddery** [comment]
You should be able to use `useStaticInfo` to do this. This hook is only available during the export so you'll want to hydrate your store as an effect too.

https://spectrum.chat/react-static/general/is-it-safe-to-use-the-undocumented-usestaticinfo-hook~1e68f8ad-6ad7-46f2-a601-4c243e2a513e
