### ISSUE TITLE
[Feature] Divide sitemap into smaller pieces

### ISSUE THREAD

**Issue by krzysztof-pyrzyk-ah** [react-static/react-static#1322]
**Problem description**
Maximum sitemap size is 50MB containing no more than 50k of entries.
It has been proven though that smaller sitemaps may have positive impact on SEO.
Bots will more likely parse whole sitemap and index all urls if there are no more than 10k of them in 1 sitemap.

Currently we're generating more than 30k pages in with react-static and having them all in 1 sitemap is suboptimal. 

**Proposed solution**
Having an option in config file where it is possible to define a maximum number of entries per sitemap. When a maximum is reached sitemap_index.xml will get created and it will point to sitemap_1.xml, sitemap_2.xml, etc.

**Alternatives I've considered**
Running a sitemap optimization after it's generated. Some kind of a script that will split one file into smaller chunks and link them in sitemap_index.xml file.

**Additional context**
We can develop such a feature, but I'd like to know if the idea itself is OK from your point of view.

Thanks!

**Comment by SleeplessByte** [comment]
Yeah as long as it's a standardized solution, I'm all for this! Go ahead and see what you can make :)
