### ISSUE TITLE
[Bug] Site does not pass HTML5 validity test - charset issue

### ISSUE THREAD

**Issue by jurosh** [react-static/react-static#1333]
Running site validator: https://validator.w3.org/nu/#textarea
There is error: `Error: A charset attribute on a meta element found after the first 1024 bytes.`

Problem is that even when I update `Layout` and add meta tag for `charset` as first in Head, `react-static` put scripts and other meta tags above automatically when generating HTML.

**Comment by paulinachojnowska** [comment]
Seems to be a react-helmet issue: https://github.com/nfl/react-helmet/issues/239

**Comment by jurosh** [comment]
@paulinachojnowska This probably isn't the case. They are saying that `..on the server side, you can control the ordering of groups of head information (i.e. meta tags before title tag before link tags). And the ordering of tags should stay the same order they were given as props to Helmet.`

**Comment by nddery** [comment]
What is the `<Layout>` component you're referring to ? Are you referring to the [`Document` config property](https://github.com/react-static/react-static/blob/master/docs/config.md#document) ? If so, I think https://github.com/react-static/react-static/pull/1342 would fix your issue.

**Comment by SleeplessByte** [comment]
#1342 is merged so should be on master.
