### ISSUE TITLE
Frontmatter support in mdx plugin

### ISSUE THREAD

**Issue by mzedeler** [react-static/react-static#1336]
I would like to be able to use frontmatter in mdx files.

**Describe the solution you'd like**
That I can do this:
```
import AwesomeContent, { frontMatter } from './awesome-content.mdx'
```
and have `frontMatter` equal `{ title: 'Awesome!' }` if `awesome-content.mdx` starts with this:

```
---
title: Awesome!
---
```

**Describe alternatives you've considered**
The only alternative I can see now, is placing a JSON file next to the mdx file with the data I need. I have tried writing a react-static plugin to handle this, but it doesn't seem to be possible - it must be done in the mdx plugin.

**Comment by tingtom** [comment]
Maybe check out https://github.com/DanWebb/jdown and DanWebb's own react-static site as an example?

**Comment by mzedeler** [comment]
Thanks for the suggestion, but it seems that then I'm out of the mdx ecosystem, including the remark/rehype plugins?
