### ISSUE TITLE
[Bug] Using @operational/components fails during build

### ISSUE THREAD

**Issue by justinmchase** [react-static/react-static#1350]
### Reporting a bug?
After installing `npm i @operational/components` and adding a component to my page, react-static fails to build.

`npm start` succeeds but running `npm run build` or `npm run export` fails with an error saying `window is not defined`.

The error is:
```
Exporting HTML across 4 threads...
  ReferenceError: window is not defined

  - main.js:1
    [example]/[react-json-view]/dist/main.js:1:152093

# ...

 - Code.tsx:5 Object.<anonymous>
    [example]/[@operational]/components/src/Code/Code.tsx:5:1

# ...
```

- Link to [@operational/components/src/Code/Code.tsx:5:1](https://github.com/contiamo/operational-ui/blob/master/src/Code/Code.tsx#L5)

### Environment
```
  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
    Memory: 3.73 GB / 15.93 GB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/bin/node
    npm: 6.12.1 - /usr/bin/npm
  npmPackages:
    react: ^16.9.0 => 16.12.0
    react-dom: ^16.9.0 => 16.12.0
    react-hot-loader: ^4.12.11 => 4.12.18
    react-static: ^7.2.0 => 7.2.3
    react-static-plugin-reach-router: ^7.2.0 => 7.2.3
    react-static-plugin-sitemap: ^7.2.0 => 7.2.3
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.3
    react-static-plugin-typescript: ^7.2.0 => 7.2.3
```
Other:
```
@operational/components: ^18.0.0
```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  npx react-static create
2.  Select typescript
3.  npm i @operational/components
4. Modify `App.tsx` to contain the below code
5. run npm run build

```ts
// App.tsx
import React from 'react'
import { OperationalUI } from '@operational/components'
import { Root, Routes, addPrefetchExcludes } from 'react-static'
import { Link, Router } from '@reach/router'
import FancyDiv from 'components/FancyDiv'
import Dynamic from 'containers/Dynamic'
import './app.css'

// Any routes that start with 'dynamic' will be treated as non-static routes
addPrefetchExcludes(['dynamic'])

function App() {
  return (
    <Root>
      <nav>
        <Link to="/">Home</Link>
        <Link to="/about">About</Link>
        <Link to="/blog">Blog</Link>
        <Link to="/dynamic">Dynamic</Link>
      </nav>
      <div className="content">
        <OperationalUI>
          <FancyDiv>
            <React.Suspense fallback={<em>Loading...</em>}>
              <Router>
                <Dynamic path="dynamic" />
                <Routes path="*" />
              </Router>
            </React.Suspense>
          </FancyDiv>
        </OperationalUI>
      </div>
    </Root>
  )
}

export default App
```

### Expected Behavior

Artifacts are successfully built and exported like normal

**Comment by justinmchase** [comment]
Duplicates https://github.com/mac-s-g/react-json-view/issues/121

**Comment by is2ei** [comment]
@justinmchase 

I don't think it's a bug.
The doc says:

https://github.com/react-static/react-static/blob/master/docs/concepts.md
> Writing universal, "node-safe" code

> To fix these errors, you can stub and require the library conditionally:

**Comment by SleeplessByte** [comment]
`react-json-view` is probably not available for SSR, and thus the error message appears. I don't think this is an react-static error and by that, I think @justinmchase is correct.

**Comment by justinmchase** [comment]
I dug into this pretty extensively and its actually a dependency of `react-json-view` called `css-loader` which is throwing the error, and you're right it has to do with `SSR` rendering code that is not ssr safe.

This is not a `react-static` bug per-se so I will close this... but it is a pretty awful experience getting an error like this and not knowing how or why or what to do about it... It took me 3hrs of hard debugging to finally get to the bottom of it. I'm not sure what you can do about it but it may be a problem worth trying to improve at least. Maybe even if there was just an error during this phase to A) not produce such massive callstacks so that you can't see what the error is easily and B) suggest that the problem _might_ be related to SSR rendering not working...

Thanks for taking a look.

**Comment by SleeplessByte** [comment]
I absolutely like the idea of somehow capturing issues like this and have an actionable error.

RS 8 has a lot of that. It will tell you exactly what is wrong and how to fix it, just like create react app tries to.

I'm sorry for the invested time!
