### ISSUE TITLE
[Bug] Path with dot doesn't work

### ISSUE THREAD

**Issue by JoshClose** [react-static/react-static#1354]
### Reporting a bug?

Routes that contain a dot give the error `Cannot GET [path]`. I'm upgrading from a much older version of react-static and this used to work.

### Environment

```
$ npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers
npx: installed 1 in 2.21s

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.08 GB / 15.90 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    react: ^16.9.0 => 16.12.0
    react-dom: ^16.9.0 => 16.12.0
    react-router: ^5.1.2 => 5.1.2
    react-router-dom: ^5.1.2 => 5.1.2
    react-static: ^7.2.0 => 7.2.3
    react-static-plugin-react-router: ^7.2.3 => 7.2.3
    react-static-plugin-sass: ^7.2.2 => 7.2.2
    react-static-plugin-sitemap: ^7.2.0 => 7.2.3
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.3

```

### Steps to Reproduce the problem

1.  Create a basic template.
2.  Create a route such as
``` js
{
    path: "foo.bar",
    template: "src/pages/foobar"
}
```
3.  Run the site and try to go to the URL `/foo.bar`.

### Expected Behavior

Dots in the URL should not cause an error.

**Comment by SleeplessByte** [comment]
Note to self: is this `react-static`, `dev-server` or `react-router`?

**Comment by JoshClose** [comment]
Any ideas on this one? I believe this is the last issue I have remaining while updating the site from an older version of react-static.

**Comment by JoshClose** [comment]
I found that the issue is coming from webpack dev server. If I add this config, it goes away.

```js
devServer: {
	historyApiFallback: {
		disableDotRule: true
	}
}
```

I'm now getting this error.

```
404 - Oh no's! We couldn't find that page :(
```

**Comment by JoshClose** [comment]
I implemented `<Routes />`'s render prop and `getComponentForPath(routePath)` returns false for anything with a `.` in it.

**Comment by JoshClose** [comment]
Any route with a `.` in it doesn't get a request for `routeInfo`. 

`/__react-static__/routeInfo/foo.bar` isn't being called.

I'm trying to track this down, but it's a little difficult in the browser.

**Comment by JoshClose** [comment]
I found the issue.

https://github.com/react-static/react-static/blob/f15f8244141903994d70ac527661508c0e729ac4/packages/react-static/src/browser/index.js#L443

**Comment by SleeplessByte** [comment]
Right. 

And we'll probably keep that. Routes with `.` are not supported. The issue is that we can not differ between trying to fetch a file and trying to fetch a route, without exporting the known routes to _each and every url_, which can both be a lot of data and a security hole. 

_however_ perhaps in _DEV_ we cán make the routes accessible. I don't know quite how to go about this.

```json
devServer: {
	historyApiFallback: {
		disableDotRule: true
	}
}
```

Yeah that would be to fix the "devserver" part. The 404 after that is to be expected.

----

Thank you for looking into this <3

**Comment by JoshClose** [comment]
I'm using react-static for a documentation site. The URL paths I use have dots in them, and it really needs to stay like this. For example https://joshclose.github.io/CsvHelper/api/CsvHelper.Configuration.Attributes/ I would like a person to be able to type an API into the URL and it to come up. 

This is currently running on an older version of react-static and I'm upgrading it. How did it used to work?

**Comment by SleeplessByte** [comment]
Basically this change broke it for ya: https://github.com/react-static/react-static/pull/885.

I'm fine with "reversing" it, with a sensible different solution.

Can you try out if everything work for you if you drop the following:
```javascript
if (link.pathname.includes('.') && !link.pathname.includes('.html')) {
  return false;
}
```

If the answer is yes, we could reverse it and check for "blacklisted" extensions (like .jpg etc). That would remove most of the 404's whilst allowing `.` in urls. Also, change to `endsWith` and not `includes`.

**Comment by JoshClose** [comment]
How do I run the source locally? 

1. I downloaded the source. I ran `npm run build`. 
1. I changed my local script to run `node ...\\react-static\\packages\\react-static\\bin\\react-static start` instead of `react-static start`.

I get a build error `Missing class properties transform` when doing this and it runs fine when doing from the globally installed version.

**Comment by SleeplessByte** [comment]
`npm` won't work: https://github.com/react-static/react-static/blob/master/CONTRIBUTING.md#getting-started-with-the-source-code

**Comment by SleeplessByte** [comment]
(and you can use `yarn link` to use the local one)

**Comment by JoshClose** [comment]
Thanks for the info. Yes my site works when those lines are removed.

**Comment by SleeplessByte** [comment]
Alright. Could you PR COMMENTING-OUT those lines, and add a comment above it referring to this issue?

I'll have someone push a new release this week.

**Comment by JoshClose** [comment]
Will there be a release soon? If you can't do that, could you do a @next version?
