### ISSUE TITLE
[Bug] Can't render without <Suspense />

### ISSUE THREAD

**Issue by JoshClose** [react-static/react-static#1357]
### Reporting a bug?

When trying to create an app component per the documentation https://github.com/react-static/react-static/blob/master/docs/api.md#routes, it doesn't work without a `<React.Suspense fallback={<em>Loading...</em>}>` component.

I get the following error:

```
An internal error occured!

Error: RoutesInner suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    in RoutesInner
    in Unknown
    in Unknown (created by Context.Consumer)
    in withRouter()
    in Unknown (created by Routes)
    in Routes (at App.js:15)
    in Switch (at App.js:14)
    in div (at layout.js:11)
    in Layout (at App.js:13)
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Unknown
    in Unknown (created by Root)
    in Catch (created by Root)
    in Root (at App.js:12)
    in App
    in AppContainer (at src/index.js:21)
    at throwException (http://localhost:3000/main.js:86205:17)
    at handleError (http://localhost:3000/main.js:87317:11)
    at performSyncWorkOnRoot (http://localhost:3000/main.js:87037:15)
    at scheduleUpdateOnFiber (http://localhost:3000/main.js:86461:11)
    at updateContainer (http://localhost:3000/main.js:89880:7)
    at http://localhost:3000/main.js:90305:11
    at unbatchedUpdates (http://localhost:3000/main.js:87199:16)
    at legacyRenderSubtreeIntoContainer (http://localhost:3000/main.js:90304:9)
    at render (http://localhost:3000/main.js:90384:14)
    at render (http://localhost:3000/main.js:1769:5)
```

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```
$ npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers
npx: installed 1 in 1.621s

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.54 GB / 15.90 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Create a new react-static site.
2.  Remove the `<Suspense />` component.
3.  Run the site.

### Expected Behavior

The site should work without a `<Suspense />` component per the documentation, or have a flag in `<Root />` to turn it off.

**Comment by SleeplessByte** [comment]
The docs say:

> Note: Make sure to wrap components using `useSiteData()` with React's `<Suspense fallback="..."></Suspense>`. More information on the subject is available here.

What exactly is the bug?

**Comment by JoshClose** [comment]
Yeah. I guess the docs are out of date then. Having suspense be required is messing up something for me and I was trying to disable it. When I saw the docs aren't using it, I removed it and the page errors.

Maybe this could be a feature request to be able to run react-static without suspense then.

**Comment by SleeplessByte** [comment]
`Suspense` is a requirement because it's used when the `routeInfo` is being retrieved. What is it exactly that you're trying to do? Perhaps we can help!

**Comment by SleeplessByte** [comment]
Might be https://github.com/facebook/react/issues/15467. Might be something else. 

I would probably use an [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

**Comment by JoshClose** [comment]
`IntersectionObserver` works great. I hadn't heard of that before. Thanks!

I still think it would be nice to have suspense not be a required use, but my issue while using it is fixed now.

**Comment by SleeplessByte** [comment]
Alright. I'll close this then and but it on the list of requested features.

**Comment by pedro-lb** [comment]
Hey folks,

Just for documentation: we had this problem and it was related to a breaking change where `component` was renamed to `template`. By updating this, it was fixed =)

**Comment by SleeplessByte** [comment]
> React announces this about the suspense feature: "Caution: This page describes experimental features that are not yet available in a stable release. Don’t rely on experimental builds of React in production apps. These features may change significantly and without a warning before they become a part of React.". That is why I wanted to get rid of it. However, if React-Static is dependent on it there is no other way for me, and I will put the suspense there. So I do agree with @JoshClose that react-static should not require using suspense especially when the feature is not stable yet.

No, [Suspense](https://reactjs.org/docs/react-api.html#reactsuspense) is not experimental. [Concurrent Mode and Suspense for data fetching](https://reactjs.org/docs/concurrent-mode-suspense.html) is. We're using the first one, not the second one.

**Comment by OfficerHalf** [comment]
Adding <Suspense/> fixes the dev server, but then I get this error on build: https://reactjs.org/docs/error-decoder.html/?invariant=294

> ReactDOMServer does not yet support Suspense.

Not sure where to go from here.
