### ISSUE TITLE
Make site work without `unsafe-inline` CSP

### ISSUE THREAD

**Issue by abiro** [react-static/react-static#1362]
**Is your feature request related to a problem? Please describe.**

I've been setting up a Content Security Policy (CSP) for a react-static site and I've noticed that the way static html is generated currently requires `script-src 'unsafe-inline'` and `style-src 'unsafe-inline';` policies. Adding these policies opens up XSS and other attack vectors, so I'd prefer if the site worked without these policies.

Looking at a `react-static-example-basic` site, there are two issues. One is an inline script with the route info:

```html
<script type="text/javascript">
    window.__routeInfo = JSON.parse("{\"template\":\"READACTED/my-static-site/src/pages/index.js\",\"sharedHashesByProp\":{},\"data\":{},\"path\":\"/\",\"sharedData\":{},\"siteData\":{}}");
</script>
```

And two divs with the following inline style:

```html
<div style="outline:none" tabindex="-1" role="group">
```

**Describe the solution you'd like**

It would be great if there was an option to not to include the inline script and load the route info from the `routeInfo.json` at the cost of performance. I'm not sure where the `outline:none` style comes from and why it's necessary, but it would be great if that could be excluded somehow as well.

**Describe alternatives you've considered**

For the inline script, one could compute its hash and insert a meta tag with the CSP option  `script-src '<hash-algorithm>-<base64-value>';`, but I'm not sure how this would play with additional CSP configurations eg. from headers.

Happy to provide a PR with some guidance :)

**Comment by SleeplessByte** [comment]
```html
<div style="outline:none" tabindex="-1" role="group">
```

This most likely comes from `@reach/router`, which we can't "fix". You should inquire there about this one.

We'll happily and _eagerly_ accept a PR which adds a hash to the inline script tag, so that there is NO performance hit. You won't need additional headers.

**Comment by abiro** [comment]
> ```
> <div style="outline:none" tabindex="-1" role="group">
> ```
> 
> This most likely comes from `@reach/router`, which we can't "fix". You should inquire there about this one.

Thanks! I've left a comment [there](https://github.com/reach/router/issues/63#issuecomment-573426748), but it doesn't seem likely that there is a solution.

> 
> We'll happily and _eagerly_ accept a PR which adds a hash to the inline script tag, so that there is NO performance hit. You won't need additional headers.

The issue is that the script hash has to be added to the CSP directive, not the script tag. There are two ways to define a CSP: either in a `Content-Security-Policy` header or in an HTML meta tag (the former is the preferred way). In react-static static it would be only possible in an HTML meta tag, so the page would have the following tags:

```html
<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'sha256-abc123';">

...

<!-- The integrity attribute is just informative here, not necessary for the CSP. -->
<script integrity="sha256-abc123"  type="text/javascript">
    window.__routeInfo = JSON.parse("{\"template\":\"READACTED/my-static-site/src/pages/index.js\",\"sharedHashesByProp\":{},\"data\":{},\"path\":\"/\",\"sharedData\":{},\"siteData\":{}}");
</script>
```

But now the user can't add any other script sources to their CSP like a CDN, as that would either overwrite the `script-src` directive in the meta tag if it came from a header or it would be ignored if it was added in a subsequent meta tag (I looked this up now in the [CSP spec](https://w3c.github.io/webappsec-csp/#parse-serialized-policy)). 

My use case would be covered by the above solution with the meta tag, but I'm not sure if it's a good solution in general. Alternatively, if react-static output a file with inline script hashes to the dist folder, so that I can read that file and add the hashes to my CSP header dynamically, that would also solve my problem, but I don't think this is a good general solution either. So I think the simplest thing would be an option to exclude the inline script even that costs some performance (the route info is only needed to make the site interactive, but the site can render without it, right?).

**Comment by SleeplessByte** [comment]
> But now the user can't add any other script sources to their CSP like a CDN, as that would either overwrite the script-src directive in the meta tag if it came from a header or it would be ignored if it was added in a subsequent meta tag

That is correct -- I was suggesting adding it as a meta, and outputting it via the build plugins, so that one could ammend it/capture it.

> (the route info is only needed to make the site interactive, but the site can render without it, right?).
Yes and no. The site will suspend without it, which breaks pre-rendering

Right now this is what we do:

1. inject the route info
2. render the page, where we set the "context" for the route info to match `window.__routeInfo`
3. the rendered page is stored 

Wen we do 3, we can actually _remove_ the `window.__routeInfo`, although hydration will fail -- and another roundtrip is needed to make the site interactive (as you say).

A much easier solution would probably be to inject a meta tag, or add it as a `data-*` attribute. That solves all these issues.

**Comment by abiro** [comment]
> That is correct -- I was suggesting adding it as a meta, and outputting it via the build plugins, so that one could ammend it/capture it.
> ...
> A much easier solution would probably be to inject a meta tag, or add it as a `data-*` attribute. That solves all these issues.

Ok, happy to work on this, but would need some pointers. My best idea would be to add the inline script hashes to the `state` prop of [`Document`](https://github.com/react-static/react-static/blob/master/docs/config.md#document) and then the user can construct a CSP in a meta element as they wish.

**Comment by SleeplessByte** [comment]
> (I haven't checked the code so I'm not sure if it's possible to get the hashes at that point.)

The "render" of the Document happens pretty late, so yeah probably!

**Comment by abiro** [comment]
Ok, thanks! So you think adding the hashes to the ‘state’ prop of
‘Document’ is a good way to go?

**Comment by SleeplessByte** [comment]
Yeah, let's just do that for now. I think it's fine. Add a new key "hashes" or something like that, which is key value. Then make a unique, but understandable key per thing like `"route-info-hydration-js"`

**Comment by abiro** [comment]
Ok, I will try to submit a PR by the end of next week.

**Comment by abiro** [comment]
I haven't forgotten about this, but need more time :)

**Comment by SleeplessByte** [comment]
Do your thing!

**Comment by owenschoppe** [comment]
Hi there, I am trying to figure out how to use this new feature. I'm using an express server with helmet to serve the /dist directory. I can add a hash for every page to the CSP, but that seems cumbersome. The [docs](https://github.com/react-static/react-static/blob/master/docs/config.md#document) seem to imply that I can change a setting in `static.config.js` in order to set a single hash for all pages, or am I reading that totally wrong?

Can you provide an example for how to use `Document` in the `static.config.js` to configure `inlineScripts`?

Doing something like this gives me nothing but errors:
```
//static.config.js
...
Document: {
    state: {
      inlineScripts: {
        script: "script",
        hash: "sha256-kjhlkjhkljhlkjhkljhfg...",
      },
    },
  },
...
```

Thank you!

**Comment by abiro** [comment]
Hi @owenschoppe this feature is just to give you the hashes of the inline scripts generated by react-static at build time. You can then add these hashes to your CSP at build time to restrict scripts. The `Document.state` object is not meant to be set in the configuration file, it's something that `react-static` populates dynamically at build time to give you access to some internals like the inline script hashes in this case. Hope this helps!

**Comment by buddhamangler-cbre** [comment]
@abiro @SleeplessByte 

I am trying to follow the [documentation](https://github.com/react-static/react-static/blob/master/docs/config.md#document) related to creating site-wide meta tags.  However, after attempting to write out custom CSP meta tags I am finding that my strings are being encoded which I don't believe will work.

For instance, with the following code....

`  Document: ({
    Html,
    Head,
    Body,
    children,
    state: { routeInfo, siteData, renderMeta, inlineScripts },
  }) => {
    return (
      <Html lang="en-us">
        <Head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {Object.keys(inlineScripts).map((key) => (
            <meta
              http-equiv="Content-Security-Policy"
              content={`script-src=\'${inlineScripts[key].hash}\'`}
            ></meta>
          ))}
        </Head>
        <Body>hi's</Body>
      </Html>
    );
  },`

my resulting meta tag looks like this (single quotes are encoded)...

`    <meta
      http-equiv="Content-Security-Policy"
      content="script-src=&#x27;sha256-og5vccCPe6Stmme6KiUIBOaCn8mrsuEM1XnPIxr791o=&#x27;"
    />`
    
I have tried to switch to dangerouslySetInnerHtml, but that also does not work because the HEAD component is automatically injecting Link elements to the rendered head element and react throws an error saying you cant do both dangerouslySetInnerHtml and set children.

So how do I get this to render correctly?

**Comment by SleeplessByte** [comment]
There is no `=` inside the `CSP` value. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#using_the_html_meta_element

**Comment by buddhamangler-cbre** [comment]
> There is no `=` inside the `CSP` value. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#using_the_html_meta_element

thanks, but I realized that error after my post and edited it to match the correct value.  Still my question stands

**Comment by buddhamangler-cbre** [comment]
hi @abiro could you possibly share the technique you used to generate the meta tags correctly?  I am having trouble [here](https://github.com/react-static/react-static/issues/1362#issuecomment-985896164) with encoding that I don't see how to solve.

**Comment by buddhamangler-cbre** [comment]
> There is no `=` inside the `CSP` value. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#using_the_html_meta_element

Any thoughts on how to solve the encoding issue?

**Comment by abiro** [comment]
@buddhamangler-cbre I had a look and found this function, but I haven't found any usages and it's been two years so I can't guarantee that it works:

```
function getCSPString(inlineScripts) {
  let scriptSources = ''
  for (let k in inlineScripts) {
    scriptSources += `'${inlineScripts[k].hash}'`
  }
  // TODO (abiro) remove style unsafe inline
  // Solution: https://github.com/reach/router/issues/63#issuecomment-575748441
  const csp = `
  default-src 'none'; 
  prefetch-src 'self';
  script-src 'self' ${scriptSources};
  connect-src 'self' https://api.example.com https://cognito-idp.us-west-2.amazonaws.com;
  img-src 'self'; 
  style-src 'self' 'unsafe-inline';
  base-uri 'self';
  frame-ancestors 'none';
  form-action 'self';
  `.replace(/(?:\r\n|\r|\n)/g, ' ')

  return csp
}
```

`inlineScripts` should be the same object that you get from `Document.state` in `static.config.js`.

**Comment by gajanan999** [comment]
Hi ,

Could you please help  me to understand the standard way to add the hash into index.html

is there any lib or just take a hash from console and paste it into csp directive
