### ISSUE TITLE
Don't show Error Overlay on warnings

### ISSUE THREAD

**Issue by pie6k** [react-static/react-static#1368]
I'm using Typescript, and my config warns me about unused variables.

Those are, however warnings, not errors.

Yet, I'm not able to iterate with those, as it shows

![image](https://user-images.githubusercontent.com/7311462/72984225-73ecf100-3de3-11ea-9bce-8f692362a091.png)

It really slows me down, and I don't want to disable this rule, as it's useful for me when cleaning the code, but when I'm iterating quickly, I often have unused variables and other warnings.

Is it possible to relax the engine a bit, so it's showing errors overlay only on real errors?

**Comment by SleeplessByte** [comment]
Are you using the typesript plugin with ts-loader / awesome-typescript-loader? Because they emit the warnings as errors.
