### ISSUE TITLE
[Docs] https://react-static.js.org redirects to the GitHub repo

### ISSUE THREAD

**Issue by EdinK1** [react-static/react-static#1371]
The link near the headline of the repo redirects to this repo. I am not sure if this repo had a unique site for react-static before but I think that link doesn't work anymore. Nothing major, just wanted to point it out!

**Comment by SleeplessByte** [comment]
It was changed to link to here because the previous maintainer felt the docs were kept unmaintained. Starting with RS 8 we'll have a docs site again :)
