### ISSUE TITLE
[Bug] Bundle not working

### ISSUE THREAD

**Issue by JoshClose** [react-static/react-static#1372]
Bundling isn't working.

When it gets to `Bundling App...` is sits there forever. If I change the script to `react-static build --debug` it will build it successfully, but the html isn't minified.

### Environment

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.70 GB / 15.90 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    react: ^16.9.0 => 16.12.0
    react-dom: ^16.9.0 => 16.12.0
    react-router: ^5.1.2 => 5.1.2
    react-router-dom: ^5.1.2 => 5.1.2
    react-static: ^7.2.0 => 7.2.3
    react-static-plugin-react-router: ^7.2.3 => 7.2.3
    react-static-plugin-sass: ^7.2.2 => 7.2.2
    react-static-plugin-sitemap: ^7.2.0 => 7.2.3
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.3
```

### Steps to Reproduce the problem

1.  Clone `git@github.com:JoshClose/CsvHelper.git`
1.  Go into directory `CsvHelper/docs-src/docs`
1.  The project is currently linked to `react-static` source, so you'll need to `yarn link` `react-static` in the `react-static` source and then in this repo.
1.  Run `yarn`
1.  Run `yarn build`

### Expected Behavior

Building should not hang indefinitely.

**Comment by SleeplessByte** [comment]
Thank you for the example repo! I'll see if this is the same issue as the one we had before or if this is something new.

**Comment by JoshClose** [comment]
When running with the `--debug` flag, all my links are wrong. It's not taking into account the set `basePath`. I tried putting a `devBasePath` in and that didn't help either.

**Comment by JoshClose** [comment]
The `--staging` flag hangs also.

**Comment by SleeplessByte** [comment]
> When running with the --debug flag, all my links are wrong. It's not taking into account the set basePath. I tried putting a devBasePath in and that didn't help either.

I'll check this out for ya too .

**Comment by sochix** [comment]
@SleeplessByte the same issue appeared for me

**Comment by moop-moop** [comment]
Anybody know what the last version was that react-static examples worked on Windows?

**Comment by SleeplessByte** [comment]
7.1.2 I think.
