### ISSUE TITLE
Is there any support for URL cloaking for affiliated redirects?

### ISSUE THREAD

**Issue by shalin51** [react-static/react-static#1382]
Our business affiliated with partners and for tracking purpose they redirect to their portal. I want to mask or cloak the URL.

Is there any way to bypass the URL by any how? I don't want users to see their URLs and redirects.

**Comment by SleeplessByte** [comment]
It's common to redirect to something _internal_ such as `yourdomain.com/out/uuid-or-slug` and then redirect to their affiliate URL, which will stop their URL from showing on hover, and if they redirect again, using a HTTP 30X it will also not show up in the history. 

However. This is not a react static specific question, and there is no specific support for this.
