### ISSUE TITLE
[Docs] Webpack config

### ISSUE THREAD

**Issue by neilyoung** [react-static/react-static#1384]
If you haven't dealt with react-static for a while, it always surprises you...

OK, I  have an old project, which has this `static-config.js`:

```
export default {

  webpack: (config, { stage }) => {
    if (stage === 'prod') {
      config.performance = {
        maxEntrypointSize: 512000,
        maxAssetSize: 512000
      }
      config.stats = {
        warnings: false
      }

    }
    
    return config
  }
}

```

I'm now running react-static-cli 5.9.12 under node 13.9.0, but this seems to not work anymore. At least if I try to intercept the stuff by adding a console.log(), it does not appear.

Please, how do I have to do that?

**Comment by SleeplessByte** [comment]
It has moved to the [plugin API](https://github.com/react-static/react-static/blob/master/docs/plugins/node-api.md#webpack). I found this by:

1. Going to the docs root: https://github.com/react-static/react-static/tree/master/docs
1. Going to the config docs: https://github.com/react-static/react-static/blob/master/docs/config.md
1. Following the link at the bottom to plugins API: https://github.com/react-static/react-static/tree/master/docs/plugins
1. Following "transform your webpack config" link: https://github.com/react-static/react-static/blob/master/docs/plugins/node-api.md#webpack

**Comment by neilyoung** [comment]
@SleeplessByte Thanks. But I have read this change was done with version 6 (not checked if there is a version 6 at all yet)?

**Comment by SleeplessByte** [comment]
Ah. I'm seeing you're on 5.9.12. Oof. Sorry, I don't know what happened there -- I wasn't around until version 7. Going forward I'd love us to support older versions, but I'm simply out of my depth here.

Would downgrading node to say <= 10 be an option, and does that work?

**Comment by neilyoung** [comment]
Good point. Will try

**Comment by neilyoung** [comment]
No, doesn't work.  But I realized, I was just thinking I was running 5.9.12. In fact it is 7... So I have to use the new pattern.

Thanks

**Comment by neilyoung** [comment]
In between I downgraded to 5.9.12 and the old patter works too. With Node 10 and 13
