### ISSUE TITLE
[Bug] On fresh project, react-static CLI commands fail while yarn commands succeed

### ISSUE THREAD

**Issue by j4p3** [react-static/react-static#1387]
I recently reinstalled dependencies on a project to debug an unrelated issue. On running the dev server, I saw `Error: Neither the page template or 404 template could be found. This means something is terribly wrong. Please, file an issue!` in the console.

Weird, I thought. I tried on a fresh project to make sure it wasn't some global issue on my machine. Same problem. Fresh projects don't seem to be able to run `react-static start`.

Obviously the recommended usage is `yarn start`, not `react-static start`. And `yarn start` does behave as expected, resolving the problem. Still, it's probably worth filing an issue if the CLI isn't working on fresh projects.

### Environment

```
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 20.83 GB / 30.99 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.6 - /usr/bin/npm
  Browsers:
    Firefox: 73.0
  npmPackages:
    react: ^16.9.0 => 16.12.0 
    react-dom: ^16.9.0 => 16.12.0 
    react-static: ^7.2.0 => 7.2.3 
    react-static-plugin-reach-router: ^7.2.0 => 7.2.3 
    react-static-plugin-sitemap: ^7.2.0 => 7.2.3 
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.3
```

### Steps to Reproduce the problem

To reproduce:

1. `yarn global add react-static`
2. `react-static create`
3. select `basic`
4. `cd <app name>`
5. `react-static start`

### Expected Behavior

Basic page loads at localhost:3000.

Actual behavior:

Error returned by localhost:3000.

Error content:

```
An internal error occured!

RoutesInner@http://localhost:3000/main.js:50062:13
renderWithHooks@http://localhost:3000/main.js:32388:31
mountIndeterminateComponent@http://localhost:3000/main.js:34871:17
beginWork$1@http://localhost:3000/main.js:36222:20
callCallback@http://localhost:3000/main.js:16409:18
invokeGuardedCallbackDev@http://localhost:3000/main.js:16458:20
invokeGuardedCallback@http://localhost:3000/main.js:16511:35
beginWork$$1@http://localhost:3000/main.js:41847:32
performUnitOfWork@http://localhost:3000/main.js:40764:16
workLoopSync@http://localhost:3000/main.js:40737:26
performSyncWorkOnRoot@http://localhost:3000/main.js:40326:15
flushSyncCallbackQueueImpl/<@http://localhost:3000/main.js:28358:28
unstable_runWithPriority@http://localhost:3000/main.js:57203:16
runWithPriority$2@http://localhost:3000/main.js:28304:14
flushSyncCallbackQueueImpl@http://localhost:3000/main.js:28353:28
workLoop@http://localhost:3000/main.js:57147:46
flushWork@http://localhost:3000/main.js:57102:20
performWorkUntilDeadline@http://localhost:3000/main.js:56698:52
```

### Reproducible Demo

https://github.com/j4p3/test-rs-bork

(This is just a basic react-static template).

**Comment by SleeplessByte** [comment]
> Obviously the recommended usage is yarn start, not react-static start. And yarn start does behave as expected, resolving the problem. Still, it's probably worth filing an issue if the CLI isn't working on fresh projects.

So the issue is that on **fresh** projects, `yarn start` works but `react-static start` doesn't?

`react-static start` is (undocumented still) meant to be ran from a `yarn` context, because then it can find the project root correctly (which is the real issue here, as `react-static` runs it "globally"). This limitation is removed in the next major.
