### ISSUE TITLE
Project folder structure in public assets path

### ISSUE THREAD

**Issue by donhessman** [react-static/react-static#1391]
I'm hoping this is just a silly mistake on my part and this is an easy fix. When building my site, React Static serves my JavaScript files from URLs that mirror my project structure. Shockingly, this goes all the way to root. Like:
```javascript
<script defer type="text/javascript" src="/templates/vendors~Users/my.user.name/my.project.name/src/routes/home/Home.somehash.js"></script>
```

I've messed with a few of the path config settings but that only seems to change what these URLs are prefixed with. Any suggestions?

**Comment by donhessman** [comment]
Ah, it sounds like this is known issue that will be fixed in the next major release hopefully: https://spectrum.chat/react-static/general/my-machines-local-path-is-being-added-to-assets-during-build~651032e1-5e01-4a7a-afcb-ec5d5938f913

**Comment by SleeplessByte** [comment]
Correct. It's a known issue. Best bet is to downgrade to 7.1.0 if you need to build right now :)

**Comment by donhessman** [comment]
Thanks @SleeplessByte that worked for me!

**Comment by SleeplessByte** [comment]
Closing in favor of #1375
