### ISSUE TITLE
[Docs] 'serve' doesn't properly serve nested routes

### ISSUE THREAD

**Issue by taylorhayduk** [react-static/react-static#1393]
### Reporting a bug?

I used `react-static create` to bootstrap my site. 

I'm using a CMS to generate static nested routes.  When I ran `react-static build` then `serve dist -p 3000 -s`, I got the loading indicator on first load of my nested pages, even though the page was statically generated.

I switched to `http-server dist -p 3000 -s` and all pages loaded without the loading indicator, even with javascript disabled in the browser.

### Steps to Reproduce the problem

1.  Bootstrap app `react-static create`
2.  Add nested routes with getData
3. Run  `react-static build` then `serve dist -p 3000 -s`
4. Notice the nested routes show the loading indicator on non-dynamic pages.
5. If you swap it with http-server it works perfectly!

### Expected Behavior

Static pages should not have loading indicator since and be served as static hydrated html.

**Comment by SleeplessByte** [comment]
> Static pages should not have loading indicator since and be served as static hydrated html.

Right but you've tested this with `http-server` so the issue is with `serve` and not `react-static`. We'll accept a PR to list the issue with `serve` and have the `http-server` as working alternative.

Thank you very much for testing this 👍
