### ISSUE TITLE
[Bug] JavaScript and CSS files don't load when a custom 'assets' path is set

### ISSUE THREAD

**Issue by cmmartti** [react-static/react-static#1397]
To reproduce:

- Create a new project with the "basic" template
- Add `paths: {assets: 'assets'}` to the */static.config.js* file
- Run `npm run build`

The exported HTML files wrongly link JavaScript files and other assets from the project root even though they are in */assets*. As a result, all assets fail to load and the result is an unstyled HTML file with no JavaScript.

Since the assets themselves have been properly exported to */assets*, this points to the problem being in the paths being translated incorrectly at the point they're written to the HTML file. This happens in the modules *[/src/static/components/HeadWithMeta](https://github.com/react-static/react-static/blob/master/packages/react-static/src/static/components/HeadWithMeta.js)* and */src/static/components/BodyWithMeta*.

A cursory inspection indicates that the bug may exist in the `pathJoin` or `makePathAbsolute` util functions. It's not immediately obvious to me how to fix it, and I don't have the time to look into it further. At the moment, setting a custom assets path is not necessary, so I have put it back to the default.

**Environment:**

WSL on Windows 10.

Builds fail on Windows proper due to #1360, so I was not able to test there.

<details>
    <summary>See <code>envinfo</code> results</summary>

#### System:
OS: Linux 4.4 Ubuntu 16.04.4 LTS (Xenial Xerus)
CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
Memory: 523.59 MB / 7.91 GB
Container: Yes
Shell: 4.3.48 - /bin/bash

  #### Binaries:
Node: 10.16.0 - /usr/bin/node
Yarn: 1.12.3 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
npm: 6.14.2 - /usr/bin/npm

  #### npmPackages:
 react: ^16.9.0 => 16.13.0
react-dom: ^16.9.0 => 16.13.0
react-static: ^7.2.0 => 7.2.3
react-static-plugin-reach-router: ^7.2.0 => 7.2.3
react-static-plugin-sitemap: ^7.2.0 => 7.2.3
react-static-plugin-source-filesystem: ^7.2.0 => 7.2.3

  #### npmGlobalPackages:
react-static: 7.2.3
</details>

**Comment by nddery** [comment]
Thanks for reporting this issue, you should be able to fix this by updating your Webpack config with the content of https://github.com/react-static/react-static/pull/1329 while this is worked out in `react-static` itself.

```js
// inside /node.api.js

export default () => ({
  webpack: (config, { stage }) => {
    if (stage === 'prod') {
      config.output.publicPath = process.env.REACT_STATIC_ASSETS_PATH || '/'
    }

    return config
  }
})
```

Note that this may not work depending on your specific config - for example if you only had declared a `basePath` (which isn't your case here).
