### ISSUE TITLE
JS File paths mimicking the filesystem

### ISSUE THREAD

**Issue by anthonyv1121** [react-static/react-static#1404]
When I build my project the JS for each page is saved in a path that mimics the filesystem. How can this be changed?
`<script defer="" type="text/javascript" src="/templates/Users/joegk/Desktop/Projects/clients/landing-page/sample-static/src/pages/index.0e41b5c1.js"></script>`

**Comment by efoken** [comment]
Yeah I also have problems with that... and because of that, the resulting file paths are way too long

**Comment by SleeplessByte** [comment]
See: https://github.com/react-static/react-static/issues/1391

Due to the ongoing pandemic we're having trouble allocating time for #1375 , but we will make an effort to release it coming week.
