### ISSUE TITLE
[Docs] Scroll on top when changing page

### ISSUE THREAD

**Issue by PolMrt** [react-static/react-static#1410]
Hello,

First of all thanks for react-static !

I'm currently looking for a way to reset the scroll to the top page when changing pages. I've saw an issue about it #551 with `autoScrollToTop={true}` on the `<Router>` but it did not work and seems to be deprecated since it not longer mentionned on the doc. So what's the way to do that ?

Thanks for your help !

**Comment by SleeplessByte** [comment]
It depends on your router. The easiest thing is something like this:

```jsx
export default function ScrollToTop() {
  const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return null;
}
```

You would then "just" mount this inside the router:

```jsx
<Root>
  <ScrollToTop />
...
```

**Comment by froatsnook** [comment]
@SleeplessByte This works great except that it also scrolls to the top when you go back.

**Comment by SleeplessByte** [comment]
That's correct. This is `ScrollToTop`, not "ScrollRestoration".
