### ISSUE TITLE
[Docs] How to Deploy On Azure

### ISSUE THREAD

**Issue by AlexanderKidd** [react-static/react-static#1412]
This is a nifty project, but how do I go about this on Azure? I've tried manual FTP upload of dist folder but it won't even take the index.html. Potentially because it looks for certain things in a node.js app.

**Comment by SleeplessByte** [comment]
A built react-static app doesn't have anything node-y. If you want to build it in an Azure pipeline, it won't "need" `index.html`, but probably do:

- `git clone`
- `yarn`
- `yarn build`
- artifacts: `dist/**`

We welcome documentation contributions via a PR!

**Comment by AlexanderKidd** [comment]
Okay, worked like a charm with Azure storage/CDN for the static version. I'll go ahead and close this, the [official Azure docs](https://docs.microsoft.com/en-us/visualstudio/javascript/publish-nodejs-app-azure?view=vs-2019) should help anyone needing to push to Azure but I think that's a separate issue not affecting react-static.
