### ISSUE TITLE
[Feature Request] Reduce bundle size + dependencies?

### ISSUE THREAD

**Issue by mikestopcontinues** [react-static/react-static#1414]
**Is your feature request related to a problem? Please describe.**

Building RS throws bundle size warnings. Looking at the vendor bundle, there are a few packages that can definitely be replaced. The two standouts to me are `react-helmet` and `axios`. Both have much smaller alternatives. 

For `react-helmet`, `react-head` would save 4.5k after compression.
https://bundlephobia.com/result?p=react-helmet@6.0.0
https://bundlephobia.com/result?p=react-head@3.3.0

And for `axios`, `isomorphic-unfetch` would save 4k after compression.
https://bundlephobia.com/result?p=axios@0.19.2
https://bundlephobia.com/result?p=isomorphic-unfetch@3.0.0

There are other to look into. For instance, `history` v5 looks like it will be much smaller. Something to keep an eye on. The intersection observer polyfill is also really big. It might be worth considering producing that functionality some other way.

**Describe the solution you'd like**

I'd like to see the vendor bundle reduced down to the bare essentials.

**Describe alternatives you've considered**

The deps all look critical to RS functionality, so this is the only solution I see.

**Additional context**

I am open to submitting PRs, if you're open to merging them! 😁

**Comment by SleeplessByte** [comment]
I think they're working on a new axios which is much smaller, but I'm not completely certain. Switching out `axios` will be a breaking change (moving from XHR to `fetch`).

I'm not actually sure if `react-helmet` is being bundled in the final code, but definitely in favour of moving that out. This will come with some caveats. We currently have some custom build step for helmet, to SSR it.

> The intersection observer polyfill is also really big. It might be worth considering producing that functionality some other way.

Unfortunately we do use quite a bit of that polyfill and its key to why pages load so fast with react-static. I doubt we'll be able to replace this until we drop IE support.

**Comment by mikestopcontinues** [comment]
Axios: Unless axios itself switches to fetch, I don't see them being able to cut too much code. I took a look a year or so ago, and nothing stood out. While I think a fetch polyfill would be the best call, there's also `redaxios`, which preserves the axios api, but uses fetch under the hood. However, it adds almost 1k zipped on top of the polyfill to preserve all the transformers and stuff.

React-Helmet: Do you mean not-bundled in the `export` code? That's good to know, though one of my use cases requires bundling once, and exporting multiple times in serverless, so I would still be interested in pulling it out. On the topic, why no out-of-the-box `export` bundle-analyzer? Have I simply missed it?

IntersectionObserver: What does it get used for other than prefetch visibility? For that, a hook/handler leveraging one window.onScroll that does the math for each element (with scrollY, viewport height, etc) would totally replace the need. 

In any case, thanks for getting back so quickly. I'm eager to hear what you think.

**Comment by SleeplessByte** [comment]
> axios

I'm more concerned about people hooking into the XHR events. `fetch` is still not cancelable (only the "parsing" of the request is, the request itself isn't), which is suboptimal for react. That said, I'm still _ok_ with changing it out. It will just have to be a major upgrade (breaking change).

>  why no out-of-the-box export bundle-analyzer? Have I simply missed it?

I think the cli accepts `--analyze`. You'll want to look at `packages/react-static/**/bin`. This should list all the options!

> IntersectionObserver: What does it get used for other than prefetch visibility? For that, a hook/handler leveraging one window.onScroll that does the math for each element (with scrollY, viewport height, etc) would totally replace the need.

Yes, this is exactly what it's used for at moment. I do think that it won't be simple math. I've seen quite a few hooks that _try_ to do this, but they don't work consistently across environments. However, I will gladly accept such a change, if we can be fairly certain it works in 95%+ of the cases 🗡️!

**Comment by guy-kdm** [comment]
Perhaps we can also have an easier path to avoid react-router? Maybe a template?

**Comment by mikestopcontinues** [comment]
@guy-kdm I don't think react-router is bundled by default, is it? That said, upgrading to RR v6 (stable beta) cuts the size down considerably. You'll have to update `react-static-plugin-react-router` though.

**Comment by docrinehart** [comment]
FWIW (as I'm trying to use RR v6) I think it's worth calling out.

> Reach Router and it’s sibling project React Router are merging as React Router v6. In other words, Reach Router v2 and React Router v6 are the same.
~ https://reach.tech/router/

That said, it does look like I'll need to dig into `react-static-plugin-react-router` and look at updating it locally. Maybe if I find time to do so, I can submit a PR....
