### ISSUE TITLE
Next release ETA

### ISSUE THREAD

**Issue by simoncorompt** [react-static/react-static#1415]
Hello guys,

Hope you're all doing well in these tough times!

I just had a look at the changelog on master, lots of really nice updates and improvements in there :) I was just wondering if you think we're close to a release, or if you want to add some more things in there before pushing?

In any case, thanks a lot and take care!

**Comment by SleeplessByte** [comment]
I want to have a proper few hours with #1375, including the latest fix by @nddery, which I need to merge in tonight. After that I'll instantly start a Release 7.4.0 branch; I really just need more people to test it out. So the ETA could be 1 day, but also 1 month.

We're struggling under COVID-19 at the moment.

**Comment by nddery** [comment]
For what it's worth, I've tested the 7.3.0 release on our builds and it seemed to go fine.

**Comment by SleeplessByte** [comment]
_All_ packages have been bumped to 7.3.0; you can try it out now and file bug reports.
