### ISSUE TITLE
[Bug] tabindex=-1 on upper elements prevent pagedown/pageup on desktop

### ISSUE THREAD

**Issue by Altiano** [react-static/react-static#1417]
React static have `tabindex=-1` on upper elements,
this prevents `pagedown`/`pageup` on desktop.

![image](https://user-images.githubusercontent.com/8316282/80704638-22a17b80-8b0f-11ea-80da-c41efafe1558.png)

This happens in Chrome & Firefox. Don't know about other browsers

**Comment by SleeplessByte** [comment]
This probably comes from the router -- not `react-static`. It also _doesn't prevent pageup/pagedown_. For example: https://dna-top10.com/ is a React Static site. On both Chrome and Firefox it allows for tabbing AND page-up/page-down, even after tabbing.

If that doesn't work for you, it's probably your environment.
