### ISSUE TITLE
[Docs] Clarify react-router plugin doesn't need an explicit Router component

### ISSUE THREAD

**Issue by dlopuch** [react-static/react-static#1422]
I landed on #937 because I was getting the 'Browser history needs a DOM' trying to incorporate react-router. I assumed the BrowserRouter/StaticRouter implementation-switch discussed there was something I had to make in my code, but it was clarified that's being done by the plugin.

This magic is very nice, but very unintuitive. Being familiar with react-router, I naturally assumed I needed a Router somewhere in my react-static app.

It would be helpful if https://github.com/react-static/react-static/blob/master/docs/guides/dynamic-routes-react-router.md or https://github.com/react-static/react-static/tree/master/packages/react-static-plugin-react-router was updated with a quick one-liner like "Note that you don't need to include any `<Router>` component in your app because react-static-plugin-react-router automagically incorporates it into the `<Root>` component"

**Comment by pedro-lb** [comment]
Had this problem too, would be of great help
