### ISSUE TITLE
[Bug] Routes not rendered statically in 7.3.0

### ISSUE THREAD

**Issue by stefan-h-singer** [react-static/react-static#1446]
Even the default "react-static create" shows the issue. Downgrading to 7.2.3 fixes the problem.

**Comment by SleeplessByte** [comment]
Should be fixed. Released as 7.4.0;

**Comment by stefan-h-singer** [comment]
Awesome, thanks!

**Comment by nddery** [comment]
Closing this as it's been fixed in 7.4.0, thanks for the report!
