### ISSUE TITLE
certificate has expired when npm run build

### ISSUE THREAD

**Issue by yud1z** [react-static/react-static#1449]
hi guys

i have a problem when doing npm run build
it shows certificate has expired
i am not sure how we get this, since data api only get from http local only.
is there any configuration i must edit?

`=> Cleaning dist...
=> [✓] Dist cleaned
=> Cleaning artifacts...
=> [✓] Artifacts cleaned
=> Building Routes...
  Error: certificate has expired

  - _tls_wrap.js:1046 TLSSocket.onConnectSecure
    _tls_wrap.js:1046:34

  - events.js:180 TLSSocket.emit
    events.js:180:13

  - _tls_wrap.js:633 TLSSocket._finishInit
    _tls_wrap.js:633:8`

for complete error

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.9.0
3 info using node@v9.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle aov_main@1.0.1~prebuild: aov_main@1.0.1
6 info lifecycle aov_main@1.0.1~build: aov_main@1.0.1
7 verbose lifecycle aov_main@1.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle aov_main@1.0.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/aov_main_src/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle aov_main@1.0.1~build: CWD: /var/www/html/aov_main_src
10 silly lifecycle aov_main@1.0.1~build: Args: [ '-c', 'react-static build' ]
11 silly lifecycle aov_main@1.0.1~build: Returned: code: 1  signal: null
12 info lifecycle aov_main@1.0.1~build: Failed to exec build script
13 verbose stack Error: aov_main@1.0.1 build: 'react-static build'
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid aov_main@1.0.1
15 verbose cwd /var/www/html/aov_main_src
16 verbose Linux 4.4.0-143-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v9.11.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error aov_main@1.0.1 build: 'react-static build'
22 error Exit status 1
23 error Failed at the aov_main@1.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by SleeplessByte** [comment]
My guess is that your computer has outdated certificates. This has nothing to do with react-static.

Perhaps try the following:

- Update node to the latest LTS
- Update yarn/npm
- Update via Windows Update/Homebrew update
