### ISSUE TITLE
Unintentional: Page scrolling just below the header while link navigation

### ISSUE THREAD

**Issue by shallinpartap** [react-static/react-static#1453]
Hello,

I am having this issue with the site I am building.

**I have a Header component which is same for the page on my site. When I clicking between links to navigate to the other pages, my site is scrolling just below the header.**

Currently my header is living on the App.jsx page. If i move my header component to all the individual pages, then page navigation works fine (I mean the next page starts from scoll postion 0, which is what is expected).

I am on chrome, Also tried CSS **'overflow-anchor: none;'** on the body.

Here is my App.jsx file:

```
function App() {
  return (
    <Root>
      <div className="app">
        <Header />
        <div className="app-content">
          <React.Suspense fallback={<em>Loading...</em>}>
            <Router>
              <Routes default />
            </Router>
          </React.Suspense>
        </div>
        <Footer />
        <Disclaimer isDialog />
      </div>
    </Root>
  );
}

export default App;

```

Please help? Thanks in advance

**Comment by SleeplessByte** [comment]
This is a _feature_ of `reach-router`. It's so screen readers etc. see the content of your app.

You can move the header _inside_ the router:

```jsx
<div className="app-content">
  <React.Suspense fallback={<em>Loading...</em>}>
    <Header />
    <Router>
       <Routes default />
    </Router>
  </React.Suspense>
</div>
```

If you're not using react-router, then it's something similar (focus after page load). This is **not** part of react-static, and definitely not a bug.

**Comment by shallinpartap** [comment]
Thanks for pointing me to right direction @SleeplessByte .

Now, I have more understanding of @reach/router.

I fixed the above issue by adding primary=false attribute to the Router component by have a wrapper component "ScrollToTop" to wrap my routes:


```
const ScrollToTop = ({ children, location }) => {
  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      window.scrollTo(0, 0);
    }
  }, [location.pathname]);
  return children;
};
```


```
function App() {
  return (
    <Root>
      <div className="app">
        <div className="app-content">
          <React.Suspense fallback={<em>Loading...</em>}>
            <Header />
            <Router primary={false}>
              <ScrollToTop path="/">
                <Routes default />
              </ScrollToTop>
            </Router>
            <Footer />
            <Disclaimer isDialog />
          </React.Suspense>
        </div>
      </div>
    </Root>
  );
}
```

Reference: https://github.com/reach/router/issues/242#issuecomment-491537468

Issue resolved! 
Thanks
