### ISSUE TITLE
styled-components ^5.x.x support

### ISSUE THREAD

**Issue by arekstryjski** [react-static/react-static#1455]
I try to use styled-components in my project.

After installing (npm) react-static-plugin-styled-components I was expecting styled-components to be also installed into to node_modules - this did not happened.
After installing manually `npm i styled-components` I got this error:

npm ERR! peer dep missing: styled-components@^4.3.2, required by react-static-plugin-styled-components@7.3.0

I can fix it but it will be good to have support of latest version of styled-components if possible.

**Comment by SleeplessByte** [comment]
Agreed. We'll accept a PR for this!

**Comment by SleeplessByte** [comment]
I agree with #1473.
