### ISSUE TITLE
[Bug] Issues with data rendering 

### ISSUE THREAD

**Issue by vikrantraut** [react-static/react-static#1457]
Hi,

I am using react static last 1.5 years, but some time refreshing site shows error like, check the below image: 
![error-1](https://user-images.githubusercontent.com/11265317/84475655-8f7d6900-acaa-11ea-99bd-e0a9284c58bd.jpg)

2. Sometimes just loaded the header and footer not main page data.
3. Sometime just load html, CSS is not loaded properly. Check the below image:
![Screen_Capture_1](https://user-images.githubusercontent.com/11265317/84475571-6c52b980-acaa-11ea-941b-31287b4a878f.png)

**Comment by atralice** [comment]
I have the same issue. When arriving to the site via and URL that is not the '/', some CSS is not showed.

Were you able to fix this?
Thanks!

**Comment by 6mint** [comment]
I encounter this issue as well.
It might correspond to: https://github.com/react-static/react-static/issues/1203

**Comment by SleeplessByte** [comment]
If you, for example, run this on Netlify, or Cloudflare, _caching_ isn't doing what you expect it does. I don't actually have a report that there is something broken in react-static. Sofar it seems circumstantial.

**Comment by markatli** [comment]
Same issue here

**Comment by SleeplessByte** [comment]
> Same issue here. Makes us nervous running React Static in production. Anyone has an update or fix? Thanks

@markatli the previous message:

> If you, for example, run this on Netlify, or Cloudflare, _caching_ isn't doing what you expect it does. I don't actually have a report that there is something broken in react-static. Sofar it seems circumstantial.

...still applies. Without a minimal reproducible example, this can't be "fixed". It's much more likely it's because of caching strategy on the host than that it's react-static.

**Comment by alqamabinsadiq** [comment]
@SleeplessByte In our case, everything is working fine except that it re-renders the entire app when you visit it.

After checking the console logs I see the following message from react-static:

`React Static: Templates Reloaded`
