### ISSUE TITLE
[Docs] How to configure MDX Remark-Mermaid plugin?

### ISSUE THREAD

**Issue by arekstryjski** [react-static/react-static#1458]
I'm trying to use MDX with Remark-Mermaid plugin

<https://github.com/temando/remark-mermaid>
<https://mermaid-js.github.io>

Does anyone know how to configure it (pass `data.destinationDir`) that generated SVG files are placed in `public` not in the source folder?

**Comment by itaditya** [comment]
Aah the rush to see exact question being asked on a React SSG project and the sudden dissapointment of not having any replies. 😭 

@arekstryjski tell me you figured it out somehow.
