### ISSUE TITLE
SCSS Modules Support (^v7.2.0)

### ISSUE THREAD

**Issue by thedanchez** [react-static/react-static#1460]
I've been experiencing great difficulty getting the basic React-Static TypeScript template to recognize my use of SCSS modules. I've added the `react-static-plugin-sass` to my `package.json` and `static.config.js` but things are not working the way that they should according to what I've read.

I'm hoping someone can help with this if they've already resolved it. Another question is, can a new react-static project template be made that sets up both TypeScript and SCSS so that others can just get going without having to spend a lot of time trying to configure it manually?

**Comment by riotrah** [comment]
I've had the same issues. I don't think scss modules are supported. My styles work if I convert them to css modules and that's all I do currently 🤷🏽‍♀️

**Comment by zjxpcyc** [comment]
In my config

```
[
  'react-static-plugin-sass',
  {
    cssLoaderOptions: {
      modules: true,
      localIdentName: '[name]__[local]--[hash:base64:5]',
      importLoaders: 2
    }
  }
]
```

It's done
