### ISSUE TITLE
[Bug] Error: EINVAL: invalid argument, mkdir 'C:\Users\zouhair\works\Desktop\test\AwesomeProject2\ios\C:\Users\zouhair\works\Desktop\test\AwesomeProject2\ios\AwesomeProject2'

### ISSUE THREAD

**Issue by zouhairjabiri** [react-static/react-static#1462]
### Reporting a bug?

  Provide as much information as you can to reproduce the issue.
  **If the issue is not reproducible, it can't be fixed!**

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```

YOUR ENV INFO HERE FOR DEBUGGING

```

of course include any other package versions here if relevant. 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  ...
2.  ...
3.  ...

**Comment by SleeplessByte** [comment]
Hi there. You have not filled in the issue template, thus we can not help you resolve this.
