### ISSUE TITLE
[Bug] REACT_STATIC_ASSETS_PATH undefined when running incremental build

### ISSUE THREAD

**Issue by simoncorompt** [react-static/react-static#1476]
### Reporting a bug?

Hey, it seems that when running an incremental build with : `yarn export --incremental`, the exported templates don't use the `config.paths.assets` specified in the `static.config.js` file to generate script tags in the exported HTML.

### Environment

```

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 895.66 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  npmPackages:
    @reach/router: ^1.2.1 => 1.3.3 
    eslint: ^6.1.0 => 6.8.0 
    eslint-config-prettier: ^6.0.0 => 6.11.0 
    eslint-config-react-tools: 1.x.x => 1.1.7 
    eslint-config-standard: ^12.0.0 => 12.0.0 
    eslint-plugin-import: ^2.16.0 => 2.20.2 
    eslint-plugin-node: ^8.0.1 => 8.0.1 
    eslint-plugin-prettier: ^3.1.0 => 3.1.3 
    eslint-plugin-promise: ^4.0.1 => 4.2.1 
    eslint-plugin-standard: ^4.0.0 => 4.0.1 
    extract-css-chunks-webpack-plugin: ^4.3.2 => 4.7.5 
    mv: ^2.1.1 => 2.1.1 
    node-sass: ^4.11.0 => 4.14.1 
    postcss-flexbugs-fixes: ^4.1.0 => 4.2.1 
    postcss-loader: ^3.0.0 => 3.0.0 
    prettier: ^1.18.2 => 1.19.1 
    prop-types: ^15.7.2 => 15.7.2 
    react: ^16.8.1 => 16.13.1 
    react-dom: ^16.8.1 => 16.13.1 
    react-static: 7.2.2 => 7.2.2 
    react-static-plugin-reach-router: ^7.0.10 => 7.4.0 
    react-static-plugin-sitemap: ^7.0.10 => 7.4.0 
    recursive-copy: ^2.0.10 => 2.0.10 
    regenerator-runtime: ^0.13.2 => 0.13.5 
    sass-loader: ^7.1.0 => 7.3.1 
    sass-resources-loader: ^2.0.0 => 2.0.3 
    serve: 11.0.0 => 11.0.0 
    yarn: ^1.16.0 => 1.22.4 

```

#### 1. Set a custom asset path in your config

```
{
  assetsPath: 'static',
  paths: {
    assets: 'static'
  }
}
```

In my case I need all static assets to be served from a `/static` directory under dist. It is working fine on a full bundle + export.

#### 2.  Run a full build first to bundle the js and generate artefacts for future incremental build.

`yarn build`

#### 3. Run an incremental build

`yarn export --incremental`

=> On first load, all incrementally generated pages will have broken assets because the script tags omit the custom asset directory from the config. When navigating away and coming back though the problem is fixed.

Here are the generated script tags after an incremental build : 

```
<script defer="" type="text/javascript" src="/templates/styles.7bf84341.js"></script>
<script defer="" type="text/javascript" src="/templates/vendors.66a979bb.js"></script>
<script defer="" type="text/javascript" src="/main.34bb2894.js"></script>
```

It should be :

```
<script defer="" type="text/javascript" src="http://localhost:3000/static/templates/styles.7bf84341.js"></script>
<script defer="" type="text/javascript" src="http://localhost:3000/static/templates/vendors.66a979bb.js"></script>
<script defer="" type="text/javascript" src="http://localhost:3000/static/main.34bb2894.js"></script>
```

I tracked down the problem to the `makeBodyWithMeta` function in `react-static/src/static/components/BodyWithMeta.js` which generates the srcs using `process.env.REACT_STATIC_ASSETS_PATH`. When running a full build it is correctly set-up but when exporting with --incremental, it is undefined.

For now I could set the var myself before running an incremental build, but I think it should definitely be automatic?

### Expected Behavior

Incrementally generated pages should have correct static assets paths without having to rebundle the app.

**Comment by bastienrobert** [comment]
Maybe we should set `process.env.REACT_STATIC_ASSETS_PATH` [here](https://github.com/react-static/react-static/blob/2ddfc029492b105468167efb33adab33a3b8e824/packages/react-static/src/commands/export.js#L19)
