### ISSUE TITLE
[Docs] Documentation on how to port existing apps from create-react-app

### ISSUE THREAD

**Issue by tetrachrome** [react-static/react-static#1492]
Hi, I'm one of the many developers who have an existing project created with create-react-app and would like to port over and adopt react-static. However, short of great documentation that I was able to find on how to do this, I'm at a lost on how to proceed.

I understand that it is fairly easy to start a new project from scratch with the react-static CLI. However, this is not an option for existing apps, and the current documentation do not paint a whole picture on how to port existing projects to adopt the features of react-static.

Perhaps I'm just not seeing it, but after reading through all the current documentations + Googling for a while, I see many face the same conundrum.

Thanks!

**Comment by SleeplessByte** [comment]
@tetrachrome Is there a reason you closed this?

**Comment by mukarramali** [comment]
Why was this cloed? This is very important to be in the documentation.
