### ISSUE TITLE
[Bug] Does not work with preact on production

### ISSUE THREAD

**Issue by rosskhanas** [react-static/react-static#1497]
### Reporting a bug?

![image](https://user-images.githubusercontent.com/10609041/91981135-0ae23a00-ed31-11ea-97d5-e72b62e3d676.png)

After investigation, I found that https://github.com/react-static/react-static/blob/87ea29379f4a8a73612db198c0bc5c021ba60366/packages/react-static/src/bootstrapApp.js#L19 line crashes.

### Environment

Run and copy the result of:

```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 2.27 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 85.0.4183.83
    Safari: 13.1.1
  npmPackages:
    react-static: ^7.4.2 => 7.4.2
```

### Steps to Reproduce the problem

1.  Add preact aliases
2.  `yarn react-static build`
3. `yarn serve ./dist -p 3000`
4. Open `http://localhost:3000/` and the browser console.

### Expected Behavior

No JS crash

**Comment by SleeplessByte** [comment]
Hi there. On `master` there is a [specific change](https://github.com/react-static/react-static/blob/f93fa5861c362316ea49f643cf1c95da7c9f1da8/CHANGELOG.md) for `preact`, referring to https://github.com/react-static/react-static/pull/1486. I think @tbgse has gotten it to work.

**Comment by tbgse** [comment]
Are you using the `react-static-plugin-preact` and have followed the instructions in the [readme](https://github.com/react-static/react-static/tree/master/packages/react-static-plugin-preact)?

**Comment by rosskhanas** [comment]
@tbgse with `react-static-plugin-preact` build completely fails, I guess it is because it uses preact 8 and it does not support hooks. That is why I tried to add preact 10 manually + applied changes manually to the `node.api.js` + removed `AppContainer` usage.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/10609041/92008589-08dba380-ed50-11ea-8a05-a2a3c937d57d.png">

**Comment by tbgse** [comment]
I just tried this too and i'm getting the same error, i know their suspense support is still experimental, somewhere there must be an incompatibility between how Suspense works in React vs Preact that is causing issues here. I'll try to look into it a bit more over the weekend.

**Comment by SleeplessByte** [comment]
It's probably because `preact`'s default export isn't the same shape of binding as `react`.

What we can do is this:

- extract the "custom suspense" to a different file
- import that file here, but in the `preact-plugin` stub out that import
- add a note in `readme.md` that you are _responsible_ for "removing" `Suspense` in production when using `preact`.

I currently don't have the cycles to do this myself, but the change would be a few lines. (hint hint, maybe one of you can do it :heart:)

---

To clarify what we're doing in `bootstrapApp`:

1. Create a new `Suspense` that only works when NOT using SSR (because Suspense doesn't work when pre-rendering)
2. Replace the `Suspense` that is used inside your app and libraries to be this new `Suspense`
3. Rejoice.

That's really all it's doing.

**Alternatives**:

Implement something like this:

- https://github.com/overlookmotel/react-async-ssr
- https://github.com/formidablelabs/react-ssr-prepass/blob/master/README.md

But I'd rather not.

**Comment by bastienrobert** [comment]
I'm still having issues with @SleeplessByte [advices](https://github.com/react-static/react-static/issues/1497#issuecomment-686178587) and @rosskhanas [solution](https://github.com/react-static/react-static/pull/1500#issuecomment-695188876) with patch. 

<details><summary>Here is my patch file for react-static 7.3.0</summary>
<p>

```
diff --git a/node_modules/react-static/src/Suspense.js b/node_modules/react-static/src/Suspense.js
new file mode 100644
index 0000000..c68f7c3
--- /dev/null
+++ b/node_modules/react-static/src/Suspense.js
@@ -0,0 +1,13 @@
+import * as React from 'react'
+
+function Suspense({ key, children, ...rest }) {
+  return typeof document !== 'undefined' ? (
+    <React.Suspense key={key} {...rest}>
+      {children}
+    </React.Suspense>
+  ) : (
+    <React.Fragment key={key}>{children}</React.Fragment>
+  )
+}
+
+export default Suspense;
\ No newline at end of file
diff --git a/node_modules/react-static/src/bootstrapApp.js b/node_modules/react-static/src/bootstrapApp.js
index 7e1ccec..a08894f 100644
--- a/node_modules/react-static/src/bootstrapApp.js
+++ b/node_modules/react-static/src/bootstrapApp.js
@@ -1,22 +1,14 @@
 /* eslint-disable import/no-dynamic-require */
 import * as React from 'react'
 import { staticInfoContext } from './browser/hooks/useStaticInfo'
-
-const OriginalSuspense = React.Suspense
-
-function Suspense({ key, children, ...rest }) {
-  return typeof document !== 'undefined' ? (
-    <OriginalSuspense key={key} {...rest}>
-      {children}
-    </OriginalSuspense>
-  ) : (
-    <React.Fragment key={key}>{children}</React.Fragment>
-  )
-}
+// import Suspense from './Suspense'
 
 // Override the suspense module to be our own
-React.Suspense = Suspense
-React.default.Suspense = Suspense
+// This is expected to break when using preact
+// In order to make it work with preact 10, use `patch-package` to remove those 2 lines
+// Reference: https://github.com/react-static/react-static/pull/1500
+// React.Suspense = Suspense
+// React.default.Suspense = Suspense
 
 const App = require(`${process.env.REACT_STATIC_ENTRY_PATH}`).default
```

</p>
</details>

The error is still the same on build. Here's a repro : https://github.com/bastienrobert/react-static-preact-repro.

**Comment by rosskhanas** [comment]
@bastienrobert I just tried to run your repo and it successfully builds.

**Comment by bastienrobert** [comment]
It successfully builds but I'm still having this error in the JS console :/

**Comment by SleeplessByte** [comment]
@bastienrobert do you manually import Suspense somewhere?

**Comment by rosskhanas** [comment]
@bastienrobert I guess the problem is that on production build `lib` folder is used. Therefore, you need to apply the patch to that folder.

**Comment by huygn** [comment]
> @bastienrobert I guess the problem is that on production build `lib` folder is used. Therefore, you need to apply the patch to that folder.

👍 I was able to make it work on prod by applying patch to `lib` dir, I also had to remove `<Suspense />` to make it work with static export, thus a custom Suspense component with a simple `document` check should work fine in both dev & prod mode.

**Comment by SleeplessByte** [comment]
@huygn can we get that into react-static?
