### ISSUE TITLE
ChunkLoadError and `basePath` not being recognized

### ISSUE THREAD

**Issue by AJTJ** [react-static/react-static#1499]
There are several bugs and they may or may not be related:
1. For some reason I'm getting a lot of `Uncaught (in promise) ChunkLoadError: Loading chunk 0 failed.` type of errors with my build. These could be webpack related (though I'm not sure how to approach it), but I'm not entirely sure. It's bizarre, since the website begins to load correctly at first, but then something happens to cause an error.

2. Also, when I click through any link it seems that react-static does not seem to add the `basePath` onto my `siteRoot` that I've declared in my `static.config.js`, 
i.e. instead of a link directing to:
`https://yukon-literacy-coalition.github.io/ylc_website/about`
it will instead direct to:
`https://yukon-literacy-coalition.github.io/about`

Please see the (broken) version of my site at https://yukon-literacy-coalition.github.io/ylc_website/
There are lots of errors in the console.
The related repo is here: https://github.com/Yukon-Literacy-Coalition/ylc_website/tree/gh-pages
And the parent repo (not just the gh-pages/build repo) is here: https://github.com/Yukon-Literacy-Coalition/ylc_website

### Reporting a bug?

As far as I know, yes.

### Environment
```

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 85.43 MB / 8.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 76.0.1
    Firefox Developer Edition: 65.0
    Safari: 13.1.2
  npmPackages:
    react: ^16.13.1 => 16.13.1
    react-dom: ^16.13.1 => 16.13.1
    react-elastic-carousel: ^0.6.6 => 0.6.6
    react-markdown: ^4.3.1 => 4.3.1
    react-moment: ^0.9.7 => 0.9.7
    react-multi-carousel: ^2.5.5 => 2.5.5
    react-router: ^5.2.0 => 5.2.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-scroll: ^1.7.16 => 1.7.16
    react-static: ^7.2.0 => 7.4.0
    react-static-plugin-emotion: ^7.2.2 => 7.2.2
    react-static-plugin-favicons: ^2.0.0 => 2.0.0
    react-static-plugin-reach-router: ^7.2.0 => 7.4.0
    react-static-plugin-react-router: ^7.4.0 => 7.4.0
    react-static-plugin-sitemap: ^7.2.0 => 7.4.0
    react-static-plugin-source-filesystem: ^7.2.0 => 7.4.0
    react-static-plugin-styled-components: ^7.3.0 => 7.3.0
    react-text-loop: ^2.3.0 => 2.3.0
  npmGlobalPackages:
    react-static: 7.4.0

```

It should be noted that I'm also `NetlifyCMS` as a static route (though I don't imagine that should be an issue.

### Steps to Reproduce the problem

1.  You would need to build the project from: https://github.com/Yukon-Literacy-Coalition/ylc_website and then put it on a github page.
2. It seems easier to simply read the console on my current github page at https://yukon-literacy-coalition.github.io/ylc_website/

### Expected Behavior

I'm imagining the website should just load.

### Reproducible Demo

Please see (broken) site and the console error statements at: https://yukon-literacy-coalition.github.io/ylc_website/
The related repo is here: https://github.com/Yukon-Literacy-Coalition/ylc_website/tree/gh-pages
And the parent repo (not just the gh-pages/build repo) is here: https://github.com/Yukon-Literacy-Coalition/ylc_website

**Comment by SleeplessByte** [comment]
Is this not the same as https://github.com/react-static/react-static/issues/1474 ?

**Comment by AJTJ** [comment]
Thanks @SleeplessByte this solved _one_ of the bugs, but not the other. I'm still getting tons of `Chunkload Errors`, and thoughts on this?

For anyone else, here is a solution for adding the basePath to all your routes as per the https://github.com/react-static/react-static/tree/master/docs/plugins documentation: 
```
...
const githubBasePath = "/ylc_website";

export default {
  plugins: [
    "react-static-plugin-react-router",
    {
      RouterProps: {
        basename: githubBasePath,
      },
    },
    "react-static-plugin-emotion",
    "react-static-plugin-styled-components",
  ],
  siteRoot: "https://yukon-literacy-coalition.github.io",
  basePath: githubBasePath,
  ...
```

unfortunately, the addition of the  only seems

**Comment by SleeplessByte** [comment]
Chunkload errors are usually webserver configuration or build failures (that didn't cause the build to halt but failed to create the file). 

If it were a structural issue with react-static, we would have heard many more people about it.

There might be an issue out there with what you're experiencing -- :)

**Comment by AJTJ** [comment]
@SleeplessByte Thanks! I believe it was a routing issue and I sorted it out, but am now getting other issues, I will open a different bug report for simplicity.
