### ISSUE TITLE
[Docs] dynamic route guides do not use addPrefetchExcludes

### ISSUE THREAD

**Issue by Zauberfisch** [react-static/react-static#1513]
There are 3 "examples" for dynamic (client side) routing, 2 in the docs (guides) and one is a template.

The 2 guides in the docs are technically working, but they do not use `addPrefetchExcludes`.

- [dynamic-routes-reach-router.md](https://github.com/react-static/react-static/blob/85c232bb3d357e15b7efd04291ad43b4af2e976b/docs/guides/dynamic-routes-reach-router.md)
- [docs/guides/dynamic-routes-react-router.md](https://github.com/react-static/react-static/blob/85c232bb3d357e15b7efd04291ad43b4af2e976b/docs/guides/dynamic-routes-react-router.md)

however, in the [basic teamplte](https://github.com/react-static/react-static/blob/85c232bb3d357e15b7efd04291ad43b4af2e976b/packages/react-static/templates/basic/src/App.js#L10) which also includes dynamic routes via reach router, there is a line

```
// Any routes that start with 'dynamic' will be treated as non-static routes
addPrefetchExcludes(['dynamic'])
```

From what I can see, this is still relevant, because I see 404 requests to dynamic/routeInfo.json.

Is there a reason why those were left out in the guides?

**Comment by SleeplessByte** [comment]
I think it's oversight!

Links that won't have a generated `routeinfo.json` should have `addPrefetchExcludes`, so I think these are missing from the docs. Thanks!
