### ISSUE TITLE
[Bug] HEAD component from react-static is causing a re-render(flash)

### ISSUE THREAD

**Issue by alqamabinsadiq** [react-static/react-static#1544]
## Bug
I am using the Head component from react-static, which is basically react-helmet and it is causing a rerender flash whenever I refresh the browser. It happens when you visit the link for the first time or when you do a hard refresh.

I removed it and used the Document option mentioned in the configuration and it works fine but using the Head component from react-static causes a rerender.

## Environment
`"react-static": "^7.2.0",`

**Comment by SleeplessByte** [comment]
Is this in production or in development?

**Comment by alqamabinsadiq** [comment]
production.

**Comment by SleeplessByte** [comment]
This site: https://agingrelative.com/senior-housing uses `Head` from react-static without the re-render flash; but perhaps we can figure out why it happens for you. 

If there's a way you can make a minimal reproducible example (e.g. use the blank template), that'd be awesome.

**Comment by alqamabinsadiq** [comment]
@SleeplessByte I found out the issue I think it was because of my implementation. I am using google fonts link which is taking a bit longer to load I think the flash was because of that I moved out my google fonts and another link tag and now the flash is gone.
