### ISSUE TITLE
[Bug] fix high severity vulnerability by updating axios to >=0.21.1

### ISSUE THREAD

**Issue by GeorgeDRPG** [react-static/react-static#1554]
### Version

react-static 7.4.2 

### Steps to Reproduce the problem

`npm audit` in a react-static project.

### Vulnerability info

High          │ Server-Side Request Forgery
Package       │ axios
Patched in    │ >=0.21.1
Dependency of │ react-static
Path          │ react-static > axios
More info     │ https://npmjs.com/advisories/1594

**Comment by SleeplessByte** [comment]
This is not an issue for react static as the attack surface doesn't apply for the use of axios in react static.

We'll still upgrade, but it's not a high priority.
