### ISSUE TITLE
[Bug] Myriad different errors trying to use react-router

### ISSUE THREAD

**Issue by jkatofsky** [react-static/react-static#1555]
### My setup:
```
  System:
    OS: macOS 11.2
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Memory: 1.04 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  npmPackages:
    babel-eslint: ^10.0.2 => 10.1.0 
    eslint: ^6.1.0 => 6.8.0 
    eslint-config-react-app: ^5.0.1 => 5.2.1 
    eslint-config-react-tools: ^1.1.7 => 1.1.7 
    eslint-plugin-flowtype: ^4.2.0 => 4.7.0 
    eslint-plugin-import: ^2.18.2 => 2.22.1 
    eslint-plugin-jsx-a11y: ^6.2.3 => 6.4.1 
    eslint-plugin-react: ^7.14.3 => 7.21.5 
    react: ^16.9.0 => 16.14.0 
    react-accessible-accordion: ^3.3.3 => 3.3.3 
    react-burger-menu: ^3.0.2 => 3.0.2 
    react-dom: ^16.9.0 => 16.14.0 
    react-loading-skeleton: ^2.1.1 => 2.1.1 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-static: ^7.2.0 => 7.4.2 
    react-static-plugin-react-router: ^7.4.2 => 7.4.2 
    react-static-plugin-source-filesystem: ^7.2.0 => 7.4.2 
    serve: ^11.1.0 => 11.3.2 
    webpack-cli: ^4.3.1 => 4.3.1 
    window-or-global: ^1.0.1 => 1.0.1
```

Here are the plugins of my `static.config.js`:
```javascript
plugins: [
        [
            require.resolve('react-static-plugin-source-filesystem'),
            {
                location: path.resolve('./src/pages'),
            },
        ],
        require.resolve('react-static-plugin-react-router'),
    ]
```

This is the `render()` of my `App.js`
```JSX
render() {
        return (
            <Root>
                <Navbar />
                <div className="page-content">
                    <React.Suspense fallback={<Loading />}>
                        <Switch>
                            <Route render={() => <Routes />} />
                        </Switch>
                    </React.Suspense>
                </div>
                <Footer />
            </Root>
        )
}
```

This is very closely mirrored from the [react-router plugin guide](https://github.com/react-static/react-static/blob/master/docs/guides/dynamic-routes-react-router.md). There are [NavLink](https://reactrouter.com/web/api/NavLink)s in my `Navbar` component, but I thought this was no issue because react-static's `Root` [should inject](https://github.com/react-static/react-static/blob/master/docs/api.md#routes) a `Router` component.

### The problem

Everything works fine when I run `npm start`. However, when I run `react-static build --staging --debug`, I see that the following error is occurring on the attempted static exports of _every page_ in my project:

```
Error: Failed exporting HTML for URL faq (__react_static_root__/src/pages/faq.js): Invariant failed:   You should not use <NavLink> outside a <Router>
```

To fix this, I've tried wrapping all children of `Root` in a [BrowserRouter](https://reactrouter.com/web/api/BrowserRouter), but that simply causes a new error:
```
Error: Failed exporting HTML for URL faq (__react_static_root__/src/pages/faq.js): Invariant failed:   Browser history needs a DOM
```

Any insight on how I can fix this? It seems to me like `Root` is not truly wrapping the app with a router.

**Comment by jkatofsky** [comment]
## UPDATE:
I had not come across [withRouteData](https://github.com/react-static/react-static/blob/master/docs/api.md#useroutedata) when I wrote the below. I fixed the below errors when I wrapped `Navbar` with `withRouteData` before exporting it. However, now I have this error: `ReactDOMServer does not yet support Suspense.` How do I approach this? I couldn't figure out a solution based on [this issue](https://github.com/react-static/react-static/issues/1501) that references the same error.

**Comment by SleeplessByte** [comment]
https://github.com/react-static/react-static/issues/1501#issuecomment-689818720 is really the same issue you're describing. You're trying to use the route data _outside_ the router context.

Switching to _reach router_ and using the pattern I describe there is probably the *easiest* way forward.
