### ISSUE TITLE
[Bug] react-static create typescript sample loads incorrect html when running serve

### ISSUE THREAD

**Issue by shahrouzz** [react-static/react-static#1559]
### Environment

```

react-static@7.4.2

```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  run ```react-static create```
2.  choose the 'typescript' sample
3.  run ```yarn build && yarn serve```
4. open http://localhost:3000/about in url field in browser

### Expected Behavior

It is expected that dist/about/index.html to be served as initial file to browser.

instead: dist/index.html is sent and then then rehydrated to the 'about' page.

This only happens in the 'typescript' sample. The 'basic' sample works as expected.

**Comment by shahrouzz** [comment]
The serve script for the typescript sample and the basic sample differ.

The problem I had was solved by removing the "-s" flag in the serve script in package.json.

script should be: ```"serve": "serve dist -p 3000"``` and not ```"serve": "serve dist -p 3000 -s"```

**Comment by SleeplessByte** [comment]
We take PRs!
