### ISSUE TITLE
[Bug] Out of Memory with basic template

### ISSUE THREAD

**Issue by andreme** [react-static/react-static#1564]
### Reporting a bug?

I've created a new site from the basic template. After doing a build and serve, opening the site locally creates an Out of memory error. As far as I can see it's stuck in hydrating.
Commenting out `React.Suspense` in App.js fixes the issue.

This also happens when the react(-static) packages are updated to the latest versions.

### Environment
react-static cli 7.5.0

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (24) x64 AMD Ryzen 9 3900 12-Core Processor
    Memory: 44.57 GB / 63.90 GB
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.19041.423.0)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    react: ^16.9.0 => 16.14.0
    react-dom: ^16.9.0 => 16.14.0
    react-static: ^7.2.0 => 7.5.0
    react-static-plugin-reach-router: ^7.2.0 => 7.5.0
    react-static-plugin-sitemap: ^7.2.0 => 7.5.0
    react-static-plugin-source-filesystem: ^7.2.0 => 7.5.0

```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**
basic template:

1. yarn build
2. yarn serve
3. Open in chrome
4. Browser tab crashes after a while

**Comment by andreme** [comment]
Just as an FYI, when `React.Suspense` is commented out, I get an error in dev mode

**Comment by SleeplessByte** [comment]
Yes. React.Suspense is used to hook in the route information. It should definitely not cause an OOM error. Might be something looping 🤷🏽‍♂️

**Comment by dictions** [comment]
@andreme just ran into this. If you're looking for a quick fix, revert to `7.4.2`

**Comment by andreme** [comment]
I have the problem with 7.4.2 as well

**Comment by SleeplessByte** [comment]
I can confirm now that `yarn build` produces a build that has valid HTML, but some infinitely looping JavaScript. Looking for a fix.

**Comment by codejunkienick** [comment]
This happened to me when I set assetsPath different from default one.

**Comment by graniczny** [comment]
Same here

**Comment by SleeplessByte** [comment]
(Please refrain from "me to" commentary as this bug has been confirmed. Now "all we need" is a solution 😄 )

**Comment by graniczny** [comment]
@SleeplessByte  any ideas for workaround? Tried using 7.4.2 and 7.2.3 versions, also with lower node versions (11.x, 14.x) but still getting error 😞  (I'm quite desperate 🙏 )

**Comment by TriDotS** [comment]
Took me some time but I have a workaround for the basic template to get a prod build

```
ckunze@Akis-MacBook-Pro test-with-rollback % react-static -v
7.5.1
```
```
  System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 6.07 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Safari: 14.0.3
  npmPackages:
    react: ^16.14.0 => 16.14.0 
    react-dom: ^16.14.0 => 16.14.0 
    react-hot-loader: ^4.13.0 => 4.13.0 
    react-static: 7.4.2 => 7.4.2 
    react-static-plugin-reach-router: ^7.5.0 => 7.5.1 
    react-static-plugin-sitemap: ^7.5.0 => 7.5.1 
    react-static-plugin-source-filesystem: ^7.5.0 => 7.5.1 
```

The trick here is to remove the ```^``` from version ```^7.5.1```and rollback to ```7.4.2``` 
you can keep the plugins versions as they are 

My working package.json
```
{
  "name": "react-static-example-basic",
  "private": true,
  "scripts": {
    "start": "react-static start",
    "stage": "react-static build --staging",
    "build": "react-static build",
    "analyze": "react-static build --analyze",
    "serve": "serve dist -p 3000"
  },
  "dependencies": {
    "@reach/router": "^1.3.4",
    "axios": "^0.21.1",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-hot-loader": "^4.13.0",
    "react-static": "7.4.2",
    "react-static-plugin-reach-router": "^7.5.0",
    "react-static-plugin-sitemap": "^7.5.0",
    "react-static-plugin-source-filesystem": "^7.5.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^7.19.0",
    "eslint-config-react-app": "^6.0.0",
    "eslint-config-react-tools": "^1.1.7",
    "eslint-plugin-flowtype": "^5.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "serve": "^11.3.2"
  }
}
```

**Comment by SleeplessByte** [comment]
Sweet. Thank you @TriDotS .

If you do NOT remove the caret (`^`), semver will kick-in and actually resolve to `7.5.1`, which is why you need to remove the `^`.

**Comment by TriDotS** [comment]
I forgot to mention that I also removed ```node_modules```and  ```.lock```file and do a clean ```yarn install```

**Comment by SleeplessByte** [comment]
Yeah, I actually do have a good idea where it was introduced, just not *why* it was.

**Comment by kespindler** [comment]
Not sure if this is helpful, but I'm encountering this and getting some odd behavior.

I get the infinite loop leading to crash with both basic and typescript templates. I also discovered that commenting out `React.Suspense` fixes the issue. However, doing that causes the dev server to serve an error on every page.

```
An internal error occured!

Error: RoutesInner suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
```

However, if I then edit a file, causing the dev server to reload, the issue goes away and the entire site loads fine. If I restart the dev server, it again errors until I modify a file to cause it to reload.

@TriDotS 's solution of downgrading to `7.4.2` worked for me.

**Comment by SleeplessByte** [comment]
The fix has NOT yet been released on NPM, but you can grab it using https://github.com/react-static/react-static/commit/f8dc77c99af961245ab1a01e6dce54a3ca647ce3 in your package.json

**Comment by kespindler** [comment]
@SleeplessByte Thanks for publishing this fix. However, I'm still encountering issues. I'd like to help debug, but I'm out of my depth on babel internals and lazy loading react components.

I created a new project from the `typescript` project using the CLI tool (version 7.5.1), and then I updated its `package.json` to have the line `    "react-static": "https://github.com/react-static/react-static.git#f8dc77c",`. 

I ran `npm install` to refresh packages, and then `npm run build` fails with this error:

```
Trace: Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /Users/kurt/work/foobar/static.config.js
- /usr/local/lib/node_modules/react-static/lib/static/getConfig.js
- /usr/local/lib/node_modules/react-static/lib/commands/bundle.js
- /usr/local/lib/node_modules/react-static/lib/commands/build.js
- /usr/local/lib/node_modules/react-static/bin/react-static
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.call (internal/modules/cjs/loader.js:964:19)
    at Module.require (/usr/local/lib/node_modules/react-static/src/utils/binHelper.js:62:26)
```

Would it be helpful to keep this issue in thread or create a separate issue?

For other users encountering this problem, keeping `package.json` with `    "react-static": "7.4.2",` still avoids this issue for me.

**Comment by SleeplessByte** [comment]
Ah sorry. I should have clarified this. Unfortunately loading from git directly won't work because the git repo only has src files.

What you can do is:
- git clone this (it will be at head, which is that commit, yay)
- yarn
- yarn build
- yarn link

Now go to your project

- yarn link react-static

Basically you want to tell yarn to use the local folder.

**Comment by kespindler** [comment]
> Ah sorry. I should have clarified this. Unfortunately loading from git directly won't work because the git repo only has src files.
> 
> What you can do is:
> 
> * git clone this (it will be at head, which is that commit, yay)
> * yarn
> * yarn build
> * yarn link
> 
> Now go to your project
> 
> * yarn link react-static
> 
> Basically you want to tell yarn to use the local folder.

Got it! Thank you for the help.

Out of curiosity, why does that commit fix the issue? It looks like all it does is bind the same component to a file-level const.

**Comment by SleeplessByte** [comment]
https://github.com/react-static/react-static/blob/3793552f6e9ff921cb8480768a7438e386f6194b/packages/react-static/src/bootstrapApp.js#L10-L11 Here we replace regular suspense with the new "will work even in SSR" suspense, but because the import is a live binding, it actually replaces the `Suspense` that's rendered.

**Comment by SleeplessByte** [comment]
Released as 7.5.3

**Comment by kespindler** [comment]
It does! Thank you for fixing this issue!

**Comment by SleeplessByte** [comment]
@andreme thank you for the PR! :D
