### ISSUE TITLE
routeInfo hook

### ISSUE THREAD

**Issue by andreme** [react-static/react-static#1566]
**Is your feature request related to a problem? Please describe.**
I'm trying to develop a solution to transform images (like https://github.com/react-static/react-static/issues/1130 ).
But I would like to make use of the existing multithreading and convert them in the worker process.
For that I need to write some data back into into the routeInfo, and as far as I can see it needs to be done before it is used anywhere else: https://github.com/react-static/react-static/blob/58cf1c6a3b2847944b588589b8abccc3a2f083c9/packages/react-static/src/static/exportRoute.js#L107

**Describe the solution you'd like**
If I code a PR for that, will it be accepted?

**Comment by SleeplessByte** [comment]
It was merged!

Released as 7.5.3
