### ISSUE TITLE
[Bug] MDX plugin doesn't include built fm-loader module

### ISSUE THREAD

**Issue by docrinehart** [react-static/react-static#1574]
Tried swapping from my local mdx plugin build, but still needed to run "npm run build" from "\node_modules\react-static-plugin-mdx" to generate the fm-loader module.

I'm assuming that maybe a build step for the plugin packages might be getting missed?

**Comment by SleeplessByte** [comment]
Weird. I checked out the npm files and the file was missing. The build step was there, and when I just build as usual, it also built correctly.

I've moved the `fm-loader` into a folder (to be certain) and re-released for you https://www.npmjs.com/package/react-static-plugin-mdx/v/7.5.4.

If that resolves it, please close this issue.

**Comment by docrinehart** [comment]
Yeah, the package came down working that time. Thanks for the quick turnaround, I was just going to fall back on my local vendor copy again. =P

**Comment by SleeplessByte** [comment]
You were in luck as I had some time this weekend to release a fix for some other stuff ☺️😃
