### ISSUE TITLE
[Bug] react-static package > 7.4.2 causes Out Of Memory issues with production build

### ISSUE THREAD

**Issue by docrinehart** [react-static/react-static#1578]
After updating to the latest version of all my relevant react-static packages, I can preview the site just fine while running in development, but the prod build served remote or locally causes the browser to fail with Out Of Memory. I haven't been able to get a good profile to see what's causing the heap to grow so quickly.

Adding this ticket for tracking -- Right now I'm incrementally setting each package version explicitly to try and find the culprit. I'll update the ticket with additional details once I know more.

```
node v14.15.0
npm v6.14.8

"react-hot-loader": "^4.13.0",
"react-static": "7.4.2", // 7.4.2 works, 7.5.0 causes Out of Memory when trying to navigate to site
"react-static-plugin-css-modules": "7.2.2",
"react-static-plugin-mdx": "7.5.4",
"react-static-plugin-reach-router": "7.5.3",
"react-static-plugin-sass": "7.3.0",
"react-static-plugin-sitemap": "7.5.3",
"react-static-plugin-source-filesystem": "7.5.3"
```

UPDATE: I've narrowed it down to the transition of the main react-static package from 7.4.2 to 7.5.0 which requires the addition of react-hot-loader. I wouldn't expect react-hot-loader to cause issues with prod, but I tried explicitly changing the react-hot-loader version without success. Leaving the latest version in my own deps and dropping to react-static v7.4.2 allows a successful production deployment, so I'm convinced that it must be something else that's changed within react-static. Continuing to dig...

**Comment by docrinehart** [comment]
Just found this related issue: https://github.com/react-static/react-static/issues/1564

**Comment by SleeplessByte** [comment]
Can you try with 7.5.3? There was a bug in 7.5.0, 7.5.1 and 7.5.2 that caused this in production only. Actually was not related to react-hot-loader, but to the way Suspense is implemented in react-static.

**Comment by docrinehart** [comment]
I saw that in #1564. Odd, I thought I had been on 7.5.3...  Setting explicitly worked. Taking a closer look at the previous build logs, I think npm was stuck on 7.5.1. Working now. Thanks!

![image](https://user-images.githubusercontent.com/5891405/109396032-995d0000-78fd-11eb-8d2a-f143f34090ea.png)

**Comment by SleeplessByte** [comment]
I don't know if you have `react-static` installed globally, but that can cause this :)
