### ISSUE TITLE
[Bug] Animated routes not working as expected 

### ISSUE THREAD

**Issue by dictions** [react-static/react-static#1584]
### Reporting a bug?

I'm having issues with the animated routes example. I've tried with the `react-spring` example in the guides, `framer-motion` as well as `react-transition-group` and I get all the same behavior:

When using a "Switch" style transition, or `exitBeforeEnter` in `framer-motion`, the contents of the `<Routes/>` component changes to the new route without allowing the transition to complete it's exit. You can use the animated routes guide as the baseline.

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```

System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 22.32 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/dev/cah-frontend/packages/web/node_modules/.bin/yarn
    npm: 7.4.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
    react-hot-loader: ^4.13.0 => 4.13.0 
    react-spring: ^8.0.27 => 8.0.27 
    react-static: 7.4.2 => 7.4.2 
    react-static-plugin-sass: ^7.3.0 => 7.3.0 
    react-static-plugin-sitemap: ^7.2.0 => 7.5.0 
    react-static-plugin-typescript: ^7.5.3 => 7.5.3 
  npmGlobalPackages:
    react-static: 7.4.2
```

of course include any other package versions here if relevant. 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

When using a "Switch" style transition, or `exitBeforeEnter` in `framer-motion`, the contents of the `<Routes/>` component changes to the new route without allowing the transition to complete it's exit. Click a transition, and the entire `<Routes/>` component is now the new route. 

### Expected Behavior

With unique `key` properties set, I expect the previous router to animate out before the new one animates in.

### Reproducible Demo

I'll work on trying to get a demo.

**Edit here's the demo:
https://github.com/dictions/react-static-router-issue-1584

**Comment by SleeplessByte** [comment]
Your "steps to reproduce" don't really explain how to reproduce this. 

Have you followed https://github.com/react-static/react-static/blob/master/docs/guides/animated-routes.md?

**Comment by dictions** [comment]
@SleeplessByte totally! 

So I did follow that example, and this morning I've realized it's **only** with routes that use `useRouteData`. That seems to be updating the child _before_ the parent route can finish the transition.

https://github.com/dictions/react-static-router-issue-1584

Note the difference between clicking home/about vs. the generated routes.

**Comment by dictions** [comment]
@SleeplessByte Here's an example screencapture:

https://user-images.githubusercontent.com/4307278/110663870-e01be700-8194-11eb-9c3f-0c1e2f9fc5b9.mov

**Comment by SleeplessByte** [comment]
That's not really what's happening, but armed with this data it probably fixable. The animations/transition groups are not blocking updates to their children / hooks / context (which is logical). 

This can be solved various ways:

## Use route data on mount instead of use latest

Instead of relying on `useRouteData` to always give the up-to-date data, only use the first invocation:

```js
function useRouteDataOnMount() {
  const latestRouteData = useRouteData();
  
  // Reference to the route data on mount. Initialise it with
  // the value available on mount
  const mountedRouteData = useRef(latestRouteData);
  
  // Store the route data if it wasn't available on mount, but
  // it is now.
  if (!mountedRouteData.current) {
    mountedRouteData.current = latestRouteData
  }
  
  return mountedRouteData.current 
}

## Force the `useRouteData` to have a certain route

Normally, `useRouteData` will use the location under the hood, provided by a context. This can definitely be optimised on the react-static side, but I personally don't have the bandwidth or funding to do that. A quick fix may be to _force_ a route. I haven't tested this code, but the idea is the same: store the `routePath` in a stable reference on mount, so that it can never update.

```tsx
const element = getComponentForPath(routePath)
return (
  <Transition
    native
    items={routePath}
    from={{ transform: 'translateY(100px)', opacity: 0 }}
    enter={{ transform: 'translateY(0px)', opacity: 1 }}
    leave={{ transform: 'translateY(100px)', opacity: 0 }}
  >
    {item => props => {
      return (
        <StableRoute initialRoutePath={routePath} key={item}>
          <animated.div style={props}>{element}</animated.div>
	    </StableRoute>
	  )
    }}
  </Transition>
)
          
function StableRoute({ initialRoutePath, children }: React.PropsWithChildren<{ initialRoutePath: string }>) {
  const routePath = useRef(initialRoutePath);
  return (
    <routePathContext.Provider value={routePath}>
      {children}
    </routePathContext>
  )   
}
```

**Comment by dictions** [comment]
@SleeplessByte thanks for the info!

That provided enough info to come up with a solution:

```
import React, { Suspense, useRef } from "react";
import { Router, Location } from "@reach/router";
import { Root, Head, Routes, routePathContext } from "react-static";

const PersistentRoutePathContextProvider = ({ initialRoutePath, children }) => {
  const routePath = useRef(initialRoutePath);

  return (
    <routePathContext.Provider value={routePath.current}>
      {children({ routePath: routePath.current })}
    </routePathContext.Provider>
  );
};

const PersistentRouter ({ location, render }) => (
  <Router location={location}>
    <Routes
      path="*"
      render={({ getComponentForPath, routePath }) =>
        render({
          getComponentForPath,
          routePath,
          children: (
            <PersistentRoutePathContextProvider initialRoutePath={routePath}>
              {({ routePath }) => getComponentForPath(routePath)}
            </PersistentRoutePathContextProvider>
          ),
        })
      }
    />
  </Router>
);

const App = () => (
  <Root>
    <Suspense fallback={""}>
      <Location>
        {({ location }) => (
          <PersistentRouter location={location} render={AnimatedRoute} />
        )}
      </Location>
    </Suspense>
  </Root>
);

//
// === Usage ===
//

const AnimatedRoute = ({ routePath, children }) => (
  <AnimatePresence exitBeforeEnter>
    <motion.div
      key={routePath}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
    >
      {children}
    </motion.div>
  </AnimatePresence>
);

<Location>
  {({ location }) => (
    <PersistentRouter location={location} render={AnimatedRoute} />
  )}
</Location>;

```

**Comment by SleeplessByte** [comment]
Sweet!


Does this work?
