### ISSUE TITLE
[Bug] Corrupt sitemap.staging.xml

### ISSUE THREAD

**Issue by humatic** [react-static/react-static#1587]
### Steps to Reproduce the problem

I have a new react-static project with a mostly default configuration. In `static.config.js`, I've set the site root: `siteRoot: 'https://mydomain.com'` (but I don't think this is relevant, since the issue is only for the staged version).

1. Run `npm run stage` and see that a sitemap file is created: `dist/sitemap.staging.xml`.Great.
2. Run `npm run serve` and point the browser to `http://localhost:3000` (or wherever you're hosting locally). For me, I get an error like this:

![Screenshot from 2021-03-15 16-13-37](https://user-images.githubusercontent.com/4943090/111167336-ad655a80-85a9-11eb-852f-23a732b1547e.png)

3. Open up the `dist/sitemap.staging.xml` in an editor and notice that it's unintelligible. For one thing, there are too many newlines.

I'm guessing that the issue stems from one or more of the `.join(staging ? '\n' : '')` calls in [this file](https://github.com/react-static/react-static/blob/v7.5.3/packages/react-static-plugin-sitemap/src/buildXML.js).

### Expected Behavior

`sitemap.staging.xml` contains valid XML that the browser can recognize.

Please note that the production version of `sitemaps.xml` builds correctly (i.e., produced with `npm run build`).

### Environment
  
    System:
      OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 1.09 GB / 15.41 GB
      Container: Yes
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Browsers:
      Chrome: 88.0.4324.182
      Firefox: 86.0
    npmPackages:
      react: ^16.14.0 => 16.14.0 
      react-dom: ^16.14.0 => 16.14.0 
      react-hot-loader: ^4.13.0 => 4.13.0 
      react-static: ^7.5.1 => 7.5.3 
      react-static-plugin-reach-router: ^7.5.1 => 7.5.3 
      react-static-plugin-sass: ^7.3.0 => 7.3.0 
      react-static-plugin-sitemap: ^7.5.3 => 7.5.3 
      react-static-plugin-source-filesystem: ^7.5.1 => 7.5.3 
    npmGlobalPackages:
      react-static: 7.5.3

**Comment by SleeplessByte** [comment]
To make this easier for someone to discover, can you post _both_ a correctly generate `sitemap.xml` and the "broken" staging `sitemap.xml`.

**Comment by humatic** [comment]
It shouldn't be too hard to reproduce. Here are some samples of what the XML looks like.

**Good**: `sitemap.xml` generated with `npm run build`:
```
<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml"><url><loc>https://mydomain.com/contact/</loc></url><url><loc>https://mydomain.com/team/</loc></url>

... etc ...

</urlset>
```

**Bad**: `sitemap.staging.xml` generated with `npm run stage`:
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
<
l
o
c
>
/
c
o
n
t
a
c
t
/
<
/
l
o
c
>

</url>
<url>
<
l
o
c
>
/
t
e
a
m
/
<
/
l
o
c
>

</url>

... etc ...

</urlset>
```
