### ISSUE TITLE
[Bug] TypeScript template does not support image import

### ISSUE THREAD

**Issue by ngocdaothanh** [react-static/react-static#1589]
I'd like to import an image, but there's error:

```
TS2307: Cannot find module './logo.png' or its corresponding type declarations.
     6 | import './app.css'
     7 |
  >  8 | import logo from './logo.png'
       |                  ^^^^^^^^^^^^
```

How to fix please?

**Comment by ngocdaothanh** [comment]
I like the simplicity of react-static very much, but because of this issue, I have to switch to Gatsby (hopefully just temporarily).

**Comment by ksekachev** [comment]
@ngocdaothanh hi, I think this issue is not related to React-static, please, try to follow Step 3 and Step 4 from [this guide](https://stackoverflow.com/questions/43638454/webpack-typescript-image-import?rq=1).

**Comment by SleeplessByte** [comment]
@ksekachev is correct. This is unrelated.

**Comment by ngocdaothanh** [comment]
It's not related to react-static core, but the TypeScript template is inside react-static repo, it should be improved to have the image import preconfigured, so that users won't have trouble using react-static?

https://github.com/react-static/react-static/tree/master/packages/react-static/templates/typescript

**Comment by SleeplessByte** [comment]
Yes, we'll definitely take a PR 🥳 😄

**Comment by ngocdaothanh** [comment]
👍 I've created this PR:
https://github.com/react-static/react-static/pull/1597
