### ISSUE TITLE
Webpack rules change does not work

### ISSUE THREAD

**Issue by Lenetta** [react-static/react-static#1604]
Hi. I want to change the webpack rules, but even using the default loader doesn't work. What am I doing wrong? Help me please.

Code from node.api.js
`const assetsLoader = (outDir) => ({
  loader: "url-loader",
  options: {
    limit: 10000,
    fallback: "file-loader",
    // outputPath: outDir,
    // name: "static/[name].[hash:8].[ext]",
  },
});

export default (pluginOptions) => ({
  webpack: (config, { defaultLoaders }) => {
    // defaultLoaders.fileLoader.exclude.push(/\.svg?$/);
    const svgLoader = {
      test: /\.svg?$/,
      oneOf: [
        {
          issuer: /\.scss?$/,
          use: assetsLoader("images"),
        },
        {
          issuer: /\.tsx?$/,
          use: "@svgr/webpack",
        },
      ],
    };

    config.module.rules = [
      {
        oneOf: [
          defaultLoaders.jsLoader,
          defaultLoaders.jsLoaderExt,
          defaultLoaders.cssLoader,
          defaultLoaders.fileLoader,
        ],
      },
    ];

    return config;
  },
});`
Result in browser http://prntscr.com/126y56c

**Comment by h0tw4t3r** [comment]
Hey, I wouldn't be that fast to add "bug" label here, your message looks kinda, uhm, broken 😅

If you can provide an example with codesandbox, people could will see if it is a bug or not.
