### ISSUE TITLE
content not showing view page source

### ISSUE THREAD

**Issue by kmaheshgit** [react-static/react-static#1613]
view page source is always showing landing page info/content for all routes. Can someone help me how to overcome this? Thanks in advance!

**Comment by SleeplessByte** [comment]
Refresh the page, or open links in a new tab, or disable JavaScript. This is not a bug.

What happens is that you're experiencing JavaScript Router based navigation when you're clicking them in your browser, so the _initial page source_ isn't updated nor is it supposed to.
