### ISSUE TITLE
[Bug] Sitemap plugin generating URLs with trailing slashes

### ISSUE THREAD

**Issue by philip-healy** [react-static/react-static#1615]
### Environment
```

  System:
    OS: Linux 4.4 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 20.40 GB / 31.82 GB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    npm: 6.14.11 - /usr/local/bin/npm
  npmPackages:
    react: ^16.14.0 => 16.14.0
    react-dom: ^16.14.0 => 16.14.0
    react-ga: ^3.3.0 => 3.3.0
    react-google-recaptcha: ^2.1.0 => 2.1.0
    react-hot-loader: ^4.13.0 => 4.13.0
    react-static: ^7.5.1 => 7.5.3
    react-static-plugin-reach-router: ^7.5.1 => 7.5.3
    react-static-plugin-sitemap: ^7.5.1 => 7.5.3
    react-static-plugin-source-filesystem: ^7.5.1 => 7.5.3
    react-static-plugin-svg: 0.0.1 => 0.0.1
  npmGlobalPackages:
    react-static: 7.5.3

```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  `npm run build`
2.  `cat dist/sitemap.xml`

### Expected Behavior

The sitemap URLs should not have trailing slashes. Google Search Console complains about them.

The sitemap URLs (with slashes) generated for my site do work, but the 404 page flashes before the page content appears.

The example output in the documentation for the sitemap plugin does not have trailing slashes in the URLs.

**Comment by deiga** [comment]
@philip-healy What exactly is the complaint from Google Search Console?

AFAIK both forms are totally valid (with or without slash) as long as one is consistent about it. I wouldn't categorise this as a bug, but rather a feature request to add a config for toggling slashes at the end of URLs.

The documentation mismatch I would call a bug though.

> The sitemap URLs (with slashes) generated for my site do work, but the 404 page flashes before the page content appears.

Are you sure this is not a configuration issue in your site? At least on my site there is no 404 flash (https://amboss.com/us/knowledge/Pneumonia/)

**Comment by philip-healy** [comment]
@deiga further investigation of the Google Search Console reveals that it's the same issue - it is flagging a problem because it sees the 404 page first. It's probably something to do with my router configuration.

Having said that, a config option for toggling slashes at the end of URLs would be welcome, as I consider the ones without slashes to be the canonical ones. Also, as you point out, there is a mismatch between the documented behavior and what is seen in practice.

Should I close this issue and recreate it as a feature request for the config option?

**Comment by SleeplessByte** [comment]
Yes please.

**Comment by philip-healy** [comment]
Thanks @SleeplessByte and @deiga. I have tracked down the source of the 404 flash by the way - it is because the site is hosted on S3. The behavior around trailing slashes differs from what you would expect. Closing this issue now.

**Comment by SleeplessByte** [comment]
I've ran into that myself. I always front it using cloudfront and use lambda @ edge to rewrite URLs to fix this.

Same issue with other static solutions.
