### ISSUE TITLE
Loading styles on Production take too long 

### ISSUE THREAD

**Issue by Alii-isk** [react-static/react-static#1622]
### Reporting a bug?
i deployed to netlify  and when i open the link the website displays the html skeleton without css and after 9 seconds or more it loads the css styles
why is that happening??

### Environment

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Memory: 2.67 GB / 5.90 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    react: ^16.14.0 => 16.14.0
    react-dom: ^16.14.0 => 16.14.0
    react-hot-loader: ^4.13.0 => 4.13.0
    react-icons: ^4.2.0 => 4.2.0
    react-reveal: ^1.2.2 => 1.2.2
    react-static: ^7.5.1 => 7.5.3
    react-static-plugin-reach-router: ^7.5.1 => 7.5.3
    react-static-plugin-sitemap: ^7.5.1 => 7.5.3
    react-static-plugin-source-filesystem: ^7.5.1 => 7.5.3
    react-static-plugin-typescript: ^7.5.1 => 7.5.3

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  yarn bundle
2.  yarn export
3.  deploy to netlify

### Expected Behavior

the website should load the styles quickly

**Comment by SleeplessByte** [comment]
Perhaps you have _a lot_ of styles? Maybe it's your browser/computer/connection. Lots of things that can cause this, but `react-static` does **not** influence this.

This is not really a problem `react-static` can solve, nor is it a `react-static` bug. Perhaps StackOverflow can help you further?

**Comment by Alii-isk** [comment]
> Perhaps you have _a lot_ of styles? Maybe it's your browser/computer/connection. Lots of things that can cause this, but `react-static` does **not** influence this.
> 
> This is not really a problem `react-static` can solve, nor is it a `react-static` bug. Perhaps StackOverflow can help you further?

i forgot to mention that i am using styled components maybe that's what causing the problem any way i migrated to NextJs
