### ISSUE TITLE
The published version of react-static-plugin-sass on npm is causing problems on projects using Node 16

### ISSUE THREAD

**Issue by jeanlescure** [react-static/react-static#1623]
When installing the plugin `react-static-plugin-sass`, I get the following error:

```
error: 'remove_cv_t' is not a member of 'std'; did you mean 'remove_cv'?
```

This can be traced back to the now deprecated `node-sass` package which is a dependency of the npm published version of the aforementioned plugin.

I see there was a PR (https://github.com/react-static/react-static/pull/1621) which would solve this issue had it been published to npm, I left the following comment on the PR as well:

@deiga @SleeplessByte I think you guys forgot to release a new version of this plugin. It is still on 7.3.0 (which was released a year ago on npm). I was trying to use react-static-plugin-sass on a project under Node 16 but it breaks due to a problem on the old version of node-sass that the published version of react-static-plugin-sass depends on.

_Originally posted by @jeanlescure in https://github.com/react-static/react-static/issues/1621#issuecomment-888769289_

**Comment by jeanlescure** [comment]
I also see that the root version of react-static is ahead of the version in npm. It seems that even though the build passed on Travis CI and the changes have been promoted to master, there has been no publish of the packages.

Any project using Node 16, depending on SASS support, and looking to adopt react-static will meet the same error I described. Is there anything else that needs to happen before publishing?

**Comment by ivanoats** [comment]
I just noticed 7.6.0 is out so I think we can close this issue.
