### ISSUE TITLE
react-static + i18next

### ISSUE THREAD

**Issue by VovaParamonov** [react-static/react-static#1624]
Does anyone have experience integrating react-static with i18next or other multilingual libraries?

I can't configure the SSR correctly in any way. I tried to use the gatsby article of 2017, but I couldn't make friends with the configs.

I will be glad of any advice and sorry for my English

**Comment by sti-web** [comment]
Hi @VovaParamonov,
I used https://github.com/woffrek/react-static-plugin-localized plugin for multilingual support. Not ideal, but works

**Comment by VovaParamonov** [comment]
Thanks, @sti-web
