### ISSUE TITLE
[Docs] Internationalized html files (for SEO)?

### ISSUE THREAD

**Issue by larissa-n** [react-static/react-static#1653]
Can react-static build pages in different languages?

[Adding a i18n library](https://github.com/react-static/react-static/issues/475) for localizing content was discussed before, but without javascript enabled, a react-static page just shows the i18n IDs, not any translated text. Docusaurus, another static site generator, automatically generates HTML files for every language (so it can be indexed by search engines like Bing that don't usually crawl JS-rendered content). Is there a way to have react-static generate different HTML files for different languages?

I see a concept proposed [here](https://github.com/react-static/react-static/issues/475#issuecomment-472573965) for pages listed manually in `static.config.js`, but it seems from [other comments](https://github.com/react-static/react-static/issues/475#issuecomment-583897660) that there are still quite a few open questions (like how to make this work with `react-static-plugin-source-filesystem`). Internationalization tends to be a common feature of most SSGs and it would be helpful to have a working solution in the docs, or at least be clear what react-static can and cannot do.

**Comment by SleeplessByte** [comment]
Addin some i18n library doesn't magically create the pages. You'll need to manually list them in config.js. Then they would be statically generated. Still would need some way to serve the right page to the right people.

**Comment by larissa-n** [comment]
Exactly. [Nextjs](https://nextjs.org/docs/advanced-features/i18n-routing) and [Gatsby](https://www.gatsbyjs.com/docs/how-to/adding-common-features/localization-i18n/) have great docs for how to implement routing with localized content. If localization is something react-static wants to support, there might be some documentation ideas there. [react-static-plugin-localized](https://www.npmjs.com/package/react-static-plugin-localized) could also be worth a mention.
