### ISSUE TITLE
Support for Yarn 2

### ISSUE THREAD

**Issue by KubukaH** [react-static/react-static#1658]
Thank you for creating this project. It solves a lot of challenges associated with a normal Create-React-App. But My challenge is that it seems the API is still using Yarn 1. I hope you are working out features to support Yarn 2. As it stands, I created a repo, cloned it, and set `yarn init -2` to utilize Yarn 2. It installs the dependencies well, except one peer dependency which I have to manually configure in the `.yarnrc.yml`. 

Upon running `yarn start`, a list of errors appears ad shown in the screenshot below:
![react-starter-error](https://user-images.githubusercontent.com/87326201/157636693-e285e21b-8bb7-4f78-b912-772306d5407d.png)

I hope this error is only appearing when using Yarn 2 because I didn't test using `npm` or Yarn 1.

Thank you.

**Comment by SleeplessByte** [comment]
We're not compatible with Yarn 2 or 3.
