### ISSUE TITLE
[Help] Dynamic Routes with statically generated data

### ISSUE THREAD

**Issue by loginov-rocks** [react-static/react-static#1667]
Hello! Thank you for this marvelous project!

If possible, I'd appreciate any help in accomplishing the following goal: create dynamic routes which will have the capability to work with data generated at build time, similar to regular `getRoutes`.

The idea is to have some pages not exported to HTML (for example to prevent SEO), but still get data at a build time not to expose the data source to clients. So these pages will have their own `routeInfo` requests probably.

So far I see the only option is to build the data with the help of `getSiteData`, however, it is gathered at the site level and will be quite heavy to preload on all pages. Is there anything else I'm missing?

Thanks!

**Comment by SleeplessByte** [comment]
These documents may help you:

- https://github.com/react-static/react-static/blob/0a3e465acd1853510de808d0464f53ec54a3c0bf/docs/guides/dynamic-routes-reach-router.md
- https://github.com/react-static/react-static/blob/82c412265560c164cc19daabde9064b4679090d6/docs/guides/dynamic-routes-react-router.md

You also want to exclude these from prefetching: https://github.com/react-static/react-static/blob/a77368f7cf0adac52adf58fd643d3916de14bf06/docs/api.md#addprefetchexcludes
.

Good luck!

**Comment by loginov-rocks** [comment]
@SleeplessByte hi, thank you for your answer! I understand the dynamic routing, the challenge is to get data generated at a build time for dynamic routes :) Still appreciate any help.
