### ISSUE TITLE
react-hot-loader should be a peer dependency installed on app level

### ISSUE THREAD

**Issue by Hypnosphi** [react-static/react-static#743]
`react-hot-loader/babel` adds imports of `react-hot-loader` directly from app's code. Therefore, it's crucial to have this module directly in app's `node_modules`. The only way to guarantee it is to have a direct dependency on app level.

An alternative is to add a `resolve.alias` in webpack config.

**Comment by tannerlinsley** [comment]
I think we'll probably go the route of an `alias` in webpack.
