### ISSUE TITLE
CSS hot reloading does not work in v6

### ISSUE THREAD

**Issue by KidkArolis** [react-static/react-static#783]
### Are you reporting a bug?

Yes.

### Environment

1.  `react-static -v`: 6.0.0-beta.21
2.  `node -v`: v10.11.0
3.  `yarn --version or npm -v`: 1.10.1
4.  Operating system: macOS

### Steps to Reproduce the problem

1.  npm i -g react-static@6.0.0-beta.21
2.  react-static create
3.  choose basic
4. yarn start
5. modify app.css

### Expected Behavior

CSS should hot reload, but it doesn't

I've been using react-static@6 beta since 6.0.0-beta.14 and css hot reloading never worked for me.

**Comment by tannerlinsley** [comment]
Are you referring to css in js or css imports?

**Comment by KidkArolis** [comment]
It used to work in 5, but doesn't work in 6.
I can see webpack's hot.json activity in the network panel after making changes, but nothing updates in the page.

**Comment by tannerlinsley** [comment]
I'll take a look at this today. Thanks for your info.

**Comment by KidkArolis** [comment]
Cross posted here: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/110

**Comment by KidkArolis** [comment]
Everything's too complicated :( there are too many plugins for plugins for plugins for webpack, all hacks :(

I'm opening a PR that uses style-loader in dev, but couldn't properly test in my project, since I'm struggling to run react-static in linked mode, seeing issues like:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/324440/46529317-fc155300-c88d-11e8-96b0-a85a0e4eede3.png">
and
<img width="394" alt="image" src="https://user-images.githubusercontent.com/324440/46529329-046d8e00-c88e-11e8-8624-e79218fa9d56.png">

**Comment by tannerlinsley** [comment]
@ScriptedAlchemy Thoughts on this?

**Comment by ScriptedAlchemy** [comment]
Okay, ill check out what the config is like in react static. Ive added a switch for hmr, and for css modules. In that case, we might need to expose an additional option to the user if we cannot infer it from some other flag. 

What i hope, is that if i just recursively run `yarn upgrade extract-css-chunks` it will just work :) 

Ill update as im investigating

**Comment by ScriptedAlchemy** [comment]
After initial investigations, it looks like there is some kind of miss-configuration which causes the HMR capability to get ignored. I have some extreme options for users who have issues with HMR, one being to just reload any and all css in the system.

The issue here is that my hot loading is not triggered at all, as if the HMR loader is never registered. 

Still investigating the cause

**Comment by LABCAT** [comment]
This seems to be broken in 7.2.0. Is there anything I can do to create hot reloading to work for CSS/SCSS?

**Comment by SleeplessByte** [comment]
It's not broken. If it doesn't work, it's because of the particular set-up you're using :). Best bet is the spectrum community for support questions like that.

**Comment by LABCAT** [comment]
@SleeplessByte tested on both windows 10 and Ubuntu 18 with both blank and basic installation. Changing the CSS doesn't result in any changes until you refresh your browser.

Works fine when using "create react app" so nothing to do with the set up I'm using :) Care to share your configuration?

Should I create a new bug report? or does someone want to reopen this one?

**Comment by SleeplessByte** [comment]
I currently don't have the capacity to try to reproduce this, but definitely welcome all help here. 

Might be worthwhile to try to build `react-static` from `master` and from #1375 ; it might be solved in either.

**Comment by pztrick** [comment]
I encountered this on a vanilla project after adding only the `react-static-plugin-stylus` plugin.

HMR didn't work for my Stylus stylesheets.

My work-around is below:

```
// index.js

import './stylesheets/index.styl'

// ...

if (module && module.hot) {
    module.hot.accept('./app', () => {
        render(App)
    })
    module.hot.addStatusHandler(status=>{
        if(status != 'apply'){
            return
        }
        (async () => {
            let head = document.getElementsByTagName('head')[0]
            let cssRef = head.querySelector('link')
            let newRef = document.createElement('link')
            newRef.setAttribute('rel', 'stylesheet')
            newRef.setAttribute('type', 'text/css')
            newRef.setAttribute('href', `main.css?c=${Date.now().toString()}`)
            head.appendChild(newRef)
            setImmediate(()=>{cssRef.remove()})
        })()
    })
}
```

This will reload the transpiled CSS on all code changes. I'm sure there is a better way to do things but I'm not familiar with the HMR life-cycle and API.

Hope this helps someone.
