### ISSUE TITLE
Typescript example doesn't include styled-components

### ISSUE THREAD

**Issue by meel-io** [react-static/react-static#814]
**Describe the bug**
According to README, Typescript example is supposed to include styled-components. I'll be happy to add it if agreed.

**Expected behavior**
[styled-components](https://github.com/styled-components/styled-components) package should be included at install and template components should use it if needed.

**Comment by PeterKottas** [comment]
Typescript example is in fact totally broken (uses old getSiteProps and getRouteProps vs new getSitedData getRouteData functions) I assume when v6 lands, there should be some template cleanup to bring these up to date.
