### ISSUE TITLE
Lots of routeInfo.json requests on page load

### ISSUE THREAD

**Issue by jamesplease** [react-static/react-static#826]
:wave: Hi there

**Describe the bug**

react-static loads a lot of routeInfo.json files when my app loads. This is unexpected, because it locks up the network tab for a noticeable time.

This is having a negative effect on application load times.

Separately, it's worrisome that the number of routeInfo.json's grows with each URL that I add to my app. Is it correct that an app with 2k pages would make 2k network requests before the application code loads?

Presently, I have ~30 pages, and with each routeInfo.json taking 40ms, this adds up to an entire second of these files being loaded before anything else loads.

Do I have something misconfigured?

**To Reproduce**

1. Navigate to [materialish.js.org](materialish.js.org)
2. Look at the network tab

**Expected behavior**

react-static would make a reasonable, set number of network requests on page load.

**Screenshots**

![image](https://user-images.githubusercontent.com/2322305/47187544-60520100-d2e9-11e8-8c38-1e50981e6842.png)

---

Thanks for taking the time to check out this issue!

**Comment by tannerlinsley** [comment]
Are you using react statics link component in v5? Are so of your links
visible in the viewport on load?

**Comment by jamesplease** [comment]
> Are you using react statics link component in v5?

I am, yeah:

```jsx
import { Link } from 'react-static';
```

> Are so of your links visible in the viewport on load?

The majority of them are visible. I'd say somewhere around 30% of them are hidden behind a "collapsible" element when the page loads, but 70% are visible onscreen.

**Comment by tannerlinsley** [comment]
The way the link works in v5 is based on visibility and intersection with
the window. It could be false positively preloading links that aren't
actually visible.

**Comment by jamesplease** [comment]
That sounds like a plausible explanation. Is it possible to disable preloading altogether? I just checked the docs, but nothing stood out to me as being a config for that behavior. Possibly `prefetchRate: 0`?

**Comment by tannerlinsley** [comment]
Technically yes. Though it could have unintended consequences. I'm away
from my computer right now. But could easily dig in deeper later.

**Comment by jamesplease** [comment]
No rush. I'll hold off on making that change for now. Should you have time to look into this more thoroughly, I'd appreciate it a lot!

Thanks for your help so far. And thanks also for all of the work you've put into react-static 🙂

**Comment by tannerlinsley** [comment]
I appreciate it. I'll look into it soon.

**Comment by tannerlinsley** [comment]
So I did some more digging. It looks like on first load, things are really good:
<img width="1219" alt="screen shot 2018-10-18 at 8 52 07 pm" src="https://user-images.githubusercontent.com/5580297/47195114-b50c7080-d317-11e8-9af9-97976778b654.png">
It's not firing off any unnecessary calls so far.

Then, when I open the sidebar, you'll see quite a few preloads fire off:
<img width="1221" alt="screen shot 2018-10-18 at 8 51 54 pm" src="https://user-images.githubusercontent.com/5580297/47195115-b50c7080-d317-11e8-89f9-e1ef1e31cd2f.png">
This is actually working as intended so far. It preloaded all of the links that became visible with the menu toggle. It also does this at the default prefetch rate of 10 at a time.

You can see as you scroll down the page, the rest of the links also preload when they become visible:
<img width="1218" alt="screen shot 2018-10-18 at 8 54 45 pm" src="https://user-images.githubusercontent.com/5580297/47195295-7fb45280-d318-11e8-9391-17a0f9271651.png">

So to my knowledge, this is working really well. It doesn't appear to be prefetching anything that isn't visible[ either. I would say you could play with the [`config.prefetchRate`](https://react-static.js.org/docs/config/#prefetchrate) if you want to throttle things a bit more for mobile.

**Comment by tannerlinsley** [comment]
It's also worth noting that in v6 (coming out hopefully in about a month), the preloader will be much better, or at least, more customizable and pluggable.
