### ISSUE TITLE
styled-components example on v6 is outdated and doesn't work.

### ISSUE THREAD

**Issue by nashequilibro** [react-static/react-static#876]
### Are you reporting a bug?

Yes:

The styled-components basic example uses styled-components v4 and fails because it still uses the old injectGlobal syntax:

`Attempted import error: 'injectGlobal' is not exported from 'styled-components'.`

Changing the code in App.js to the styled-components v4 example on how to use the new GlobalStyle:

```
import { createGlobalStyle } from "styled-components";
const GlobalStyle = createGlobalStyle`
  html {
    color: red;
  }
`;
export default function App() {
  return (
    <div>
      <GlobalStyle />
      This is my app!
    </div>
  );
}
```

does not work as the hot reloading fails with:

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### Environment

1.  `react-static 6.0.0`:
2.  `node 10.9.0`:
3.  `npm 6.4.1`:
4.  Operating system: Win 10

### Steps to Reproduce the problem

1.  react-static create with styled-components plugin
2.  yarn start

### Expected Behavior

It should start.

**Comment by mariovde** [comment]
Exact same error here... Any ideas on this one?

**Comment by tannerlinsley** [comment]
I just updated react-hot-loader to the latest version which should fix this. Try again with the latest version?

**Comment by mariovde** [comment]
Just did a re-install, and still a no-go.
updated App.js to use createGlobalStyle. 

yarn start now starts up a server.
But got this error in chrome:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `App`.

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    at invariant (react-dom.development.js:59)

**Comment by tannerlinsley** [comment]
Please post your code you are attempting to use from App.js

**Comment by mariovde** [comment]
`    import React from 'react'
    import { Root, Routes, Link } from 'react-static'
    import styled, { createGlobalStyle } from 'styled-components'
    
    //
    
    const GlobalStyle = createGlobalStyle`
      body {
        font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', Helvetica, Arial,
          'Lucida Grande', sans-serif;
        font-weight: 300;
        font-size: 16px;
        margin: 0;
        padding: 0;
      }
    `
    
    const AppStyles = styled.div`
      a {
        text-decoration: none;
        color: #108db8;
        font-weight: bold;
      }
    
      nav {
        width: 100%;
        background: #108db8;
    
        a {
          color: white;
          padding: 1rem;
          display: inline-block;
        }
      }
    
      .content {
        padding: 1rem;
      }
    
      img {
        max-width: 100%;
      }
    `
    
    const App = () => (
      <Root>
        <AppStyles>
          <GlobalStyle />
          <nav>
            <Link exact to="/">
              Home
            </Link>
            <Link to="/about">About</Link>
            <Link to="/blog">Blog</Link>
          </nav>
          <div className="content">
            <Routes />
          </div>
        </AppStyles>
      </Root>
    )
    
    export default App
    `

**Comment by tannerlinsley** [comment]
Run these commands, then try again:

```bash
yarn add react-static@latest react-static-plugin-styled-components@latest
# or
npm i react-static@latest react-static-plugin-styled-components@latest
```

**Comment by mariovde** [comment]
@tannerlinsley I tried the commands you provided, but problem still persists.

**Comment by Pixelatex** [comment]
Eureka!

The issues seems to be the link component. It's still being imported from 'react-static'

I added `import { Link } from '@reach/router'` and it runs!

**Comment by Pixelatex** [comment]
That and removing the AppContainer component from this method:

```
 renderMethod(
      <AppContainer>
        <Comp />
      </AppContainer>,
      document.getElementById('root')
    )
```

**Comment by Pixelatex** [comment]
https://github.com/nozzle/react-static/pull/889

**Comment by sgup** [comment]
Running into the same issues. Wary of removing the code above though, will it break other features?

**Comment by mariovde** [comment]
@Pixelatex your solution works indeed.
But removing AppContainer from react-hot-loader, won't it affect performance in some way?
